### ISSUE TITLE
An unhandled exception occurred: Cannot find module '@angular-devkit/custom-webpack/package.json

### ISSUE THREAD

**Issue by msms007** [just-jeb/angular-builders#1016]
## Describe the Bug

getting an error when including custom webpack

## Minimal Reproduction

An unhandled exception occurred: Cannot find module '@angular-devkit/custom-webpack/package.json'
Require stack:
- /Users/{name}/Dev/twilio/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js

#Package JSON

"dependencies": {
    "@angular/animations": "~12.1.1",
    "@angular/common": "~12.1.1",
    "@angular/compiler": "~12.1.1",
    "@angular/core": "~12.1.1",
    "@angular/forms": "~12.1.1",
    "@angular/platform-browser": "~12.1.1",
    "@angular/platform-browser-dynamic": "~12.1.1",
    "@angular/router": "~12.1.1",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "twilio-client": "^1.14.0",
    "util": "^0.12.4",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-builders/custom-webpack": "^12.1.0",
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular/cli": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.2.3"
  }

**Comment by just-jeb** [comment]
Probably a wrong entry in `angular.json`. Try `@angular-builders/custom-webpack` and not `@angular-devkit/custom-webpack`. 😄

**Comment by matadorhernan** [comment]
> Probably a wrong entry in `angular.json`. Try `@angular-builders/custom-webpack` and not `@angular-devkit/custom-webpack`. 😄
same x2
