### ISSUE TITLE
Module not found: Error: Can't resolve 'zone.js/plugins/zone-legacy'

### ISSUE THREAD

**Issue by iwt-philipzeh** [just-jeb/angular-builders#1020]
## Describe the Bug

getting an error when including custom webpack browser target

## Minimal Reproduction
`../../node_modules/@angular-devkit/build-angular/src/webpack/es5-polyfills.js:106:0-37 - Error: Module not found: Error: Can't resolve 'zone.js/plugins/zone-legacy' in '/Users/pzeh/Work/team/UI/project-ui/node_modules/@angular-devkit/build-angular/src/webpack'

## Environment

Libs
- @angular/core version: 12.1.3
- @angular-devkit/build-angular version: 12.1.3
- @angular-builders/custom-webpack" version: 12.1.0

<pre><code>
angular.json
"build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./webpack.config.ts"
            },
            "outputPath": "dist/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "baseHref": "/",
            "outputHashing": "all",
            "assets": ["src/favicon.ico", "src/assets"],
            "styles": ["src/styles/styles.scss"],
            "stylePreprocessorOptions": {
              "includePaths": ["src/app/components"]
            },
            "scripts": [],
            "aot": false,
            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true
          }
</code></pre>
For Tooling issues:
- Node version: 12.18.3
- Platform:   Mac

## Additional Context

I did a clean install, removed node_modules first.  I use yarn workspaces.

**Comment by iwt-philipzeh** [comment]
Sorry that i bothered you. 
We did a mistake back when we migrated from angular 9 to angular 10 which ultimately resulted in this issue. I fixed it by undoing all migrations, migrated again and switched from tslint to eslint. What a bummer :D

**Comment by Parth7030** [comment]
+1
