### ISSUE TITLE
No implicit any tsconfig cause issue with webpack config factory

### ISSUE THREAD

**Issue by GerkinDev** [just-jeb/angular-builders#1031]
## Describe the Bug

I'm using a factory to generate my webpack browser & server configuration. My application tsconfig is in full strict mode. When running the builder for the browser, it seems that type annotations are removed **before** typescript compilation, causing errors related to implicit `any` types.

## Minimal Reproduction

```ts
import { Configuration } from 'webpack';

export type ConfigFactory = ( baseConfig: Configuration, ngBuildConfig: any, ngBuildTarget: any ) => Configuration;

const factory: ConfigFactory = ( baseConfig, ngBuildConfig, ngBuildTarget ) => {
    // ...
}
export default factory;
```

Build fails with following message:

```
An unhandled exception occurred: ⨯ Unable to compile TypeScript:
configs/build/webpack.browser.config.ts:15:18 - error TS7006: Parameter 'baseConfig' implicitly has an 'any' type.

15 const factory = (baseConfig, ngBuildConfig, ngBuildTarget) => {
                    ~~~~~~~~~~
configs/build/webpack.browser.config.ts:15:30 - error TS7006: Parameter 'ngBuildConfig' implicitly has an 'any' type.

15 const factory = (baseConfig, ngBuildConfig, ngBuildTarget) => {
                                ~~~~~~~~~~~~~
configs/build/webpack.browser.config.ts:15:45 - error TS7006: Parameter 'ngBuildTarget' implicitly has an 'any' type.

15 const factory = (baseConfig, ngBuildConfig, ngBuildTarget) => {
                                               ~~~~~~~~~~~~~

See "/tmp/ng-lUATx4/angular-errors.log" for further details.
```

## Expected Behavior

Build should work.

## Environment

<pre><code>
Libs
- @angular/core version: 12.0.5
- @angular-devkit/build-angular version: 12.2.4
- @angular-builders/custom-webpack version: 12.1.1

For Tooling issues:
- Node version: 16.7.0
- Platform:  Fedora Linux x64

Others:

</code></pre>

## Additional Context

Seemms related to #749.

I've managed to fix the issue localy by editing https://github.com/just-jeb/angular-builders/blob/66b21aa50d31ae06ff4a3467851f068680f70cc9/packages/custom-webpack/src/utils.ts#L9-L17 and adding `transpileOnly`:
```ts
    require('ts-node').register({
      project: tsConfig,
      compilerOptions: {
        module: 'CommonJS',
        transpileOnly: true,
        types: [
          'node', // NOTE: `node` is added because users scripts can also use pure node's packages as webpack or others
        ],
      },
    });
```

Funny thing is that somehow, the server build is not impacted by this, but use the exact same factory signature.

**Comment by just-jeb** [comment]
Hey, thanks for raising it. Yup, seems like the `ts-node` double registration issue again.  
Not sure that you're "fixing" it by using `transpileOnly`, it is more likely you're just hiding the problem (although it will works since Javascript is a subset of Typescript).  

Could you please create a minimal reproduction repo so that I could check it out? Thanks!

**Comment by GerkinDev** [comment]
Have you à boilerplate or something? To be honest, a repro for tooling such as yours is quite expensive in time: install angular, install your builder, tweak angular json configs (which is a pain), etc... That's not huge but it is big enough to discourage some users to do so, compared to some packages where a repro is a simple npm i + 3 lines of code.

**Comment by just-jeb** [comment]
You have a few example apps which you can take as a boilerplate (or even fork the repo if you want). For example: https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack/examples/sanity-app

**Comment by GerkinDev** [comment]
Thank you, I'm on it. I've got one additional information already: the bug only occurs when having both a typescript `indexTransform` and a typescript `customWebpackConfig`.
Here is the repro: https://github.com/GerkinDev/angular-builders-1031

I'm trying to do the same for server builds.

**Comment by GerkinDev** [comment]
Commit https://github.com/GerkinDev/angular-builders-1031/commit/6ac2a481e7f19e5deab9f7bc8e302745e4391ae8 adds demo with SSR. Note that SSR build use a special browser target not causing issue mentioned above, so that you can see that server SSR works as intended by itself.

Use `npm run start` for browser build only and `npm run start:ssr` for server+browser build.

**Comment by just-jeb** [comment]
> I've got one additional information already: the bug only occurs when having both a typescript indexTransform and a typescript customWebpackConfig.

This actually gives me a clue on what's going on here: we're registering the `ts-node` in two places - once for [`indexTransform`](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/transform-factories.ts#L30) and then for the [webpack config](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/custom-webpack-builder.ts#L68). Since there is no check whether it was already registered, it's being registered twice and then the TS code is being transpiled twice. Need to add a check and it should fix this.   

Thanks for the info, it helps a lot. Hope to get to this soon, but since we're entering a holidays period it might take some time.  
That said you're welcome to make a PR, I can merge and release from my phone 😄

**Comment by GerkinDev** [comment]
Here you are sir! See #1035. I did what I could to test this. I didn't added test for #749 though.

**Comment by just-jeb** [comment]
Thank you for your contribution, could we please confirm that the issue is solved for you in `12.1.2-beta.0`?

**Comment by GerkinDev** [comment]
I installed it like 5 mins after your release, dev server works like a charm. I didn't tested in prod env nor SSR yet, but I'm pretty confident

**Comment by just-jeb** [comment]
Cool then, I'm graduating to stable release. Thanks for your insights that allowed to pinpoint the root cause quickly and of course for your contribution!
@all-contributors please add @GerkinDev for code.

**Comment by GerkinDev** [comment]
You're very welcome. Hopefully this might close some open issues as well, so maybe you can ask a status update on some with latest
