### ISSUE TITLE
@angular-builder/jest@12.1.1 throw error with no-cache option

### ISSUE THREAD

**Issue by gillerr** [just-jeb/angular-builders#1032]
## Describe the Bug

With `@angular-builder/jest@12.1.1` tests run with `ng test`  with  the `no-cache` option leads to the following error:

```
Schema validation failed with the following errors:
    Data path "/no-cache" must be array.
```

It works fine with  `@angular-builder/jest@12.1.0`

## Minimal Reproduction

`ng new no-cache`
`cd no-cache`
`npm i @angular-builders/jest jest`

edit `angular.json`, replace `test` block with 

```
"test": {
    "builder": "@angular-builders/jest:run",
    "options": {
        "no-cache": true
    }
 }
```

`ng test`  triggers the problem

A minimal repo this the above steps is available at
https://github.com/gillerr/no-cache

## Expected Behavior

Tests can be run with `no-cache` option.

## Environment

Libs
- @angular/core version: 12.2.23
- @angular-devkit/build-angular version: 12.2.3
- @angular-builders/jest version: 12.1.1

For Tooling issues:
- Node version: 14.16.1
- NPM version: 6.14.12
- Platform:  Linux

**Comment by just-jeb** [comment]
Right, Jest's transition from `camelCase` to `kebab-case` is yet to be handled here. If you use `noCache` it will work.  

I believe the right solution would be to transition the builder options schema to `kebab-case` in v13 (as a breaking change), although there are a few other options (like supporting both `camelCase` and `kebab-case` and transforming it internally etc.).

**Comment by gillerr** [comment]
Hi

I just tested the repo with  `noCache`  instead of `no-cache` and it doesn't solve the problem, the same error arises.

As every other options in `angular.json` are camelCase, I think you should only support camelCase as well

**Comment by just-jeb** [comment]
Ok, now I got it. Using `["cache": false`](https://jestjs.io/docs/25.x/cli#--cache) should solve you the problem. 
The thing is I'm taking all the options right from [`jest-cli`](https://github.com/facebook/jest/blob/master/packages/jest-cli/src/cli/args.ts#L92) repo and `no-cache` isn't there. But I definitely need to add `no-cache` to the schema, since it's clearly supported in the CLI.   

Regarding supporting `camelCase` - I'm not sure I should align with other options in `angular.json`, better to be aligned with Jest on this matter and they are going to deprecate the usage of `camelCase` soon.

**Comment by gillerr** [comment]
Ok, I did check the changes between version 12.0.1 and 12.0.0 and I think I pinpointed the problem: https://github.com/just-jeb/angular-builders/commit/11cd5d061ce416bb813c312140bc203b75d9b90c#diff-ea1e594dbdc5b0b85a6719ab645854149b069cc86cd34d247b03c8fb5b456b29
This commit did change the schema by adding `additionalProperties`  as an array. So my guess is that before this commit `no-cache` was simply ignored by the schema and since it is a valid property, everything worked. After the commit, the `no-cache` falls into the `additionalProperties` catchAll and triggers an error since it is not defined as an array. This is consistent with the error message I got.

I think this commit is a breaking change but only because, weirdly enough, the jest schema doesn't list all possible options.
I see 3 solutions, depending on how you classify the problem:
* it's a bug in your lib: remove the `additionalProperties` and maybe add it back in v13 or support it in your schema if possible
* it's a bug in jest-cli: file a bug on jest-cli so that `no-cache` is integrated in the schema
* `no-cache` is not regular option and should never have been used: adapt the readme (https://github.com/just-jeb/angular-builders/blob/master/packages/jest/README.md) to show an example with `cache` instead of `no-cache`

**Comment by gillerr** [comment]
Regarding `camelCase` vs `kebab-case`, you're right, you should stick to jest's convention.

**Comment by just-jeb** [comment]
The change of `additionalProperties` is itself a bug fix (to allow passing file paths to the CLI), so reverting it is not possible.  
A quick bug fix would be just adding the `no-cache` to the builder schema.  
I'd prefer to do it in v13 along with other `camelCase` to `kebab-case` changes, but you've rightfully pointed out that the docs are not in line with the builder, so I'll add it now.

**Comment by just-jeb** [comment]
Fixed in `12.1.2-beta.1`. Waiting for your confirmation to graduate.

**Comment by gillerr** [comment]
I just tested the `12.1.2.beta.1` version and  it actually solves the problem.

Thank you

**Comment by just-jeb** [comment]
Graduated to stable release
