### ISSUE TITLE
v12.1.2 breaks SSR compilation with multiple tsconfigs.

### ISSUE THREAD

**Issue by quinnjr** [just-jeb/angular-builders#1037]
## Describe the Bug

On `v12.1.2`, my SSR application fails to build when running `npm run dev:ssr` with the error: 
`Called with multiple tsconfigs.`

The error is not present in `v12.1.1` and the application compiles as expected.

I've tested downgrading from `v12.1.2` to `v12.1.1` on two projects and can confirm the issue is present in both projects.

The error seems to be thrown from [here](https://github.com/just-jeb/angular-builders/blob/359a4c4c6200bbe522516c9c7eda30614b2ede3c/packages/custom-webpack/src/utils.ts#L6)

## Minimal Reproduction

1) Install `v12.1.2` in a project using `@angular-builders/custom-webpack:server` to compile the server and `@angular-builders/custom-webpack:browser` for the browser application.
2) Attempt to build the project and receive the error above.
3) Downgrade to `v12.1.1`.
4) Attempt to build the project (which should succeed)

## Expected Behavior

The Angular application should compile both the frontend and server portions of the project correctly without errors.

## Screenshots

![Screenshot](https://i.imgur.com/FmPEiTZ.png)

## Environment

<pre><code>
Libs
- @angular/core version: ^12.2.6
- @angular-devkit/build-angular version: ^12.2.6
- @angular-builders/custom-webpack: 12.1.2

For Tooling issues:
- Node version: v14.15.4
- Platform: Linux

Others:
- PNPM version: 6.13.0
</code></pre>

**Comment by just-jeb** [comment]
Hey @quinnjr, thanks for reporting this. Most certainly it was caused by [this](https://github.com/just-jeb/angular-builders/pull/1035) change, but in order to be able to figure out the problem I'm gonna need a minimal reproduction repo. 
Care to share one? Thanks!

**Comment by exequiel09** [comment]
Can confirm this is happening. I was using `@nguniversal/builders:ssr-dev-server` alongside with `@angular-builders/custom-webpack:server` and throws that error about multiple TSConfigs.

**Comment by exequiel09** [comment]
@just-jeb here's the minimal reproduction repo for you: https://github.com/exequiel09/angular-builders/tree/multiple-tsconfigs-error/packages/custom-webpack/examples/full-cycle-app

Run the following command for the `full-cycle-app` example app.:
1. Install deps - `yarn`
2. Start the SSR dev server - `yarn dev:ssr`

Output when running:
![Screen Shot 2021-09-29 at 5 57 44 PM](https://user-images.githubusercontent.com/1289472/135247045-6cda88a4-f47b-4d73-bf79-33c717ad8183.png)

P.S. Make sure you're on the `multiple-tsconfigs-error` branch.

**Comment by just-jeb** [comment]
Should be fixed in `12.1.3-beta.1`. Could you please verify?

**Comment by exequiel09** [comment]
I'll try this tomorrow. It's already night in my timezone 😅 Will comment
out an update tomorrow morning 🙏🏻

**Comment by exequiel09** [comment]
Hey @just-jeb! Works like a charm! 🥳

**Comment by just-jeb** [comment]
Cool then, I'm graduating it. Thanks!

**Comment by quinnjr** [comment]
Sorry for the late reply, but confirming that v12.1.3 also fixes the issue for me.
