### ISSUE TITLE
@angular-builders/custom-webpack:server don't allow to disable optimizations.styles.inlineCritical

### ISSUE THREAD

**Issue by DzmVasileusky** [just-jeb/angular-builders#1040]
## Describe the Bug

Angular 12 has new schema for the optimizations config. This allows to disable new critical css optimization like that:
```
"optimization": {
  "scripts": true,
  "styles": {
    "minify": true,
    "inlineCritical": false
  },
  "fonts": true
}
```

But I get an error:
```
Property 'optimization' does not match the schema.
{
  "description": "Enables optimization of the build output. Including minification of scripts and styles, tree-shaking and dead-code elimination. For more information, see https://angular.io/guide/workspace-config#optimization-configuration.",
  "x-user-analytics": 16,
  "default": true,
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "scripts": {
          "type": "boolean",
          "description": "Enables optimization of the scripts output.",
          "default": true
        },
        "styles": {
          "type": "boolean",
          "description": "Enables optimization of the styles output.",
          "default": true
        }
      },
      "additionalProperties": false
    },
    {
      "type": "boolean"
    }
  ]
}'
```

## Expected Behavior

New angular config schema is supported for by server builder.

## Environment

<pre><code>
Angular CLI: 12.2.5
Node: 12.16.1
Package Manager: npm 7.6.3
OS: darwin x64

Angular: 12.2.5
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.5
@angular-devkit/build-angular   12.2.5
@angular-devkit/core            12.2.5
@angular-devkit/schematics      12.2.5
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             12.2.5
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.51.1
</code></pre>

## Additional Context

This schema is allowed for @angular-builders/custom-webpack:browser

**Comment by just-jeb** [comment]
According to Angular CLI [source code](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/builders/server/schema.json#L37) the `server` builder does not support this optimization.

**Comment by DzmVasileusky** [comment]
You are right it's still not supported by Angular.

But we have found a workaround if anyone will get the same problem:
```
server.get('*', (req, res) => {
  ...
  res.render('index', {
        ...
        inlineCriticalCss: false,
        ...
        req

    });
});
```
