### ISSUE TITLE
Build error: require() of ES modules is not supported error using Angular 13

### ISSUE THREAD

**Issue by jponeill** [just-jeb/angular-builders#1043]
## Describe the Bug

Get build error: require() of ES modules is not supported error using Angular 13 (prerelease). 

See issue https://github.com/angular/angular/issues/43833

## Minimal Reproduction

npm i -g @angular/cli@13.0.0-next.9

1 ng new graphql
2. npm i @angular-builders/custom-webpack --save-dev
3. npm i @graphql-tools/webpack-loader
4. Change angular.json line to "builder": "@angular-builders/custom-webpack:browser"
5. Create extra-webpack.config.js in project root directory
module.exports = {
module: {
rules: [
{
test: /.(graphql|gql)$/,
exclude: /node_modules/,
loader: '@graphql-tools/webpack-loader'
}
]
}
}

... run ng build and get error: "An unhandled exception occurred: Must use import to load ES Module"

!-- Please create and share minimal reproduction -->

## Expected Behavior

Successful build. 

## Environment

<pre><code>
Angular CLI: 13.0.0-next.9
Node: 14.18.1
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 13.0.0-rc.0
... animations, common, core, forms, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.10
@angular-devkit/build-angular   13.0.0-next.9
@angular-devkit/core            12.2.10
@angular-devkit/schematics      13.0.0-next.9
@angular/cli                    13.0.0-next.9
@angular/compiler               13.0.0-next.15
@angular/compiler-cli           13.0.0-next.15
@schematics/angular             13.0.0-next.9
rxjs                            7.4.0
typescript                      4.4.4
</code></pre>

**Comment by nhhockeyplayer** [comment]
PRETTY-SURE ?
