### ISSUE TITLE
Can we move the CLI builder for Bazel here?

### ISSUE THREAD

**Issue by alexeagle** [just-jeb/angular-builders#1047]
Hey there,

We're looking for a new home for a small builder that teaches Angular CLI how to run Bazel. It's very little code - just this directory
https://github.com/bazelbuild/rules_nodejs/tree/stable/packages/angular
with this primary implementation
https://github.com/bazelbuild/rules_nodejs/blob/stable/packages/angular/src/builders/index.ts

For the next release of rules_nodejs we want to trim our scope. @just-jeb what do you think about hosting it in your repo instead?
/cc @alan-agius4

**Comment by just-jeb** [comment]
@alexeagle So the PR has been merged and the `@angular-builders/bazel` package will be available in v13 (it's already available in a preview version).  
Thanks for your contribution!

**Comment by alexeagle** [comment]
Awesome thank you for adopting it!!
