### ISSUE TITLE
Support Angular 13

### ISSUE THREAD

**Issue by DavidDudson** [just-jeb/angular-builders#1049]
**Is your feature request related to a problem? Please describe.**

Due to this plugin depending on an old `@angular` version, it fails to work with angular 13. I believe this is due to a typescript version change. causing the legacy `@ngtools/webpack` plugin to no longer work

```
/webpack/src/ivy/plugin.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from ../package.json
```

**Describe the solution you'd like**

A new major version of `@angular-builders/jest` and `@angular-builders/custom-webpack` both supporting angular 13

**Additional context**
There is a workaround. Adding:

```
  "resolutions": {
    "@angular/compiler": "13.0.0",
    "@angular/cli": "13.0.0",
    "@angular-devkit/build-angular": "~13.0.0"
    }
```

to package json and this works fine.

**Comment by abadakhshan** [comment]
@DavidDudson 

You could find a solution here #1050

**Comment by DavidDudson** [comment]
`angular-builders-jest` is also a dep of ours, they just released a prerelease version which seems to work perfectly for us!

Thanks for the quick PR <3

**Comment by just-jeb** [comment]
You're welcome to check out the preview version `13.0.0-beta.0` (under the `next` tag).

**Comment by gabynevada** [comment]
@just-jeb I get the following error when trying ng build using the beta
```
Error: Cannot find module 'webpack-sources'
```

After installing webpack-sources package everything works as expected, including the new angular cache.

Thanks!

**Comment by just-jeb** [comment]
@gabynevada Hey, I suspect it's a broken lock file. Try to remove it and regenerate again (remove the `webpack-sources` from direct dependencies before regeneration).

**Comment by DavidDudson** [comment]
@just-jeb that beta version works perfectly. I think this is close to record timing that all our dependencies have been working (even if they are still all pre-release) after an angular upgrade, thank you very much! It means we can thoroughly test our applications while waiting for full releases.

**Comment by gabynevada** [comment]
@just-jeb Perfect! That was the issue.

Thanks! All working great

**Comment by just-jeb** [comment]
@DavidDudson doing my best 😄 The stable release won't take long, I'm working on integrating a [new builder](https://github.com/just-jeb/angular-builders/pull/1048), then a few minor doc updates and we're good to go.   
Unless you discover any issues of course.
