### ISSUE TITLE
Resources written in a custom Webpack configuration plugin in build dir are deleted

### ISSUE THREAD

**Issue by PhiLhoSoft** [just-jeb/angular-builders#1052]
## Describe the Bug

We have an Angular 11 application, using a custom i18n system, and scripts run from a custom Webpack configuration plugin to create, at build time, the i18n files (Json and JS files) served to the application.

In other words, when we run `ng build`, we leverage `@angular-builders/custom-webpack` to run a plugin than reads and processes i18n files in the source and generates a i18n folder with .js and .json files in a `<build dir>/<app name>/i18n` directory (from `outputPath`).

So far, so good, it worked well.

I upgraded the application to Angular 12, and discovered that `<build dir>/<app name>/i18n` folder disappears, only to find the generated application and the assets copied from `angular.json`.

Is there a way to avoid erasing files existing in the `outputPath`, or perhaps delaying the generation of the files after this reset?

## Minimal Reproduction

I generated a standard Angular 12 application with `ng generate`, then customized it a bit as follows:

- package.json: just added a `"@angular-builders/custom-webpack": "~12.1.3",` line to the devDependencies.
- angular.json: replaced the `"builder": "@angular-devkit/build-angular:browser",` line with `"builder": "@angular-builders/custom-webpack:browser",` and added `"customWebpackConfig": { "path": "./extra-webpack-config.js" },` to the `options`.
- extra-webpack-config.js as follows:

```
const globby = require('globby');
const fs = require('fs-extra');

class I18nPlugin {
	constructor(version) {
		this.version = version;

		this.apply = (compiler) => {
			if (compiler.options.devServer && compiler.options.devServer.host) {
				return;
			}
			const outputRoot = compiler.options.output.path;
			fs.mkdirpSync(`${outputRoot}/i18n`);
			const result = version.split('').reduce((res, character, index) => {
				console.log(`Processing "${character}" out of "${version}"`);
				fs.writeJsonSync(`${outputRoot}/i18n/${index}.json`, { character }, 'UTF-8');

				fs.writeFileSync(`${outputRoot}/i18n/${index}.txt`, `${version}: ${character} (${index})`, 'UTF-8');

				return res;
			}, true);

			if (!result) {
				throw new Error('Could not process i18n files');
			}
		};
	}
}

const version = require('./package.json').version;

module.exports = {
	plugins: [
		new I18nPlugin(version),
	],
};
```
Silly code, gross simplification of our real code, but doing the job for reproduction purpose.

## Expected Behavior

Generated `dist/application-name/i18n` with some .json and .txt files, and in `dist/application-name`, files like:
styles.31d6cfe0d16ae931b73c.css
3rdpartylicenses.txt
favicon.ico
index.html
main.87de95552a39e6aec818.js
polyfills.ea0318623030e48f2534.js
runtime.adc971993013d7f0b1ee.js

With Angular 12, I have these files, but the `i18n` folder, which we can see generated during the first part of build process, has disappeared.

## Environment

<pre><code>
Libs
- @angular/core version: "~12.2.0" (also 12.2.13 in real app)
- @angular-devkit/build-angular version: "~12.2.11" (also 12.2.13)
- @angular-builders/custom-webpack version: "~12.1.3"

For Tooling issues:
- Node version: v14.16.0
- Platform:  Windows 10

</code></pre>

## Possible workaround

Perhaps generate the files in a separate directory, ignored by Git, and copy them as assets.
But I find this rather ugly (and inefficient), as it generates yet another build-time artifact to clean up.

**Comment by just-jeb** [comment]
I believe the problem is not with Angular Builders and even not with Angular CLI.  
In version 12 they've started using Webpack 5 by default, so you might want to match your plugin to [Webpack Plugins API](https://webpack.js.org/contribute/writing-a-plugin/).

**Comment by PhiLhoSoft** [comment]
Thank you for the information. The example given at the page you list is exactly what I was looking for.
I adapted a bit this example to my dummy use case to get a taste of the changes to do, it works.
For reference, here is the new version of the code:
```
// https://webpack.js.org/contribute/writing-a-plugin/
class I18nPlugin {
	constructor(version) {
		this.version = version;
	}

	apply(compiler) {
		const pluginName = I18nPlugin.name;

		const ilogger = compiler.getInfrastructureLogger(pluginName);
		ilogger.info('Processing i18n files');

		// webpack module instance can be accessed from the compiler object,
		// this ensures that correct version of the module is used
		// (do not require/import the webpack or any symbols from it directly).
		const { webpack } = compiler;

		// Compilation object gives us reference to some useful constants.
		const { Compilation } = webpack;

		// RawSource is one of the "sources" classes that should be used
		// to represent asset sources in compilation.
		const { RawSource } = webpack.sources;

		// Tapping to the "thisCompilation" hook in order to further tap
		// to the compilation process on an earlier stage.
		compiler.hooks.thisCompilation.tap(pluginName, (compilation) => {
			const logger = compilation.getLogger(pluginName);

			// Tapping to the assets processing pipeline on a specific stage.
			compilation.hooks.processAssets.tap(
				{
					name: pluginName,

					// Using one of the later asset processing stages to ensure
					// that all assets were already added to the compilation by other plugins.
					stage: Compilation.PROCESS_ASSETS_STAGE_SUMMARIZE,
				},
				(assets) => {
					// "assets" is an object that contains all assets
					// in the compilation, the keys of the object are pathnames of the assets
					// and the values are file sources.

					version.split('').forEach((character, index) => {
						ilogger.info(`Processing "${character}" out of "${version}"`);

						// Adding new asset to the compilation, so it would be automatically
						// generated by the webpack in the output directory.
						compilation.emitAsset(
							`./i18n/${index}.json`,
							new RawSource(`{ ${character} }`),
						);
						compilation.emitAsset(
							`./i18n/${index}.txt`,
							new RawSource(`${version}: « ${character} » (${index})`), // Special chars to ensure it is UTF-8
						);
					});
				}
			);
		});
	}
}

const version = require('./package.json').version;

module.exports = {
	stats: {
		logging: 'log', // Doesn't seem to work? Neither that nor `true`. Had to use logger.info.
	},
	plugins: [
		new I18nPlugin(version),
	],
};
```
