### ISSUE TITLE
jest package depends on old rc version preset for angular

### ISSUE THREAD

**Issue by icorne** [just-jeb/angular-builders#1064]
jest package depends on old rc version preset for angular, rc-1 and it does not work for my project.
Updating to the released version does work. I've created a PR to fix this

**Comment by just-jeb** [comment]
Should be fixed in `13.0.1-beta.0`, please confirm.

**Comment by icorne** [comment]
» npm install @angular-builders/jest@13.0.1-beta.0
npm ERR! code ETARGET

Can't seem to install?

**Comment by icorne** [comment]
Is it published yet? I can't find it

**Comment by just-jeb** [comment]
Cool, graduating
