### ISSUE TITLE
Cannot set public path

### ISSUE THREAD

**Issue by SebastianStehle** [just-jeb/angular-builders#1070]
## Describe the Bug

It is kind of weird, but I cannot override the publicPath with Angular 13. I am migrating from a custom webpack config to angular CLI and have to make a few changes.

One of them is to override public path. Most settings work but not this one. It seems that angular overrides it after the path is set. Because the deprecated setting `--deploy-url ./build/` works.

## Minimal Reproduction

Override publicPath

```
module.exports = (config) => {
    config.output.publicPath = './build/';

    return config;
};
```

## Environment

<pre><code>
Libs
- @angular/core version: 13.1.2
- @angular-devkit/build-angular version: 13.1.2
- @angular-builders/custom-webpack version: 13.0.0

For Tooling issues:
- Node version: XX v16.13.1
- Platform:  Windows

**Comment by just-jeb** [comment]
The reason it doesn't work is that `index.html` is no longer generated by Webpack. It is generated after the Webpack build by Angular CLI itself. 
As the official docs suggest, you should 

> Use "baseHref" option, "APP_BASE_HREF" DI token or a combination of both instead

**Comment by SebastianStehle** [comment]
Thank you very much. There is an issue in the angular CLI repo to revert the decision about making deployUrl deprecated because not everything can be solved with that.

**Comment by just-jeb** [comment]
Well, the only thing I can recommend you is maybe take a look at [indexTransform](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#index-transform). Otherwise, unfortunately, there isn't much I can do about it.
