### ISSUE TITLE
Incorrect path resolution on windows

### ISSUE THREAD

**Issue by phl3x0r** [just-jeb/angular-builders#1144]
## Describe the Bug

The path property for customWebpackConfig is not resolved correctly on windows machines.

## Expected Behavior

No errors

## angular.json
<pre><code>
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js"
            },
            ....
</code></pre>

## Error
<pre><code>
'Q:\Workspace\my-project\apps\web-app/./custom-webpack.config.js'
</code></pre>

## Output
<pre><code>
⠋ Generating browser application bundles (phase: setup)...An unhandled exception occurred: Cannot find module 'Q:\Workspace\my-project\apps\web-app/./custom-webpack.config.js'
Require stack:
.....
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: my-project@0.0.0
npm ERR!   at location: Q:\Workspace\my-project\apps\web-app
</code></pre>

## Environment

<pre><code>
Libs
- @angular/core version: 13.1.3
- @angular-devkit/build-angular version: 13.1.4
-  angular-builders/custom-webpack varsion 13.1.0
For Tooling issues:
- Node version: 16.13.0
- Platform:  Windows

</code></pre>

**Comment by just-jeb** [comment]
Please create a repo with minimal reproduction.

**Comment by phl3x0r** [comment]
> "builder": "@angular-builders/custom-webpack:browser",
>           "options": {
>             "customWebpackConfig": {
>               "path": "./custom-webpack.config.js"
>             }

Here you go: https://github.com/phl3x0r/custom-webpack-minimal

**Comment by phl3x0r** [comment]
You are right, how embarrassing.
The issue was that I was running the build command from the root directory of a npm workspace, e.g `npm start -w apps/my-app` however the path is relative to the current directory, not the app directory containing the angular.json, as I was expecting.

Appending the app path (or moving the webpack config to the workspace root) solved the problem.

**Comment by phl3x0r** [comment]
Closing this. Might be a good idea to make the path relative to angular.json to avoid potential problems with CI pipelines, but this is a minor issue and can be easily mitigated.
