### ISSUE TITLE
Selecting HTMLElements byRole returns null

### ISSUE THREAD

**Issue by andreashouben** [just-jeb/angular-builders#1187]
## Describe the Bug

In our projects we use `angular-builders/jest` to run our tests. We use `[ngneat/spectator](https://github.com/ngneat/spectator/) to create our components in the test environment.

spectator implements the dom selectors from `@testing-library/dom-testing-library`. Those work so far, only the `byRole` selector always returns null.

At first I suspected a bug in spectator, that's why I filed a bug [there](https://github.com/ngneat/spectator/issues/538). 

Turns out, it works if you set the option `{hidden:true}` in the selector. Apparently `angular-builders/jest` renders components in a way that they are inaccessible to the selector.

## Minimal Reproduction

Please take a look at the issue I filed with spectator: https://github.com/ngneat/spectator/issues/538

There is a detailed description of the behavior, as well as a link to a repository that can be used to reproduce the bug.

## Expected Behavior

I expect queries like `byRole('button')` to return an element from the rendered DOM.

## Screenshots

-

## Environment

<pre><code>
Libs
- @angular/core version: 13.2.0
- @angular-devkit/build-angular version: 13.2.4
- @angular-builders/jest version: 13.0.3

For Tooling issues:
- Node version: 16
- Platform:  Mac, Windows

Others:
Nothing special

## Additional Context

-

**Comment by andreashouben** [comment]
Hm. But when I use `jest-preset-angular` it works. Why would I file an issue there?

**Comment by andreashouben** [comment]
However, your comment brought me to a possible solution in giving me a bit of understanding of how `@angular-builders/jest` works. I took a look at the globals and noticed [`computed-style`](https://github.com/just-jeb/angular-builders/blob/master/packages/jest/src/global-mocks/computed-style.ts
), which returns `display: 'none'` for the window object. That explains why the byRole query doesn't find the elements.
If I disable this global setting, it works.
Can you elaborate on why you set that global?

**Comment by just-jeb** [comment]
No particular reason actually. Usually you use this mock just to make the code not crash when accessing `getComputedStyle` but I'm open for suggestions about its default value.
