### ISSUE TITLE
Html template file can't be resolved in webpack plugins when using custom-webpack builder

### ISSUE THREAD

**Issue by andy-maca** [just-jeb/angular-builders#1201]
## Describe the Bug
We used to build a mobile web app by replacing specific html template file for some components with `NormalModuleReplacementPlugin`, e.g, we replace `abc.component.html` to `abc.mobile.component.html` when building the abc component. It works in ng11, but after upgrade to ng13, I found all webpack plugins I tested can't see any html file resource. Seems the ng compiler filtered out all html resource files.

## Minimal Reproduction

I created two dummy projects with both angular 11(https://github.com/andy-maca/ng11-app) and angular 13(https://github.com/andy-maca/ng13-app)
Just run `ng build` to see the difference in output, you will find the html file can be seen in `ng11-app`, but not in `ng13-app`.

## Expected Behavior

Html template resource should be available in webpack plugin when using custom webpack  builder. 

## Screenshots

![image](https://user-images.githubusercontent.com/1320635/165902251-ecdf70d8-0eb5-4e37-be71-9b7b13e61b74.png)
![image](https://user-images.githubusercontent.com/1320635/165902443-ffb7949c-1e47-47e7-b5a5-2b1009ff09fa.png)

## Environment

<pre><code>
Libs for Angular 13 project
- @angular/core version: 13.3.0
- @angular-devkit/build-angular version: 13.3.4
- @angular-builders/custom-webpack version: 13.1.0

Libs for Angular 11 project
- @angular/core version: 11.1.1
- @angular-devkit/build-angular version: 11.1.1
- @angular-builders/custom-webpack version: 11.1.1

If this issue can't be fix in angular 13, is there other way to replace template file during compiling.

**Comment by just-jeb** [comment]
Hey @andy-maca, thanks for reporting the issue.  
It doesn't look like a bug with Custom Webpack builder, most probably Angular changed the way it works with the template files and hence it stopped working. It requires deeper investigation (it's great that you have repro!) so it might take some time.  
Meanwhile I'd suggest you look at [this](https://github.com/just-jeb/angular-builders/issues/616#issuecomment-554356151) comment and see if it can give you a different direction (maybe use custom loader instead of plugin or something).  

LMK if you have any news 🙏🏿

**Comment by andy-maca** [comment]
I tried to add the following configuration in webpack config file, then I got a lot of compilation error of the template.
`
 const index = angularConfig.plugins.findIndex(p => p instanceof AngularWebpackPlugin.AngularWebpackPlugin);
  if(index>=0) {
    const oldOptions = angularConfig.plugins[index].pluginOptions;
    oldOptions.directTemplateLoading = false;
    angularConfig.plugins.splice(index,1,new AngularWebpackPlugin.AngularWebpackPlugin(oldOptions));
  }
  
  angularConfig.module.rules.push({
    test: /\.html$/i,
    use: [
      { loader: 'raw-loader' }
    ]
  });
`

**Comment by andy-maca** [comment]
It turns out only set the `directTemplateLoading ` to false is enough, no need to use the `raw-loader`. 

    const angularWebpackPlugin = angularConfig.plugins.find(p => p instanceof AngularWebpackPlugin.AngularWebpackPlugin);
    if(angularWebpackPlugin) {
      angularWebpackPlugin.pluginOptions.directTemplateLoading = false;
    }

Now I can use `NormalModuleReplacementPlugin` for html template again, one little difference is the request path for each html file has a suffix "?ngResource", a working code for it is:

       new webpack.NormalModuleReplacementPlugin(
        /(.+)\.component\.html/,
        function (result) {

          let fileUrl = result.request;
          const urls = result.request.split("?");
          if (urls.length > 1) {
            fileUrl = urls[0];
          }
          const fileName = path.basename(fileUrl);

          if (replaceFiles.includes(fileName)) {
            result.request = result.request.replace(
              ".component.",
              ".mobile.component."
            );
            if (result.resource) {
              result.resource = result.request;
            }
          }
        }
      )

Thanks @just-jeb
