### ISSUE TITLE
Update `angular-builders/jest` Major dependencies

### ISSUE THREAD

**Issue by just-jeb** [just-jeb/angular-builders#1205]
A new version of `jest-preset-angular` is out (`v12.0.0`) and it includes a lot of breaking changes, including dropping `Node 12` support and supporting `Jest 28`.  
All these changes might greatly affect the users, so they should be introduced as part of a major v14 release. 
The major release should include the following updates: 
 - `jest-preset-angular@12`
 - `Angular@14`
 - `Jest@28`

**Comment by henryruhs** [comment]
It would be nice to have a beta release - there are libraries that properly depend on this and should have the chance to test against Angular 14 release candidates to have support from day one for the final 14 release.
