### ISSUE TITLE
@angular-builders/custom-webpack - auto update package dependencies

### ISSUE THREAD

**Issue by hadrien-f** [just-jeb/angular-builders#1214]
**Is your feature request related to a problem? Please describe.**
Packages does not follow angular development rythm. It is unfortunate since we miss angular small updates containing small features and fixes.

We get conflicting peer dependency when we try to update :
`
npm ERR! Found: @angular-devkit/build-angular@13.2.4
npm ERR! node_modules/@angular-devkit/build-angular
npm ERR!   dev @angular-devkit/build-angular@"^13.3.5" from the root project
npm ERR!   @angular-devkit/build-angular@"^13.0.0" from @angular-builders/custom-webpack@13.1.0
`

**Describe the solution you'd like**
I see the repository has a bot to auto update some projets. It would be very nice to have the bot publish new version when all test pass ?

**Describe alternatives you've considered**
I either wait for a new custom-webpack version but I guess we could ignore the npm install error if project works ?

**Additional context**
Thanks for the package it helps a lot :)

**Comment by just-jeb** [comment]
Sounds like an issue with your `lock` file. All the builders have a pretty loose constraint on the Angular Devkit versions (for example [here](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/package.json#L43)). As you can see it's `^13.0.0` which literally means `Anything that matches 13.x.x`.  
The package manager (such as `npm` or `yarn`) should dedupe these dependencies. 
Maybe try to regenerate the lock file?

**Comment by hadrien-f** [comment]
Indeed you are right, the issue was with the lockfile.

Sorry for the support, I'm closing the issue.

Have a nice day :)
