### ISSUE TITLE
Preset jest-preset-angular not found

### ISSUE THREAD

**Issue by lemesh2424** [just-jeb/angular-builders#1228]
Hi all,

Have validation error with text same as title - "Preset jest-preset-angular not found". Tests running with "ng test" command

<img width="1437" alt="Снимок экрана 2022-06-29 в 18 00 27" src="https://user-images.githubusercontent.com/35412885/176469502-c8f32131-c5f2-467c-a7c3-461b9e9d3b70.png">

Dependencies version:
"@angular-builders/jest": "^13.0.4",
"@angular-devkit/build-angular": "^13.3.3",
"@angular-eslint/builder": "13.2.1",
"@angular/cli": "~13.3.3",
"@angular/compiler-cli": "~13.3.3",
"@briebug/jest-schematic": "^4.0.0",
"jest": "^27.5.1"

_jest.config.js_

<img width="966" alt="Снимок экрана 2022-06-29 в 18 05 50" src="https://user-images.githubusercontent.com/35412885/176470648-755a77d8-c3ce-4a33-a4ef-7a641913d850.png">

_setup.jest.ts_

<img width="966" alt="Снимок экрана 2022-06-29 в 18 06 09" src="https://user-images.githubusercontent.com/35412885/176470720-7d05083f-43f2-4da2-8f89-b5868be651c2.png">

**Comment by lemesh2424** [comment]
_angular.json_

<img width="966" alt="Снимок экрана 2022-06-29 в 18 40 23" src="https://user-images.githubusercontent.com/35412885/176478313-9ca57678-e205-4ccd-9f89-66aa8df33d2e.png">

**Comment by just-jeb** [comment]
Looks like some dependency hell stuff. Probably multiple versions of `jest-preset-angular`. Try to set `resolutions` and see if it helps.

**Comment by lemesh2424** [comment]
@just-jeb have no multiple versions

<img width="966" alt="Снимок экрана 2022-06-30 в 00 59 40" src="https://user-images.githubusercontent.com/35412885/176552725-9e593c7d-f009-4d87-9f39-0efe4a0b1845.png">

**Comment by just-jeb** [comment]
Yup, the preset should be at the root `node_modules`, there is no reason for it to be under `jest` builder, unless you have some conflicts. 

What happens here essentially is that you specify `jest-preset-angular` in the config and it tries to find it in the root `node_modules` but it's not there. You can of course give the full pass to the preset (under `@angular-builders/jest/node_modules`) but this is very fragile. Instead I'd suggest you to understand why it is being installed under `@angular-builders/jest`. 

Might be `peerDependencies`, might be `dependencies`, probably something that `jest-preset-angular` depends on and you have another version of it.  

I had this issue a while back and it was multiple `typescript` versions. You'll have to figure it out 🤷🏿 

Btw, you don't have to specify the whole configuration, the builder does that for you. Just add what's needed (in your case I guess it's `moduleNameMapper`), the builder takes care of the rest. Same goes for global mocks etc.

**Comment by lemesh2424** [comment]
@just-jeb Yes, I installed it to the global level with `node_modules` deletion and it's worked. Thank you so much :)
