### ISSUE TITLE
@angular-builders/jest: Unknown arguments: testNamePattern, testPathPattern, updateSnapshot in v14

### ISSUE THREAD

**Issue by enolive** [just-jeb/angular-builders#1237]
## Describe the Bug

While trying out the latest 14.0.0 version, I noticed that the parameters above aren't passed to jest anymore. This renders this package practically unusable while using JetBrains IDEs (such as IntelliJ, WebStorm) since this is the way they pass their arguments to the Jest runner when trying to run individual tests or update the snapshots.

I double-checked if this problem is related to Jest 28.x, but it accepts all mentioned arguments

## Minimal Reproduction

Install v14 and try to run 

`ng test --testPathPattern=app.component.spec.ts --testNamePattern=AppComponent --updateSnapshot`

in contrast the following command works: 

`ng test --test-path-pattern=app.component.spec.ts --test-name-pattern=AppComponent --update-sapshot`

I also uploaded my test project to Github:

https://github.com/enolive/learning/tree/master/angular/chart-mock

## Expected Behavior

The Parameters should be passed to the Jest CLI

## Screenshots

![image](https://user-images.githubusercontent.com/20992515/180311057-2ccfa74b-f544-4606-b7b5-4cf93c32c32b.png)

## Environment

<pre><code>
Libs
- @angular/core version: 14.1.0
- @angular-devkit/build-angular version: 14.1.0
- @angular-builders/jest version: 14.0.0

For Tooling issues:
- Node version: 16.6  
- Platform:  Linux 

Others:

WebStorm 2022.2.4
</code></pre>

**Comment by enolive** [comment]
update: it seems that other parameters written in camelCase style (such as --watchAll or --listTests) also won't work. The dashed-args style however does. If I understand the [Jest documentation](https://jestjs.io/docs/cli#camelcase--dashed-args-support) correctly, both styles should work

**Comment by just-jeb** [comment]
This is why we have the migration guide: https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#jest-builder

This is a limitation of Angukar CLI, nothing to do with Jest.
