### ISSUE TITLE
After Angular V13 upgrade to Angular V14 the compilation fails.

### ISSUE THREAD

**Issue by polhek** [just-jeb/angular-builders#1239]
## Describe the Bug

I have updated my Angular v13 app to Angular v14. When updating the NPM packages I didn't get any errors. I have also updated the `"@angular-builders/custom-webpack": "^14.0.0"`. When running `ng serve` I get errors, which were not present before.

## Minimal Reproduction

I am sorry, but I cannot share the app minimal reproduction. 

## Expected Behavior

The compilations of the Angular app should finish as expected.

## Screenshots

![test](https://user-images.githubusercontent.com/32010556/180784073-ef3180b0-97e4-4f39-b3a6-01f6e70d2eb3.png)

![image](https://user-images.githubusercontent.com/32010556/180784959-02ebefa9-169a-4647-b10b-f96be0470efe.png)

I get the following errors when compiling my Angular app.  Before updating to v14 and updating to `"@angular-builders/custom-webpack": "^14.0.0"`` it worked flawlessly.

## Environment

<pre><code>
Libs
-  "@angular/core": "^14.1.0",
- "@angular-devkit/build-angular": "^14.1.0",
- `"@angular-builders/custom-webpack": "^14.0.0"``.

For Tooling issues:
- Node version: 16.16.0
- Platform:  Windows

**Comment by just-jeb** [comment]
Please try regenerating `package-lock.json` (remove and run `npm install`).

**Comment by polhek** [comment]
I have tried all this things, and have also found the solution. The .style.css file that you get errors for, you need to add to angular.json styles. And then the app compiles normally. Don't know why this wasn't the problem in angular 13, but has become a problem in version 14.

**Comment by YES-Lee** [comment]
I have the same problem.

**Comment by polhek** [comment]
Try adding the files that the compiler tells you about to angular.json. This solved my problem. Maybe there is even better workaround.

**Comment by arturovt** [comment]
@polhek are you able to provide a reproducible example? Unfortunately, its lack makes the issue stale because no one can understand what's happening on your side just by looking at your screenshots.

(note: the reproducible example was required when you were opening an issue: _Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this._)

**Comment by polhek** [comment]
We figured out that with Angular 14  we had to import every .scss of angularJS to angular.json. It wasn't error on the package site.
