### ISSUE TITLE
Cannot run a single test file

### ISSUE THREAD

**Issue by PhiLhoSoft** [just-jeb/angular-builders#1241]
## Describe the Bug

This is about `@angular-builders/jest`

I described the issue in details at https://github.com/angular/angular-cli/issues/23651
While I feel they made changes affecting the described behavior, they sent me here…

In short: since I upgraded to Angular 14, I can't find a good way to run a single test file.
If I just overlooked a way to do it, please show me, I am sure it would be used for other people.

Thanks.

**Comment by just-jeb** [comment]
Migration guide: https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#jest-builder
What about this? `ng test --test-path-pattern=src/lib/my-shared-library.service.spec.ts`

**Comment by PhiLhoSoft** [comment]
Ah, I didn't see this page, I looked at something like that from https://github.com/just-jeb/angular-builders/tree/master/packages/jest, therefore I overlooked it in https://github.com/just-jeb/angular-builders…

Sorry for the noise.
`ng test --test-path-pattern=mention`
just works too.

Thank you.

**Comment by PhiLhoSoft** [comment]
I have some other problems, tell me if I must create new issues (if they are real bugs).
I see "tsConfig - path to tsconfig file. If the path is relative then it is evaluated relative to the project root. Defaults to tsconfig.spec.json that is located in project root." so I didn't added this option, as we use this name.
But since I upgraded to Angular 14, I have this message:
```
$ ng test
Determining test suites to run...
ngcc-jest-processor: running ngcc
Warning: The inferred tsconfig file "C:/_Projets/front/ng-oo-shortcuts/tsconfig.json" appears to be "solution-style" since it contains no root files but does contain project references.
This is probably not wanted, since ngcc is unable to infer settings like "paths" mappings from such a file.
Perhaps you should have explicitly specified one of the referenced projects using the --tsconfig option. For example:

  ngcc ... --tsconfig "./tsconfig.lib.json"
  ngcc ... --tsconfig "./demo_files/tsconfig.json"
  ngcc ... --tsconfig "./tsconfig.spec.json"

Find out more about solution-style tsconfig at https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/#solution-style-tsconfig.
If you did intend to use this file, then you can hide this warning by providing it explicitly:

  ngcc ... --tsconfig "tsconfig.json"
```
Just to be sure, I added the following after the "builder" line in angular.json:
`          "options": { "tsconfig": "tsconfig.spec.json" },`
It complained:
```
Error: Schema validation failed with the following errors:
  Data path "/tsconfig" must be array.
```
So I added instead:
`          "options": { "tsconfig": ["tsconfig.spec.json"] },`
and I had the same message about an inferred tsconfig file.

**Comment by just-jeb** [comment]
Yes, could you please create a separate issue for this? Also, a reproduction repo would be great.
