### ISSUE TITLE
After upgrading from angular 13 to 14 ng build fails

### ISSUE THREAD

**Issue by devHimanshu12** [just-jeb/angular-builders#1242]
## Describe the Bug

when i run ng build --extra-webpack it throws 

This version of CLI is only compatible with Angular versions ^13.0.0 || ^13.3.0-rc.0,
but Angular version 14.1.0 was found instead.

 webpack it required i cannot delete in node modules because we need the extra arguments when doing ng build

## Minimal Reproduction
It is related to only update angular 14 and ng build so i don't think minimal reproduction is required.

## Expected Behavior
app should build and serve locally 

## Screenshots
![issue](https://user-images.githubusercontent.com/89963043/181750640-cb4aaee0-0cbd-4274-94d9-d287c57bcef4.png)

## Environment

<pre><code>
Libs
- @angular/core version: 14.1.0
- @angular-devkit/build-angular version: 14.1.0
- @angular-devkit/architect version:   0.1303.9
- @angular-devkit/build-angular version:  14.1.0
- @angular-devkit/core version: 14.1.0
- @angular-devkit/schematics version: 14.1.0
- @schematics/angular version: 14.1.0

For Tooling issues:
- Node version: 16.15.1
- Platform:  linux x64

Others:

</code></pre>

**Comment by just-jeb** [comment]
I see that your `architect` version is `0.13xx.x`. It should be `0.14xx.x`.

**Comment by devHimanshu12** [comment]
Thank you @just-jeb , issue is resolved.
