### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded at _gloabal.<computed>.get (zone.js:xx)

### ISSUE THREAD

**Issue by devHimanshu12** [just-jeb/angular-builders#1244]
## Describe the Bug
I have updated my angular from version 7 to version 14. step by step.
But now i am getting this maximum call stack size exceeded at _global.<computed>.get(zone.js:xx)
I have tried things like updating zone.js to latest , deleting node modules and npm i and npm ci also.
and check ts file whether there is any recursive function or not, there is no.if i comment polyfills then there is no error. 
Please me in removing this error.

## Expected Behavior
I should run without error.

## Screenshots
![classification-package-json](https://user-images.githubusercontent.com/89963043/183415873-64ef27e4-a3d1-4756-96bb-f5bcd53cc6c5.png)

![classification](https://user-images.githubusercontent.com/89963043/183415884-b2af9490-2441-4765-8c1b-531e40ebc54d.png)

![console-zone-err](https://user-images.githubusercontent.com/89963043/183415897-2c4276e9-f884-4675-8439-c0112489cfed.png)

## Environment

<pre><code>
Libs
- @angular/core version: 14.1.1
- @angular-devkit/build-angular version: 14.1.1
- @angular-devkit/architect version : 14.1.1
- @schematics/angular version: 14.1.1

For Tooling issues:
- Node version: 16.15.1
- Platform:  linux x64

Others:

</code></pre>

**Comment by just-jeb** [comment]
From what I see you're not even using `@angular-builders`. Probably an issue for Angular/Angular CLI repo?

**Comment by arturovt** [comment]
I'm sure this is not related to `angular-builders`. The package isn't doing any code transformations. It has nothing to do with the zone.js package, which throws an error that the getter is called recursively somewhere in your code. That's happening because there's a change between zone.js versions.
