### ISSUE TITLE
errorOnUnknownElements and errorOnUnknownProperties options are not applied

### ISSUE THREAD

**Issue by Yohandah** [just-jeb/angular-builders#1245]
Upgrade jest-preset-angular to 12.2 to allow this

https://github.com/angular/angular/issues/36430
https://github.com/thymikee/jest-preset-angular/issues/1656
https://github.com/thymikee/jest-preset-angular/blob/main/CHANGELOG.md

**Comment by Yohandah** [comment]
After testing the beta.3 that updated jest-preset-angular, the options 

```
testEnvironmentOptions: {
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true,
  },
```

are not taken

**Comment by Yohandah** [comment]
@just-jeb I pushed a repo that reproduce this issue https://github.com/Yohandah/angular-builder-jest-errorOnUnknownElementsr

* Fresh Angular 14 project
* With @angular-builders/jest installed following this guide : https://www.justjeb.com/post/angular-cli-ng-test-with-jest
* Run `ng test`
* Tests are passing with a console.error
* They should've failed as specified here : https://github.com/angular/angular/issues/36430#issuecomment-1117801535 and implemented in jest-preset-angular here : https://github.com/thymikee/jest-preset-angular/issues/1656

**Comment by just-jeb** [comment]
You're not using it right (look closely at the links you provided). 

![image](https://user-images.githubusercontent.com/9823087/186116975-695555f8-8b93-4944-a707-d5c8a0572bd4.png)

**jest-setup.js**: 

```js
globalThis.ngJest = {
  testEnvironmentOptions: {
    errorOnUnknownElements: true,
    errorOnUnknownProperties: true,
    teardown: { destroyAfterEach: false },
  }
}

```

**Comment by Yohandah** [comment]
My bad sorry, I didn't figured this out, thank you. 

But why do I have to specify the `--setup-file` in CLI when it's specified inside jest.config.js as `setupFilesAfterEnv: ['<rootDir>/setup-jest.js'],`, it doesn't work without the parameter in CLI

**Comment by Yohandah** [comment]
@just-jeb But why do I have to specify the `--setup-file` in CLI when it's already specified inside `jest.config.js` as `setupFilesAfterEnv: ['<rootDir>/setup-jest.js'],`.

It doesn't work without the parameter in CLI. Maintainers at `jest-preset-angular` says that it should work like this. (https://github.com/thymikee/jest-preset-angular/issues/1656#issuecomment-1224078597)

I could also add the options directly into **jest.config.js** and it's not working

**Comment by Yohandah** [comment]
@just-jeb I forgot to push my commit sorry, it's done

**Comment by just-jeb** [comment]
In your example the file is `setup.js` while the file you specify in config is `setup-jest.js`.  
Anyways, the options in the config and the CLI args are mutually replaceable so it should work with config file as well.   
I did the CLI because it was the fastest way to check that it works.

**Comment by Yohandah** [comment]
@just-jeb Oops I missed my copy/paste from my real project, I've corrected that in the reproduction repo.
It's still not working with the config file then, only works via CLI, but it works with the config file using only `jest-preset-angular` as they said here https://github.com/thymikee/jest-preset-angular/issues/1656#issuecomment-1224078597

**Comment by Yohandah** [comment]
Have you managed to reproduce the issue with my repo ?

**Comment by Yohandah** [comment]
@just-jeb Did you succeed making it work with the options in the config instead of the CLI ? Because I still have the issue :(

**Comment by just-jeb** [comment]
I'll try it again and update you.

**Comment by just-jeb** [comment]
If you change `setupFilesAfterEnv` to `setupFiles` it works with the config file as well.  
It's truly puzzling how it works using only `jest-preset-angular` though, because I can see that your `setupFilesAfterEnv` makes it to the final config, so it should work exactly the same.  
Could you please share a reproduction with the working version using only `jest-preset-angular` and `setupFilesAfterEnv`? 
Not the example they give in their repo, but this specific repo using only `jest-preset-angular`? Thank you!
