### ISSUE TITLE
 Module not found error when package contains nested node_modules directory

### ISSUE THREAD

**Issue by kemsky** [just-jeb/angular-builders#1278]
## Describe the Bug

Latest versions on `@angular-builders/custom-webpack` and `@angular-devkit/build-angular` can not build our application.

Many many lines with similar content:
```
./node_modules/rxjs/dist/esm/internal/AsyncSubject.js:1:0-177 - Error: Module not found: Error: Can't resolve '/home/dookie/Documents/projects/sanity-app/node_modules/@angular-builders/custom-webpack/node_modules/@babel/runtime/helpers/esm/classCallCheck.js' in '/home/dookie/Documents/projects/sanity-app/node_modules/rxjs/dist/esm/internal'

./node_modules/rxjs/dist/esm/internal/AsyncSubject.js:2:0-171 - Error: Module not found: Error: Can't resolve '/home/dookie/Documents/projects/sanity-app/node_modules/@angular-builders/custom-webpack/node_modules/@babel/runtime/helpers/esm/createClass.js' in '/home/dookie/Documents/projects/sanity-app/node_modules/rxjs/dist/esm/internal'

./node_modules/rxjs/dist/esm/internal/AsyncSubject.js:3:0-155 - Error: Module not found: Error: Can't resolve '/home/dookie/Documents/projects/sanity-app/node_modules/@angular-builders/custom-webpack/node_modules/@babel/runtime/helpers/esm/get.js' in '/home/dookie/Documents/projects/sanity-app/node_modules/rxjs/dist/esm/internal'

```

## Minimal Reproduction

Reproduction is very simple:
- use `sanity-app` from this repo as a starting point
- update `@angular-builders/custom-webpack` and `@angular-devkit/build-angular`  to the latest versions, "14.0.1" and "14.2.5" currently
- execute `yarn build`

## Expected Behavior

Successful build.

## Environment

<pre><code>
Libs
- @angular/core version: 14.2.5
- @angular-devkit/build-angular version: 14.2.5
- @angular-builders/custom-webpack version: 14.0.1

For Tooling issues:
- Node version: v16.17.1
- Platform:  all

**Comment by just-jeb** [comment]
Could you try to remove `yarn.lock` (or `package-lock.json`) and run the install again?

**Comment by kemsky** [comment]
@just-jeb, it worked!
