### ISSUE TITLE
Passing Jest options directly through "ng test" not longer possible with v14

### ISSUE THREAD

**Issue by fischermatte** [just-jeb/angular-builders#1279]
## Describe the Bug

Passing Jest options directly via npm script in package.json seems to be broken in V14. Is this on purpose? 

```
 "test": "ng test --maxWorkers=33%"
```

Instead the only thing that is working is setting the option fix in angular.json. 

```
...
"test": {
          "builder": "@angular-builders/jest:run",
          "options": {
            "maxWorkers": "33%"
          },
...
```

**Why is this an issue:**  We use a different npm script `"test:ci" :"ng test [other options]"`in our pipeline with other options. Having it in angular.json is not very flexible when you want to have scripts with different options.

## Expected Behavior

Options are passed through to jest.

## Environment

<pre><code>
Libs
- @angular/core version: 14.2.0
- @angular-devkit/build-angular version: 14.2.0
- @angular-builders/jest: 14.0.1

For Tooling issues:
- Node version: 16.14.0
- Platform:  Linux

**Comment by fischermatte** [comment]
Ah, sorry. It seems the reason was the update of jest itself. One has to use `--max-workers=33%` inistead of `--maxWorkers=33%`

**Comment by just-jeb** [comment]
Actually it's not because of Jest but because of Angular CLI (which is still out of my control), it is mentioned in the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#jest-builder). Have a nice one!
