### ISSUE TITLE
lodash version vulnerability

### ISSUE THREAD

**Issue by RomaRathi** [just-jeb/angular-builders#1280]
## Describe the Bug

There is a vulnerability shown for loadsh as mentioned in the image
![Capture](https://user-images.githubusercontent.com/72570363/195869891-94dcdcce-77d3-4005-97e5-a8617d458bfa.PNG)

In the package.lock.json file it is as follows

"@angular-builders/custom-webpack": {
      "version": "13.1.0",
      "resolved": "https://registry.npmjs.org/@angular-builders/custom-webpack/-/custom-webpack-13.1.0.tgz",
      "integrity": "sha512-qhtnAv1i7agk14zeKZZfXjrckYt37OZ+3tsTBLhf3ZFbwREK8L1SNi8xhZ1j1JLGsf2Dp0GEcZrSYeFDweo0WA==",
      "dev": true,
      "requires": {
        "@angular-devkit/architect": ">=0.1300.0 < 0.1400.0",
        "@angular-devkit/build-angular": "^13.0.0",
        "@angular-devkit/core": "^13.0.0",
        **"lodash": "^4.17.15",**
And because of this lower version it is giving issue.
## Minimal Reproduction

**Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducible issues.
Please delete this note once you have read it.

## Expected Behavior

Version should be updated

## Screenshots

Attached

## Environment

<pre><code>
Libs
- @angular/core version: X.Y.Z
- @angular-devkit/build-angular version: X.Y.Z
- @angular-builders/{the name of the builder} version: X.Y.Z

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by RomaRathi** [comment]
How i could update the version in the @angular-builders/custom-webpack
or any other solution for this vulnerability

**Comment by just-jeb** [comment]
We don't use `zipObjectDeep` in the code so no worries. As for your question, you can either upgrade to Angular 14 (and Angular Builders 14) which will [fix](https://github.com/just-jeb/angular-builders/blob/master/yarn.lock#L11918) the warning or use `resolutions` on your `package.json` to directly instruct the package manager to install a newer version of `lodash`.  
But as I said, you have nothing to worry about, we don't use this function.

**Comment by RomaRathi** [comment]
![image](https://user-images.githubusercontent.com/72570363/196425646-9b6b8da2-8b40-4cab-a2e9-091a095ddc31.png)

One more thing these all libraries are causing vulnerability issues and these are all dependencies that we are not directly using.
So is there any other solution to resolve those?
One sol is to update the parent pacakge but that is not possible right now. Please provide any other sol.
Can we directly update that?

For example see below.
"request": {
      "version": "2.88.2",
      "resolved": "https://registry.npmjs.org/request/-/request-2.88.2.tgz",
      "integrity": "sha512-MsvtOrfG9ZcrOwAW+Qi+F6HbD0CWXEh9ou77uOb7FM2WPhwT7smM833PzanhJLsgXjN89Ir6V2PczXNnMpwKhw==",
      "dev": true,
      "requires": {
        "aws-sign2": "~0.7.0",
        "aws4": "^1.8.0",
        "caseless": "~0.12.0",
        "combined-stream": "~1.0.6",
        **"extend": "~3.0.2",**

Here extend is giving issues for the version but already 3.0.2 is installed. It's just this particular package is giving issues.

**Comment by just-jeb** [comment]
You could use [selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) (if you're using `yarn`) or [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) (if you're using `npm`).
