### ISSUE TITLE
can we have esbuild builders?

### ISSUE THREAD

**Issue by giniedp** [just-jeb/angular-builders#1288]
In angular v14 we can opt in for the experimental esbuild builder.

```diff
-"builder": "@angular-devkit/build-angular:browser",
+"builder": "@angular-devkit/build-angular:browser-esbuild",
```

It would be awesome if we could do the same with custom-webpack.

**Comment by just-jeb** [comment]
The experimental `esbuild` builder uses `esbuild` instead of webpack for transformations, so you can't use custom-webpack with `esbuild`, these are two separate build chains 🙃.

**Comment by giniedp** [comment]
i kind of thought it was tied together with esbuild doing the heavy lifting through an esbuild-loader within webpack

**Comment by just-jeb** [comment]
If I remember correctly that's not the case but I double check 👍🏿 .

**Comment by arturovt** [comment]
That's not currently possible to provide a custom ESBuild builder (e.g., `@angular-builders/custom-esbuild`), because there's no ability to hook into their API, which is very experimental. I've created an issue in the Angular CLI repository and awaiting them to provide any public surface to the ESBuild builder.

**Comment by just-jeb** [comment]
https://github.com/angular/angular-cli/issues/24163

**Comment by eng-dibo** [comment]
> so you can't use custom-webpack with `esbuild`

we can name it `custom-esbuild`

**Comment by sfinoteffy** [comment]
Hello, it looks like the issue for custom esbuild has been solved on Angular side: https://github.com/angular/angular-cli/pull/26011
