### ISSUE TITLE
regression @angular-builders/jest 14 missing command shard

### ISSUE THREAD

**Issue by lionel-meunier** [just-jeb/angular-builders#1314]
## Describe the Bug

I use Jest CLI options --shard in my project for split test in separated job in CI.
But with `@angular-builders/jest: @14.0.2`, I have error 

`Error: Unknown argument: shard`

## Minimal Reproduction

I use command 

`ng test --shard=1/2`

## Expected Behavior

I need use shard command in my project

## Environment

<pre><code>
Libs
- @angular/core version: 14.2.9
- @angular-devkit/build-angular version: 14.2.8
- @angular-builders/jest version: 14.0.2

For Tooling issues:
- Node version: 16.17.0 
- Platform:  Windows

**Comment by arturovt** [comment]
Closing since been fixed.
