### ISSUE TITLE
bundleDependencies option is breaking migration to v15 for @angular-builders/custom-webpack:server

### ISSUE THREAD

**Issue by DzmVasileusky** [just-jeb/angular-builders#1340]
## Describe the Bug

After updating to 15th version build process managed by `@angular-builders/custom-webpack:server` is throwing `'bundleDependencies' is not found in schema` error.
But migration guide says:
> No breaking changes (except for updating to Angular 15)

It seems `bundleDependencies` is a breaking change.

## Minimal Reproduction

```
"server": {
      "executor": "@angular-builders/custom-webpack:server",
      "options": {
        "bundleDependencies": true,
        "customWebpackConfig": {
          "path": ".../webpack.server.config.js"
        },
        "main": "...",
        "optimization": true,
        "outputHashing": "media",
        "outputPath": "...r",
        "sourceMap": false,
        "stylePreprocessorOptions": {
          "includePaths": [...]
        },
        "tsConfig": "..."
      },
      "configurations": {
        "dev": {
          "fileReplacements": [
            {
              "replace": "...",
              "with": "..."
            }
          ]
        },
        "proto1": {
          "fileReplacements": [
            {
              "replace": "...",
              "with": "..."
            }
          ]
        },
        "proto2": {
          "fileReplacements": [
            {
              "replace": "...",
              "with": "..."
            }
          ]
        },
        "proto3": {
          "fileReplacements": [
            {
              "replace": "...",
              "with": "..."
            }
          ]
        },
        "staging": {
          "fileReplacements": [
            {
              "replace": "...",
              "with": "..."
            }
          ]
        },
        "production": {
          "fileReplacements": [
            {
              "replace": "...",
              "with": "..."
            }
          ]
        }
      }
    },
```

## Expected Behavior

No error or clear migration guide about breaking changes.

## Environment

<pre><code>
Libs
- @angular/core version: 15.1.4
- @angular-devkit/build-angular version: 15.1.5
- @angular-builders/custom-webpack version: 15.0.0

For Tooling issues:
- Node version: v16.15.0
- Platform:  Mac

**Comment by arturovt** [comment]
They don't allow having our builder in migration code and I'm sure they won't. What you should do before migrations is change the `@angular-builders/custom-webpack` to `@angular-devkit/build-angular`, then run `nx migrate --run-migrations` and then revert builders.

**Comment by just-jeb** [comment]
https://github.com/just-jeb/angular-builders/issues/1342 Duplicate?

**Comment by arturovt** [comment]
Yeah, definitely.
