### ISSUE TITLE
Jest snapshots fail with Angular 15.2.2

### ISSUE THREAD

**Issue by mkemmerling** [just-jeb/angular-builders#1350]
Jest snapshots are broken with Angular 15.2.2. The reason is that Ivy detection fails in jest-preset-angular 12.2.6 (no `ɵivyEnabled` anymore in @angular/core). This is fixed in jest-preset-angular 13.0.1, see https://github.com/thymikee/jest-preset-angular/issues/2003 and https://github.com/thymikee/jest-preset-angular/blob/v13.0.1/CHANGELOG.md.

**Comment by sceed1** [comment]
Problem for me is that @angular-builders/jest requires jest-preset-angular@12.2.3 which produces the following warnings:

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: jest-preset-angular@12.2.3
npm WARN Found: jest@29.5.0
npm WARN node_modules/jest
npm WARN   dev jest@"29.5.0" from the root project
npm WARN   2 more (@angular-builders/jest, jest-when)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer jest@"^28.0.0" from jest-preset-angular@12.2.3
npm WARN node_modules/@angular-builders/jest/node_modules/jest-preset-angular
npm WARN   jest-preset-angular@"12.2.3" from @angular-builders/jest@15.0.0
npm WARN   node_modules/@angular-builders/jest

```

**Comment by just-jeb** [comment]
The upgrade to Jest 29 (as well as to `jest-preset-angular` 13) will happen with the major release of Angular 16, since there are potentially breaking changes.
