### ISSUE TITLE
Support for Angular 16

### ISSUE THREAD

**Issue by d-koppenhagen** [just-jeb/angular-builders#1354]
**Is your feature request related to a problem? Please describe.**
The schematic `@angular-builders/jest` should support Angular 16.

**Describe the solution you'd like**
Update the schematic (peerDependency must support `@angular-devkit/build-angular` for version 16)

**Describe alternatives you've considered**

**Additional context**
Current log

```
                  Package "@angular-builders/jest" has an incompatible peer dependency to "@angular-devkit/build-angular" (requires "^15.0.0", would install "16.0.0").
✖ Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.
```

**Comment by henryruhs** [comment]
You could use the experimental builder for now:

```
{
  "projects": {
    "my-app": {
      "architect": {
        "test": {
          "builder": "@angular-devkit/build-angular:jest",
          "options": {
            "tsConfig": "tsconfig.spec.json",
            "polyfills": ["zone.js", "zone.js/testing"]
          }
        }
      }
    }
  }
}
```

And delete the `jest.config` from the project.

**Comment by just-jeb** [comment]
Hi @d-koppenhagen, 
As @henryruhs suggested you can give `build-angular:jest` a try if it satisfies your needs. Hopefully we'll be able to deprecate `@angular-builders:jest` in favor of the official builder soon 🙏🏿 . 
Regardless, we will be releasing v16 of Angular Builders soon. There are some potentially breaking changes (such as Jest 29) that @arturovt and I should take care of so I assume it will happen sometime next week.

**Comment by henryruhs** [comment]
@just-jeb Thanks a lot for 5+ years maintaining this.

**Comment by hrmcdonald** [comment]
`build-angular:jest` is still very limited feature-wise. Looking forward to one last big update here!

**Comment by alkemist** [comment]
Same problem with `@angular-builders/custom-webpack`

**Comment by just-jeb** [comment]
You're welcome to try the new version under the `@next` tag. We'll give it a few days in beta and then graduate to stable. 
![image](https://github.com/just-jeb/angular-builders/assets/9823087/ceb3e15d-c3a4-45d2-9c3c-d292df5b5d33)

**Comment by flavianh** [comment]
Don't know if this is enough information to help, I've upgraded to 16.0.0-beta.0 for the jest builder and got this error:

```
TypeError: configSet.processWithEsbuild is not a function

      at NgJestTransformer.process (node_modules/jest-preset-angular/build/ng-jest-transformer.js:56:23)
      at ScriptTransformer.transformSource (node_modules/@jest/transform/build/ScriptTransformer.js:542:31)
      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:671:40)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:723:19)
      at Object.<anonymous> (node_modules/jest-preset-angular/setup-jest.js:2:24)
      at Object.require (node_modules/@angular-builders/jest/src/jest-config/setup.ts:1:1)
```

<pre><code>
Libs
- @angular/core version: 16.0.1
- @angular-devkit/build-angular version: 16.0.2
- @angular-builders/jest: version: 16.0.0-beta.0
- - @angular-builders/custom-webpack: version: 16.0.0-beta.0

For Tooling issues:
- Node version: 16.18.1
- Platform:  Mac
</code></pre>

**Comment by maximLyakhov** [comment]
Upgraded to  16.0.0-beta.0
Locally works, but on GitLab CI/CD everything with @Component() fail like that:

```
Component 'BasicLayoutComponent' is not resolved:
     - templateUrl: ./basic-layout.component.html
     - styleUrls: ["./basic-layout.component.scss"]
    Did you run and wait for 'resolveComponentResources()'?
```

**Comment by just-jeb** [comment]
@flavianh Please try to remove your lock file, node_modules folder and then perform a clean install.

**Comment by SchroederSteffen** [comment]
Tested it successfully in small to medium sized projects. 👍 

Needed to force the installation via `npm i -D -f @angular-builders/jest@next` because of conflicting dependencies in the existing installation. (Avoids having to delete the lock file & node_modules folder.)

**Comment by flavianh** [comment]
@just-jeb The bug stands with `jest-preset-angular`. I've opened an issue there. Leaving the details out, I needed to change my `jest.config.ts` and `setupJest.ts` files to plain Javascript files. Now tests run, kudos for the version upgrade!

**Comment by just-jeb** [comment]
Stable version is out.
