### ISSUE TITLE
Is this possible to to configure webpack to run target: ['web', 'es5']  Angular 16?

### ISSUE THREAD

**Issue by KimAlexander** [just-jeb/angular-builders#1444]
## Describe the Bug

webpack.config.js file 
```
module.exports = (config, options, targetOptions) => {
  config.plugins.push(
    new webpack.DefinePlugin({
      target: ['web', 'es5'],
    })
  );

  return config;
};
```

looks like Angular 16 ignores target.  I defined 'es5' inside but still not able to get `es5` bundle

I'm not sure is this is bug or not, maybe i just missing something. But, maybe some advice on this. How can I generate `es5` bundle  by forcing   target: ['web', 'es5'] it `webpack.config.js` file  ?

## Minimal Reproduction

**Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducible issues.
Please delete this note once you have read it.

## Environment

<pre><code>
Libs
- @angular/core version: X.Y.Z
- @angular-devkit/build-angular version: X.Y.Z
- @angular-builders/{the name of the builder} version: X.Y.Z

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by arturovt** [comment]
This is not an issue with Angular builders itself, but rather a third-party configuration problem. Better avenue for support is StackOverflow, but since this is an issue tracker and not a support forum, this issue will be closed.
