### ISSUE TITLE
How do I import the `monaco-editor`?

### ISSUE THREAD

**Issue by mrakgr** [just-jeb/angular-builders#1464]
I am trying to figure out how to import the [`monaco-editor`](https://github.com/microsoft/monaco-editor/tree/main) in [a project](https://github.com/mrakgr/Logo-Clone-In-Angular/tree/4127f061a24da4221ee3e6b0bfc4b08e245588e8) I am working on and failing. When I try to build it, I get the following kinds of errors.

```
./node_modules/monaco-editor/esm/vs/platform/severityIcon/browser/media/severityIcon.css:6:0 - Error: Module parse failed: Unexpected token (6:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  *--------------------------------------------------------------------------------------------*/
| 
> .monaco-editor .zone-widget .codicon.codicon-error,
| .markers-panel .marker-icon.error, .markers-panel .marker-icon .codicon.codicon-error,
| .text-search-provider-messages .providerMessage .codicon.codicon-error,
```

Admittedly, I don't have the style and the css loaders in the [config file](https://github.com/mrakgr/Logo-Clone-In-Angular/blob/4127f061a24da4221ee3e6b0bfc4b08e245588e8/extra-webpack.config.js), but that is because when I try them, they give the following kind of error.

```
./src/styles.css?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):

SyntaxError

(2:7) E:\Webdev\qwe\webpack-trial\src\styles.css Unknown word

  1 | 
> 2 |       import API from "!../node_modules/style-loader/dist/runtime/injectStylesIntoStyleTag.js";
    |       ^
  3 |       import domAPI from "!../node_modules/style-loader/dist/runtime/styleDomAPI.js";
  4 |       import insertFn from "!../node_modules/style-loader/dist/runtime/insertBySelector.js";
```

It only really has trouble loading the styles from the `monaco-editor` package. In my own, it seems that it works.

What should I do here?

**Comment by arturovt** [comment]
I'm closing this issue as it pertains to a matter outside the scope of our support, which is integrating third-party packages into Angular's codebase. This issue is unrelated to the specific package in question.
