### ISSUE TITLE
Add an ability to see the final configuration

### ISSUE THREAD

**Issue by just-jeb** [just-jeb/angular-builders#147]
**Is your feature request related to a problem? Please describe.**
It's hard to understand what's the problem with webpack config if you don't see the resulting (merged) configuration

**Describe the solution you'd like**
`verbose` flag that will print out the resulting configuration (and probably more information that helps in problem identification

**Comment by meltedspark** [comment]
Related to #144

**Comment by arturovt** [comment]
Closing as implemented.
