### ISSUE TITLE
Compilation errors after upgrade to Angular 16

### ISSUE THREAD

**Issue by slh-swisslog** [just-jeb/angular-builders#1475]
## Describe the Bug

I have an application that loads MD, HTML, and TS files at runtime to display sample usage code for other developers.  The same custom webpack configuration worked with Ng14 and Ng15 but fails to build after upgrading to Ng16.  I tried both @angular-builders/custom-webpack 16.0.0 and 16.0.1.

## Minimal Reproduction

https://github.com/shuppert/CustomWebpackNg15
https://github.com/shuppert/CustomWebpackNg16

## Expected Behavior

The code should build under Ng16 the same as it did under prior versions.

## Screenshots

![image](https://github.com/just-jeb/angular-builders/assets/100732337/39a01b4f-4794-41cb-9576-db91bcbe8a7c)
![image](https://github.com/just-jeb/angular-builders/assets/100732337/bc73e252-4b20-49fa-9b59-1059ce9bf204)

## Environment

<pre><code>
Libs
- @angular/core version: 16.2.4
- @angular-devkit/build-angular version: 16.2.1
- @angular-builders/custom-webpack:browser version: 16.0.1

For Tooling issues:
- Node version: 18.17.1
- Platform:  Windows

</code></pre>

**Comment by shuppert** [comment]
FWIW I figured it out.  The fix was to change the way the import with a promise to a require.

``import(`../${this.name}/${this.name}.component.html?raw`).then((res) => {``

was replaced with:
``const html = require(`../${this.name}/${this.name}.component.html?raw`);``
