### ISSUE TITLE
Using pure TypeScript libraries throws error

### ISSUE THREAD

**Issue by WalterWoshid** [just-jeb/angular-builders#1501]
## Describe the Bug

We created a TypeScript library which we would like to use in multiple projects, not all of them are Angular. Doing this results in the runtime error: `TypeError: (0 , _a_cool_library_src_test__WEBPACK_IMPORTED_MODULE_0__.helloWorld) is not a function`

## Minimal Reproduction

1. Create a simple TypeScript library in your project directory (e.g: `my_library`)
2. Add a `package.json` to `my_library` with `name`, `version` and `main` (Not sure if `main` is needed)
3. Link your `main` section to a `index.ts` which exports all functions that should be exported
E.g:
```typescript
// index.ts
export * from './src/test';

// src/test.ts
export function helloWorld(): string {
  return 'Hello world';
}
```
4. Add a `tsconfig.json` with `"include": ["src"]`
5. Install the library in your Angular project: `npm i --save-dev ./my_library` or `yarn add -D ./my_library`
6. Build your Angular project

## Expected Behavior

The built files (`vendor.js` in my example) should include the JavaScript code of the library.

## Actual Result

The built files (`vendor.js` in my example) includes this section:
```javascript
/***/ 4923:
/*!**************************************************!*\
  !*** ./node_modules/@a/cool-library/src/test.ts ***!
  \**************************************************/
/***/ (() => {



/***/ }),
```

## Screenshots

![image](https://github.com/just-jeb/angular-builders/assets/36635504/d019abd8-d3fd-47ae-9e8c-f31bc617ea92)
![image](https://github.com/just-jeb/angular-builders/assets/36635504/e5c472fb-18a1-45a5-a6b2-a97a3593f7c8)
![image](https://github.com/just-jeb/angular-builders/assets/36635504/7acbccfc-480e-423b-aa6b-ff05448687a9)

## Environment

<pre><code>Libs
- @angular/core version: 16.1.7
- @angular-devkit/build-angular version: 16.1.6
- @angular-builders/custom-webpack version: 16.0.0

For Tooling issues:
- Node version: 18.18.1
- Platform:  Arch Linux
</code></pre>

## Error Reason

I have debugged the application and found the culprit. In TypeScript there is this function:
`function sourceFileMayBeEmitted(sourceFile, host, forceDtsEmit)`
which has a lot of conditions.

These conditions (pretty-printed) look like this:
```javascript
const options = host.getCompilerOptions();
    const isNoEmitForJsFiles = options.noEmitForJsFiles;
    const isSourceFileNotJS = !isSourceFileJS(sourceFile);
    const isNotDeclarationFile = !sourceFile.isDeclarationFile;
    const isNotFromExternalLibrary = !host.isSourceFileFromExternalLibrary(sourceFile);

    const shouldEmitDts = forceDtsEmit ||
      (!(isJsonSourceFile(sourceFile) &&
        host.getResolvedProjectReferenceToRedirect(sourceFile.fileName))) &&
      !host.isSourceOfProjectReferenceRedirect(sourceFile.fileName);

    const shouldEmitFile = !isNoEmitForJsFiles &&
      isSourceFileNotJS &&
      isNotDeclarationFile &&
      isNotFromExternalLibrary &&
      shouldEmitDts;

    return shouldEmitFile;
```
Here `shouldEmitFile` is `false` and that's why TypeScript returns an empty string. The reason why `shouldEmitFile` is `false`, is because `isNotFromExternalLibrary` is `false`, because the TypeScript project lies in the `node_modules` folder. When the project is outside of the `node_modules` folder or if I manually set `isNotFromExternalLibrary` to `true` while debugging, it actually generated the code.

## Alternative solutions

I know that we can generate JavaScript ourselves in a `dist` folder for example, but we don't want that.

**Comment by arturovt** [comment]
This is not an issue with Angular builders itself, but rather a third-party library problem. Better avenue for support is StackOverflow, but since this is an issue tracker and not a support forum, this issue will be closed.

**Comment by WalterWoshid** [comment]
Hi @arturovt, thanks for the answer. So should I report this issue to TypeScript then?

**Comment by arturovt** [comment]
The issue may be reproducible with a clean Webpack configuration, w/o any framework, which likely seems to be a TS issue.
