### ISSUE TITLE
Angular 17 Support

### ISSUE THREAD

**Issue by iKrishnaSahu** [just-jeb/angular-builders#1512]
Angular is going to release version 17 in November 2023 and also released 17rc version.

Is there any plan for Angular 17 support?

**Comment by VictorZakharov** [comment]
Especially interested [in this part](https://www.angulararchitects.io/en/blog/whats-new-in-angular-17/):
> "builder" : "@angular-devkit/build-angular:browser-esbuild"

[A related ticket](https://github.com/just-jeb/angular-builders/issues/1288) here on GitHub.

**Comment by alaaahmedmu** [comment]
any updates when will the Angular 17 support will be real?

**Comment by iKrishnaSahu** [comment]
@alaaahmedmu PR is already raised for Angular 17 support - https://github.com/just-jeb/angular-builders/pull/1514

**Comment by iKrishnaSahu** [comment]
@arturovt when can we expect https://github.com/just-jeb/angular-builders/pull/1514 to get merge?

**Comment by hillin** [comment]
A slight bump - this is the last blocker for us to upgrade to Angular 17

**Comment by mdudek** [comment]
You can temporary use forked ng-17-stable branch package:

`yarn add https://gitpkg.now.sh/mdudek/angular-builders/packages/custom-webpack?ng-17-stable`

**Comment by SmailHammour** [comment]
> A slight bump - this is the last blocker for us to upgrade to Angular 17

Same here

**Comment by just-jeb** [comment]
v17 is out.

**Comment by infodusha** [comment]
It seems v17 has outdated `jest-preset-angular` version that throws because `zone.js` changed their imports for `0.14`.
In new preset version that is already fixed.
