### ISSUE TITLE
Support Customization of new application builder

### ISSUE THREAD

**Issue by luca-peruzzo** [just-jeb/angular-builders#1537]
As with other builders, Angular exposed the new application builder function.
```import { buildApplication } from "@angular-devkit/build-angular";```
it is a complete replacement for the browser and server builder and compiles everything with esbuild.
Are you going to integrate this builder allowing customisation?

**Comment by just-jeb** [comment]
@arturovt is [working](https://github.com/just-jeb/angular-builders/pull/1536) on supporting ESBuilder, I assume application builder is one of the goals.

**Comment by mattdsteele** [comment]
Really excited for this! I opened a ticket in the Angular repo which just got an update to [also support custom middleware](https://github.com/angular/angular-cli/issues/25777#issuecomment-1814635133).

@arturovt  were you planning to support custom middleware in your PR? If not, I could potentially extend on your foundation.

**Comment by just-jeb** [comment]
@mattdsteele I'm not sure what's the status of @arturovt PR but I think you can go ahead and create another PR based on his (after we merge his PR you'll have to rebase).

**Comment by just-jeb** [comment]
Actually, @mattdsteele, I see that @arturovt already [added](https://github.com/just-jeb/angular-builders/pull/1536/files#diff-806a7b1bad9f08d9001a13ca2922c5d79d90bc74ffd479af5bf913c7b7471886R8) custom middlewares.

**Comment by muuvmuuv** [comment]
@arturovt can you also add the ability to manipulate the indexHtml, they merged that feature in main already? Since there is no release tag yet maybe something for another angular-builders release.
- PR: https://github.com/angular/angular-cli/pull/26667
- Issue: https://github.com/angular/angular-cli/issues/26299

**Comment by arturovt** [comment]
Yeah I’ll take a look
