### ISSUE TITLE
Jest is not taking my webpack config

### ISSUE THREAD

**Issue by josevelasdev** [just-jeb/angular-builders#1588]
## Describe the Bug

I have an angular project with version 15. I installed  stream-browserify in my angular project to configure an internal library. To run the project I installed a Custom webpack builder to run in the browser but I cannot configure this plugin at the execution of my Jenkins pipeline and my jest test.

```js
const webpack = require('webpack');

module.exports = {
  devtool: false,
  plugins: [
    new webpack.NormalModuleReplacementPlugin(/node:/, (resource) => {
        const mod = resource.request.replace(/^node:/,'');
        switch(mod){
            case 'stream/web':
                resource.request = 'stream/web';
                break;
            default:
                    throw new Error(`Not found ${mod}`)    
        }
    })
  ],
};
}
```

Is there a way to achieve this configuration for jest as well?

Libs
- @angular/core version: 15.2.9
- @angular-devkit/build-angular version: 15.2.9
- @angular-builders/jest version: 15.0.0

For Tooling issues:
- Node version: 18.17.1
- Platform: Windows

**Comment by arturovt** [comment]
Jest is unrelated to Webpack configuration. They're not functioning together.
