### ISSUE TITLE
Natively support webpack.config written in Typescript

### ISSUE THREAD

**Issue by abadakhshan** [just-jeb/angular-builders#16]
Hi

How can I write my extra-webpack.config with Typescript?

**Comment by meltedspark** [comment]
It's not yet supported natively, but you can write the _extra-webpack.config_ with Typescript and then compile it to JavaScript with `tsc`. 
Just do the following:
1. In _package.json_ change the `build` command (or `serve`) to `tsc extra-webpack.config.ts && ng build`
2. Run `npm run build`

**Comment by AlexAegis** [comment]
I would like to see this happen too!

**Comment by NitsanBaleli** [comment]
@meltedspark trying to `tsc extra-webpack.config.ts` as you suggest isn't so straight forward

**Comment by meltedspark** [comment]
@NitsanBaleli Could you elaborate?

**Comment by meltedspark** [comment]
@NitsanBaleli, thanks for sharing!
