### ISSUE TITLE
Custom vite builder

### ISSUE THREAD

**Issue by LukasKlement** [just-jeb/angular-builders#1617]
The default vite application builder of Angular does not support plugins. Similar to custom-webpack, it would be great to be able to support adding plugins to the build process using vite.

See someone else requesting it in the angular-cli repo: https://github.com/angular/angular-cli/issues/26329
Another request: https://github.com/angular/angular-cli/issues/26859

**Comment by just-jeb** [comment]
There is an [ongoing work](https://github.com/just-jeb/angular-builders/pull/1536) on supporting extension for esbuild builder, this should also support plugins for Vite dev-server.

**Comment by edumserrano** [comment]
@just-jeb I looked at #1536 and the documentation for the resulting [@angular-builders/custom-esbuild](https://www.npmjs.com/package/@angular-builders/custom-esbuild) npm package and forgive me for my inexperience but I can't see how/if I can use the `@angular-builders/custom-esbuild` package to extend the vite configuration.

I can see how to use the `@angular-builders/custom-esbuild` package to add custom ESBuild plugins but not how to extend [Vite's configuration](https://vitejs.dev/config/). 

What I'm attempting to do is to use the [vite-plugin-federation](https://github.com/originjs/vite-plugin-federation) to configure module federation for an Angular 17 app (using vite+ESBuild). Looking at `vite-plugin-federation`'s documentation, the first step is to modify the `vite.config.js` which the angular cli does not expose as per angular/angular-cli#26859. I've been following the work on #1536 in hopes it would provide a solution that would allow me to extend Angular's vite configuration like the [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) package allows extending Angular's webpack configuration.

Am I missing something or is this not supported?
