### ISSUE TITLE
Latest version of Angular uses application rather than [browser|server|karma|dev-server|extract-i18n]"

### ISSUE THREAD

**Issue by REPTILEHAUS** [just-jeb/angular-builders#1657]
Im migrating an older project to a new angular 17 with SSR the builder is called `application` rather than any of the predefined ones ` "builder": "@angular-builders/custom-webpack:[browser|server|karma|dev-server|extract-i18n]",` 

running with my angular.json throws the following error 

```
An unhandled exception occurred: Cannot find builder "@angular-builders/custom-webpack:application".
See "...../angular-errors.log" for further details.
```

**Comment by arturovt** [comment]
The `:application` is the ESBuild builder, please refer to the documentation https://github.com/just-jeb/angular-builders/blob/master/packages/custom-esbuild/README.md.
