### ISSUE TITLE
[QUESTION] Can `@angular-builders/custom-esbuild` be used to extend the Vite configuration of an Angular 17 app?

### ISSUE THREAD

**Issue by edumserrano** [just-jeb/angular-builders#1660]
I've been looking for a way to extend the Vite configuration of an Angular 17 app and came across this issue angular/angular-cli#26859 which took me to #1617 and #1537, both of which were closed by the work done in #1536 that resulted in the [@angular-builders/custom-esbuild](https://www.npmjs.com/package/@angular-builders/custom-esbuild) npm package.

I've looked at the [docs](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-esbuild) for `@angular-builders/custom-esbuild` and checked out the example apps at [/examples/custom-esbuild](https://github.com/just-jeb/angular-builders/tree/master/examples/custom-esbuild) but I can't figure out how to extend the Vite configuration for an Angular 17 app.

To provide more context, I'd like to be able to use things like:

- [vite-plugin-federation](https://github.com/originjs/vite-plugin-federation)
- [vite-plugin-istanbul](https://github.com/iFaxity/vite-plugin-istanbul)

But I'm stuck because I don't know how to extend the `vite.config.js` for an Angular 17 app? I was hoping that the `@angular-builders/custom-esbuild` would let me configure some kind of `customViteConfig` similar to how the [@angular-builders/custom-webpack](https://www.npmjs.com/package/@angular-builders/custom-webpack) let's you configure a [customWebpackConfig](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-object).

Is this possible and I'm just missing something simple or is this not supported ? Perhaps @muuvmuuv and @arturovt can provide some guidance here?

**Comment by muuvmuuv** [comment]
Nope, from what I know, you wont and perhaps never will. Angular injects a lot of custom stuff into Vite for their bundling. I don't think this is something you will be able to do. I have also tried it to support http2 for proxy but there is no API or anything in that context.

**Comment by edumserrano** [comment]
Well, that's... sad. It does limit Angular apps wanting to use the new application builder since they're locked out of a lot of the ecosystem that exists for Vite such as the 2 plugins I linked above.

Furthermore I tried to use [esbuild-plugin-istanbul](https://www.npmjs.com/package/esbuild-plugin-istanbul) and couldn't get that ESBuild plugin to work. I created an issue requesting assistance abraha2d/esbuild-plugin-istanbul#1 and the author found this comment [vitejs/vite#2238 (comment)](https://github.com/vitejs/vite/issues/2238#issuecomment-808943494) which says:
> The reason why you can't use on-load plugins with the transform API is that it's pointless. The transform API takes the code as a string so if you want to transform the string before esbuild processes it, you can just transform the string yourself first before giving it to esbuild. You don't need the plugin API for that.

Which meant that I can't also use the `esbuild-plugin-istanbul` or from what I understand any ESBuild plugin that uses the "on-load" functionality. Does this look correct @muuvmuuv or this isn't actually a limitation and there's a way to get it to work for this kind of ESBuild plugins?

**Comment by muuvmuuv** [comment]
You must understand that Vite is just used as the dev-server. For the builder they mainly use esbuild so you must use esbuild plugins.

Furthermore, I also tried esbuild Sentry plugin which also does not work because Angular does not actually write the files until end which Sentry requires to upload. The build process with esbuild is still not a golden egg yet but will be developed further. I suggest you to open an issue at Angular and state your use case so that it gets attraction.

You can read a lot about that issue here: https://github.com/getsentry/sentry-javascript-bundler-plugins/issues/351

**Comment by edumserrano** [comment]
Thank you for the guidance @muuvmuuv

**Comment by apappas1129** [comment]
I know this is outside the scope of `@angular-builders/custom-esbuild`, but I am hoping to find help on how to use a custom `@angular-devkit/build-angular:dev-server` (vite) server so i can provide my own vite config extending whatever is Angular's default.
