### ISSUE TITLE
not using path.join() makes the scirpt break on windows 

### ISSUE THREAD

**Issue by emonidi** [just-jeb/angular-builders#1682]
https://github.com/just-jeb/angular-builders/blob/7bba25020597132d2a444811888c92ccefa09775/packages/custom-webpack/src/custom-webpack-builder.ts#L41

creating the `webpackConfigPath` like that on windows results as `C:\Users\some_dir\some_dir\some_dir/some_dir/some_dir/tsconfig.app.json`  which throws an error

**Comment by arturovt** [comment]
Shouldn't be a case anymore.
