### ISSUE TITLE
esbuild pass additional entry points

### ISSUE THREAD

**Issue by ArielGueta** [just-jeb/angular-builders#1692]
Hi,

Is there anyway to pass additional entry points when using the custom esbuild builder?

```ts
"architect": {
  ...
  "build": {
    "builder": "@angular-builders/custom-esbuild:application",
    "options": {
      "additionalEntryPoints": ["foo.ts", "bar.ts"]
    }
```

Thanks.

**Comment by arturovt** [comment]
No, there are no such options within the original builder schema. Angular custom builders act as wrappers over the original Angular builders, but they only enable calling additional APIs exposed by the original Angular builders.
