### ISSUE TITLE
[custom-esbuild] Add --deploy-url to custom application builder

### ISSUE THREAD

**Issue by chergui** [just-jeb/angular-builders#1728]
**Is your feature request related to a problem? Please describe.**
Currently, the custom-esbuild lacks support for the deployUrl property, despite its reintroduction in the latest Angular 17.3 release.

**Describe the solution you'd like**
I would like to request the addition of support for the deployUrl property within the  custom-esbuild. This enhancement would enable developers to specify the base URL for their applications during the build process.

**Describe alternatives you've considered**
One alternative solution could be for developers to manually configure the deployUrl property outside, but this approach adds complexity and reduces efficiency in the development workflow. Integrating this feature directly into the custom-esbuild would provide a more seamless experience for developers.

**Additional context**
[Issue on Angular.](https://github.com/angular/angular-cli/issues/26411)

**Comment by just-jeb** [comment]
What do you get right now when you try to use it with `custom-esbuild` and Angular 17.3?

**Comment by chergui** [comment]
I have this error : "Error: Schema validation failed with the following errors: "Data path "" must NOT have additional properties(deployUrl)".

 

The schema file in [node_modules/@angular-builders/custom-esbuild/dist/application/schema.json](mailto:node_modules/@angular-builders/custom-esbuild/dist/application/schema.json) miss deploy url entry :

 

`"deployUrl": {

      "type": "string",

      "description": "Customize the base path for the URLs of resources in 'index.html' and component stylesheets. This option is only necessary for specific deployment scenarios, such as with Angular Elements or when utilizing different CDN locations."

    }`

 

Angular 17.3.2

@angular-builders/custom-esbuild": "17.1.2-beta.1"

 

Thank you

**Comment by just-jeb** [comment]
Should be solved in the latest beta version. @chergui could you validate please before I graduate?

**Comment by chergui** [comment]
I confirm that I no longer have the problem. THANKS
