### ISSUE TITLE
Support for Angular v18

### ISSUE THREAD

**Issue by adisreyaj** [just-jeb/angular-builders#1786]
**Is your feature request related to a problem? Please describe.**
Angular v18 was released on May 23rd. The latest version of `@angular-builders/jest` has a peer dep on Angular v17. To be able to use newer version of Angular, we need to update the deps of the packages.

**Describe the solution you'd like**
Update the deps of the packages to support the newer Angular v18

**Comment by playerx** [comment]
+1

**Comment by phihochzwei** [comment]
+1 :)

**Comment by just-jeb** [comment]
WIP, probably will release in the coming week.

**Comment by just-jeb** [comment]
You're welcome to try out `v18` beta under `@next` tag.
