### ISSUE TITLE
Add plugin esbuild

### ISSUE THREAD

**Issue by adrien3** [just-jeb/angular-builders#1852]
Hello, 
I've tried many things but unfortunately, I can't integrate an external plugin (https://github.com/esbuild/community-plugins). 
My idea is to add https://github.com/luckycatfactory/esbuild-graphql-loader to the plugin so that my gql files are transformed into ts. However, I always get errors in my console. 

```
const plugin: Plugin = {
  name: 'update-external',
  setup(pluginBuild: PluginBuild) {
    pluginBuild.esbuild
      .build({
        plugins: [graphqlLoaderPlugin({ filterRegex: /\.(graphql|gql)$/ })],
      })
      .catch(() => {
        process.exit(1);
      });
  },
};

export default plugin;
```

However, when building, I have an error that comes up
```
✘ [ERROR] No loader is configured for ".gql" files: libs/shared/util/preference/src/lib/graphql/tracking-config-query.gql

    libs/shared/util/preference/src/lib/graphql/index.ts:2:32:
```

Is this an error in the lib or in my implementation? Thanks in advance

**Comment by arturovt** [comment]
You should be doing this:

```ts
import graphqlLoaderPlugin from '@luckycatfactory/esbuild-graphql-loader';

const plugin = graphqlLoaderPlugin({ filterRegex: /\.(graphql|gql)$/ });

export default plugin;
```

Tried this out personally:

```gql
// schema.gql

type Post {
  author: String!
  name: String!
}
```

```ts
// main.ts

// @ts-ignore
import schema from './schema.gql';
console.log(schema);
```

![image](https://github.com/user-attachments/assets/f2e70223-7e25-4f27-ab27-a8e4f1694c0a)
