### ISSUE TITLE
Custom webpack config not getting picked up, asset-inline rule not working

### ISSUE THREAD

**Issue by lazartsarev** [just-jeb/angular-builders#1857]
## Describe the Bug

Added custom webpack config but it seems like it's being picked up from the builder.

## Minimal Reproduction

Clone https://github.com/lazartsarev/angular-16-crud-example
Run npm install
Run npm run build

## Expected Behavior

The src/assets/camera.svg to be inline packaged instead it is created as a separate asset and downloaded on opening the app.

Maybe I'm missing something in terms of merge rules config, I tried all kinds of different combinations there, but couldn't resolve the problem.

## Environment

<pre><code>
Libs
- @angular/core version: 16.0.0
- @angular-devkit/build-angular version:16.0.2
- @angular-builders/{the name of the builder} version:16.0.1

</code></pre>

## Additional Context

I'm adding a new rule in the webpack config like this:
module.exports = (config, options, targetOptions) => {
  config.module.rules.unshift({
    test: /\.svg/,
    type: 'asset/inline',
  });

  return config;
};

All my changes in order to get this to work can be seen in this commit - https://github.com/lazartsarev/angular-16-crud-example/commit/44c488ced0e89edfa980c24f46f264d8ddb9fe89

I would appreciate any feedback or clues, since I'm out of ideas on how to resolve this one.

**Comment by arturovt** [comment]
The `asset/inline` targets JS files to inline asset files directly into the JavaScript bundle and not CSS files.

Please note that this repository provides a wrapper around the Angular builder. We're not modifying Webpack configurations, and we are not responsible for user's extended configurations or why they might not work.

**Comment by lazartsarev** [comment]
@arturovt any idea how to extract the generated webpack config file so that I can take a look at the current rules? Regarding asset-inline what I gather from the documentation it's supposed to work just like the url-loader worked for loading any assets (fonts, images). Before upgrading our angular we had url-loader configured and it was working fine for these images.
