### ISSUE TITLE
Support for Angular 19

### ISSUE THREAD

**Issue by d-koppenhagen** [just-jeb/angular-builders#1869]
**Is your feature request related to a problem? Please describe.**
Since Angular 19 was released today, it should be supported by this package and therefore defined as allows peerDependency.

**Describe the solution you'd like**
bump version

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by salztorte** [comment]
+1

**Comment by just-jeb** [comment]
I wish it would be as simple as just bumping the version but unfortunately it's a process that requires a bit of work.   
I'm really short on free time now but I'll do my best to do it ASAP.

**Comment by LanderBeeuwsaert** [comment]
We are getting failing tests with:
"No value provided for @angular/core symbol 'ɵɵStandaloneFeature'"
and
"ReferenceError: _ts_decorate is not defined"
any idea if this is because of that this library isn't adapted/upgraded to angular 19?

**Comment by salztorte** [comment]
@LanderBeeuwsaert I think the symbol ɵɵStandaloneFeature does not exist anymore in angular 19.
I searched for it in angular 18 and found something, but not in angular 19

**Comment by LanderBeeuwsaert** [comment]
@salztorte indeed would make sense now that standAlone has become the default.
But we upgraded all our angular packages to 19 so I suppose that it's the dependencies of this library that are still on 18 that are giving the issue:
![image](https://github.com/user-attachments/assets/fa23fba6-00aa-41b2-941a-ae93396c84c3)

**Comment by bobbyquantum** [comment]
@arturovt #1871 passes CI if jest-preset-angular is updated to [14.4.0-rc.0](https://github.com/thymikee/jest-preset-angular/releases/tag/v14.4.0-rc.0), and all references to zone.js are updated to 0.15.0.
 
https://github.com/bobbyquantum/angular-builders/actions/runs/12028925443

**Comment by khvedela** [comment]
any updates on this issue ?

**Comment by bobbyquantum** [comment]
The final release of jest-preset-angular 14.4.0 is out now

**Comment by salztorte** [comment]
When is the release of v19 planed?
I do not want use a beta version in my project.

**Comment by salztorte** [comment]
@just-jeb Thank you.

**Comment by SchroederSteffen** [comment]
I noticed only today that v19 has been released already: https://www.npmjs.com/package/@angular-builders/jest?activeTab=versions 👀
