### ISSUE TITLE
Custom loader not working on production - Custom webpack

### ISSUE THREAD

**Issue by vasicvuk** [just-jeb/angular-builders#192]
**Describe the bug**

I added webpack-replace-loader to extra-webpack.config.js file but it works only with command `ng serve`. When i do build with `ng build` it does not work at all. I tried disabling extractCss but it didn't help.

**To Reproduce**
Here is the code of extra webpack config i am using:
```
var path = require('path');
module.exports = {
    node: {
        global: true,
        crypto: 'empty',
        process: true,
        module: false,
        net: 'empty',
        clearImmediate: false,
        setImmediate: false
    },
    module: {
        rules: [
            {
                test: /\.[0-9a-z]+$/,
                use: [
                    {
                        loader: 'webpack-replace-loader',
                        options: {
                            arr: [
                                { search: '~assets', replace: 'assets', attr: 'g' },
                            ]
                        }
                    }
                ]
            }
        ]
    },
    resolve: {
        alias: {
            assets: path.resolve('src/assets')
        }
    }
};

```

**Expected behavior**

It should work for both production and development

**Builder:**
 - The name of the builder: @angular-builders/custom-webpack:browser
 - The version of the builder 7.1.1

**Libraries**
 - `angular-devkit/build-angular`:  0.11.0

**Comment by meltedspark** [comment]
You don't need the custom webpack builder for this. There is an out of the box option called `fileReplacements` which you can use I believe.  
In any case, if your config doesn't work there might be a bug in the builder so let's investigate. Would you mind creating a minimal reproduction repository?

**Comment by vasicvuk** [comment]
**fileReplacements**  is for replacing whole files. The loader on the other hand replaces text in file. 

I fixed the issue the other way without the loader but still there i no reason why the loader didn't work for production and it work with ng serve.

**Comment by meltedspark** [comment]
I agree. Would you mind creating a minimal reproduction? Also, have you tried to use merge strategy `"module.rules": "prepend"`.

**Comment by guillaumedoutriaux** [comment]
I ran into the same problem on a project I am currently working on. I am using a PostCSS loader to convert pixels to rem and it fails on production build `ng build --prod`. Everything is fine when I use the command `ng serve`.

I have tried a few things, like :
- "extractCss": false
- merge strategy to prepend

The version of the builder is 8.0.2 and I am using Angular 8.0.3.

It only works when I disable AOT or if I remove the posts loader.

My custom webpack config is the following :
``` javascript
const pxtorem = require("postcss-pxtorem");

module.exports = {
  module: {
    rules: [
      {
        test: /\.scss/,
        use: [
          {
            loader: "postcss-loader",
            options: {
              ident: "postcss",
              plugins: () => [pxtorem()]
            }
          },
          { loader: "sass-loader", options: { sourceMap: true } }
        ]
      }
    ]
  }
};
```

I create a minimal reproduction of the problem :[ in this repo]( https://bitbucket.org/guillaume-yoozly/issue-builder-custom-webpack/src/master/)

**Comment by just-jeb** [comment]
@guillaumedoutriaux #66 is certainly related to your problem.

**Comment by guillaumedoutriaux** [comment]
I have just done a new test by updating all the dependencies with the following versions :
- @angular : 8.2.14
- @angular-devkit/build-angular: 0.803.19,
- @angular-builders/custom-webpack: 8.3.0
 
Now I have this error when I try a build in production :
`ERROR in ./src/app/app.component.scss.shim.ngstyle.js
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Invalid CSS after " */": expected 1 selector or at-rule, was 'var styles = [".iss'
      in /Users/guillaume/Local Sites/sandbox/issue-builder-custom-webpack/src/app/app.component.scss.shim.ngstyle.js (line 6, column 4)
Error: Invalid CSS after " */": expected 1 selector or at-rule, was 'var styles = [".iss'
      in /Users/guillaume/Local Sites/sandbox/issue-builder-custom-webpack/src/app/app.component.scss.shim.ngstyle.js (line 6, column 4)
    at options.error (/Users/guillaume/Local Sites/sandbox/issue-builder-custom-webpack/node_modules/node-sass/lib/index.js:291:26)
 @ ./src/app/app.component.ngfactory.js 7:0-56 11:27-36
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts`

I have updated the test [repo](https://bitbucket.org/guillaume-yoozly/issue-builder-custom-webpack/src/test-updated-deps/) with the updated versions.

**Comment by guillaumedoutriaux** [comment]
After further investigation, I finally found the origin of the problem : I was missing the $ in the test rule, ie `test: /\.scss$/` instead of `test: /\.scss/`.

**Comment by arturovt** [comment]
@vasicvuk 

You have to provide a reproduction. I just took the example from the `webpack-replace-loader` docs and it seems to work:

![image](https://user-images.githubusercontent.com/7337691/69079351-78430980-0a42-11ea-88ea-50d42455ac63.png)

The only thing I did is I've set the `mergeStrategies` to `prepend`:
```js
// angular.json
"mergeStrategies": {
  "module.rules": "prepend"
}
```
