### ISSUE TITLE
stylePreprocessorOptions doesn't work with @angular-builders/custom-webpack:browser

### ISSUE THREAD

**Issue by losbeekos** [just-jeb/angular-builders#219]
**Describe the bug**
When I include a path to the `stylePreprocessorOptions` object it doesn't work how it's supposed to work with `@angular-builders/custom-webpack:browser`, it works fine with the default builder (eg `@angular-devkit/build-angular:browser`).

```
"stylePreprocessorOptions": {
  "includePaths": [
    "src/scss"
  ]
 },
```

**To Reproduce**
1. Add a path to stylePreprocessorOptions.includePaths Array
2. Include a file in `src/scss` named `_variables.scss`
3. Make an Angular component with SCSS
4. Import the variables in that component SCSS file `@import 'variables';`
5. Check the error, it can't find the file

**Expected behavior**
The file should work as expected.

**Builder:**
 - @angular-builders/custom-webpack:browser
 - 7.2.0

**Libraries**
 - `angular-devkit/build-angular`: 0.12.3

**Comment by meltedspark** [comment]
Hey, thanks for the report! Would you mind creating a small repo with reproduction? Will speed it up a bit. Thanks!

**Comment by arturovt** [comment]
@losbeekos 

Could you provide a reproduction? I just went through your steps and it works like a charm:

![image](https://user-images.githubusercontent.com/7337691/69091373-d2e46180-0a52-11ea-853c-306c43dd43eb.png)

**Comment by losbeekos** [comment]
Thanks for the replies but this issue is not relevant anymore, it works like it's supposed to.
