### ISSUE TITLE
The configuration example link in the README is dead

### ISSUE THREAD

**Issue by ibenjelloun** [just-jeb/angular-builders#249]
**Describe the bug**
In the [README file](https://github.com/meltedspark/angular-builders/blob/master/packages/jest/README.md), the link to the configuration example is dead :

Take the [default configuration](https://github.com/angular-builders/jest/blob/master/src/jest-config/default-config.ts) from the library

**Expected behavior**
Change the link to a working link or remove the link.

**Comment by meltedspark** [comment]
Thanks for reporting. The right link would be: https://github.com/meltedspark/angular-builders/blob/master/packages/jest/src/jest-config/default-config.ts

**Comment by mousedownmike** [comment]
In case anyone else looks to do this one, it's already done in PR: #576

**Comment by arturovt** [comment]
This can be closed due to #610 PR.

**Comment by just-jeb** [comment]
Thanks @arturovt
