### ISSUE TITLE
Extending angular.json schema with custom options?

### ISSUE THREAD

**Issue by llwt** [just-jeb/angular-builders#276]
I'm looking to use the function callback in `@angular-builders/custom-webpack` for for environment based webpack configuration. However any any unexpected values in the `angular.json` cause the schema validation to fail.

### Example `webpack.config.json`:
```js
module.exports = (config, options) => {
  if (options.someCustomConfiguration) {
    config.plugins.push(
      // some environment specific webpack plugin
    )
  }

  return config;
};
```

**Describe the solution you'd like**
A way to extend the valid schema in `angular.json` OR pass environment specific configuration into the webpack callback function.

**Describe alternatives you've considered**
As an alternative I was going to try and detect the environment and load the configuration from an external file,  however I found no good way way to detect the configuration name from the passed in options.

The other option I was thinking about was creating another builder that extended this one to provide a custom schema, however that seemed a bit overkill and error prone.

**Comment by meltedspark** [comment]
You can simply use plain environment variables (by setting them before the build in `package.json`) and use them like in [this] (https://github.com/meltedspark/electron-angular-native/blob/master/native-webpack.config.js) example.

**Comment by meltedspark** [comment]
You can simply use plain environment variables (by setting them before the build in [`package.json`] (https://github.com/meltedspark/electron-angular-native/blob/1fbbd124112f2dc75e14a57808430a55fdc412a4/package.json#L42)) and use them like in [this] (https://github.com/meltedspark/electron-angular-native/blob/master/native-webpack.config.js) example.

**Comment by llwt** [comment]
The issue is we have configuration that doesn't fit well in env vars and some apps that have a ton of environments.

The specific usecase we're looking at is inlining external includes into the index.html at build time. For example:

```json
          "configurations": {
            "dev": {
              "includes": [
                  {
                    "type": "script",
                    "src": "path-to-dev-tag-manager.com",
                    "async": true,
                    "location": "body"
                  }
              ]
            },
            "prod": {
              "includes": [
                  {
                    "type": "script",
                    "src": "path-to-prod-bug-reporter",
                    "async": false,
                    "location": "head"
                  },
                  {
                    "type": "script",
                    "src": "path-to-prod-tag-manager.com",
                    "async": true,
                    "location": "body"
                  }
              ]
            }
```

**Comment by meltedspark** [comment]
You can have multiple config files and use each of then in the corresponding configuration.  
Then you can run the build with `configuration` option: `ng build --configuration=dev`.  
[Example](https://github.com/meltedspark/angular-builders/tree/master/packages/custom-webpack/examples/append-webpack-plugins) for app with multiple configs.

**Comment by llwt** [comment]
Sure, but having a separate place to define which scripts get inlined is a lot less ergonomic than having them defined in the `angular.json`.

**Comment by meltedspark** [comment]
In that case it does sound right to create a custom builder. The thing is, you do want schema validation so that you'd be able to catch errors in your configuration. The moment you allow anything to be entered in the `options` object you lose this capability.  
As for you specific use case there is something you should know anyways. 
In Angular CLI 8 they are no longer generating `index.html` with Webpack. So if your solution uses Webpack to append the scripts to html it will stop working the moment you upgrade to version 8. 
The only way to change the html is having a separate script that changes `index.html` in `dist` after the build. Dev server though still uses Webpack so you'll need it for development. 
I'm talking about current implementation, it might change in the future. Maybe @clydin could provide more details on their plans.
