### ISSUE TITLE
__webpack_public_path__ not recognized in webpack.config.js

### ISSUE THREAD

**Issue by tYYGH** [just-jeb/angular-builders#291]
**Describe the bug**
I have started a new Angular 7 project. I need to set the public-path because the whole application will be packaged as a WAR file and deployed in eg. `webapps/myapp.war` of a Tomcat server. Thus the URL will be http://localhost:8080/myapp/.

Overloading `output.publicPath` does not work. However, configuring `baseHref` and `deployUrl` in the `options` in `angular.json` does work.
And I _can_ take this prefix into account in my Typescript files, eg.:

```typescript
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, __webpack_public_path__ + '/assets/i18n/');
}
```

However, using this same `__webpack_public_path__` variable in my `webpack.config.js` file does not work: variable unknown.

Yet I need this variable to configure the proxy, so that Webpack Dev Server can dynamically serve the Angular stuff on port 4200, while Eclipse/Tomcat (on port 8080) can dynamically serve the Java stuff, the proxy feature being there to avoid CORS errors.

**Builder:**

`package.json`:

```json
…
  "devDependencies": {
    "@angular-builders/custom-webpack": "~7.2.0",
    "@angular-builders/dev-server": "~7.2.0",
    "@angular-devkit/build-angular": "~0.12.1",
…
```
The last line’s version is a constraint I should keep…

`angular.json`:

```json
…
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./webpack.config.js"
            },
            "baseHref": "/myapp/",
            "deployUrl": "/myapp/",
…
        "serve": {
          "builder": "@angular-builders/dev-server:generic",
          "options": {
            "browserTarget": "myapp:build"
          },
```

**Comment by just-jeb** [comment]
Is this issue still relevant with version 8?
