### ISSUE TITLE
Unable to auto merge custom htmlwebpackplugin opitons

### ISSUE THREAD

**Issue by yinshuxun** [just-jeb/angular-builders#301]
**Describe the bug**
I want to add a parameter of htmlwebpackplugin locally，Want to write html always to disk，
But it does not take effect

angular.json:
```
"build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "webpack.config.js"
            }
}
```
webpack.config.js
```
{
 plugins: [
    new HtmlWebpackPlugin({
            alwaysWriteToDisk: true,
            chunksSortMode: 'none',
          }),
    new HtmlWebpackHarddiskPlugin()
  ]
}
```

Builder:
"@angular-builders/custom-webpack": "^7.4.3",
"@angular-builders/dev-server": "^7.3.1",
Libraries
"@angular-devkit/build-angular": "^0.13.7"
"@angular/cli": "^7.3.7"
"@angular/compiler-cli": "^7.2.11"

**Comment by yinshuxun** [comment]
I thought of a way, this is effective, but is there a better way to be compatible with this common plugin?Or synchronize similar options to IndexHtmlWebpackPlugin？

webpack.config.js
```
module.exports = function(config, options) {
      const indexHtmlPlugins = config.plugins.filter(
        p => p.constructor.name === 'IndexHtmlWebpackPlugin',
      );
      indexHtmlPlugins.forEach(plugin=>{
        config.plugins.push(
          new HtmlWebpackPlugin({
            template: plugin._options.input,
            filename: plugin._options.output,
            alwaysWriteToDisk: true,
            inject: 'body',
            cache: false,
            alwaysWriteToDisk: true,
            showErrors: true,
            chunksSortMode: 'none',
          }),
        );
      })
      config.plugins.push(new HtmlWebpackHarddiskPlugin());
  }

  return config;
};

```

**Comment by pipeng119** [comment]
I also met the same problem - according to the normal configuration, and presents the default configuration to merge, may I have your problem solved?

**Comment by just-jeb** [comment]
I'm not sure what is your use case. Please bear in mind that `IndexHtmlWebpackPlugin` is not in use since Angular 8. Please refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) if you are in Angular 8. If you are using Angular 7 please elaborate on your use case.

**Comment by yinshuxun** [comment]
@just-jeb thanks！

**Comment by pipeng119** [comment]
> I'm not sure what is your use case. Please bear in mind that `IndexHtmlWebpackPlugin` is not in use since Angular 8. Please refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) if you are in Angular 8. If you are using Angular 7 please elaborate on your use case.

#

> I'm not sure what is your use case. Please bear in mind that `IndexHtmlWebpackPlugin` is not in use since Angular 8. Please refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) if you are in Angular 8. If you are using Angular 7 please elaborate on your use case.



> I'm not sure what is your use case. Please bear in mind that `IndexHtmlWebpackPlugin` is not in use since Angular 8. Please refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) if you are in Angular 8. If you are using Angular 7 please elaborate on your use case.



> 我不确定您的用例是什么。请记住，`IndexHtmlWebpackPlugin`自Angular 8以来就没有使用过。如果您使用的是Angular 8，请参阅[迁移指南](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder)。如果您使用的是Angular 7，请详细说明您的用例。


> I'm not sure what is your use case. Please bear in mind that `IndexHtmlWebpackPlugin` is not in use since Angular 8. Please refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) if you are in Angular 8. If you are using Angular 7 please elaborate on your use case.

I'm sorry, I repeat the problem that I met.I use @ presents - builders/custom - webpack normal plug-in configuration angular8 project, hope to add some custom webpack configuration.But on the basis of the files in the plug-in configuration, can normal building, but custom configuration and angular8 merge the default configuration.

```
//angular.json
...
"builder": "@angular-builders/custom-webpack:browser",
      "options": {
        "customWebpackConfig": {
          "path": "./extra-webpack.config.js",
          "mergeStrategies":{"externals":"replace"},
         }
...
```

```
//extra-webpack.config.js
const path = require('path');
module.exports = {
  module: {
    rules: [{
      test: /\.css$/,
      use: [{
        loader: 'px2rem-loader',
        // options here
      }]
    }]
  },
  output: {
    filename: 'bbb.js',
    path: path.resolve(__dirname, './wgo')
  }
};
```
Then execute command `npm run build`, generates wgo folder, but there's not index.html in this folder.  And change the output directory package again, original files in the directory is not empty, which means that the clear - webpack - plugin plug-in is not effective, so I don't think on the basis of my existing configuration options to custom configuration and angular8 default configuration merged, would like to ask you is how the configuration。
I might not be the expression of clear and hope you can understand me, look forward to your reply, thank you
