### ISSUE TITLE
Improve contributing experience

### ISSUE THREAD

**Issue by michaeljota** [just-jeb/angular-builders#350]
**Is your feature request related to a problem? Please describe.**

This project is great. Contributing to this was easy and clear, but I think this can be improve for people that are not so familiarize with Lerna. Also, I found inconsistent indentation, quote marks and semi colon usage. And, scripts in packages are mean to be run as if the modules are hoisted, but this seems unnecessary as Lerna would install the modules in a way that Node is able to resolve the package if they are hoisted or not. 

**Describe the solution you'd like**

I think that with some scripts in `package.json`, running `npm install`/`yarn install` could bootstrap all the dependencies and related packages. Also, having a consistent dependency tree across the projects would also allow to hoist the projects. 

Improving the scripts in the packages would allow to use them either if it is installed in hoisted mode or not.

Using Prettier would reduce significantly the inconsistency in formatting. Additional TSLint rules could be used to improve readability as well.

**Additional context**

This changes should affect only how the project is setup and not the behavior of the code.

**Comment by meltedspark** [comment]
You're 💯 % right. There is a lot of technical debt accumulated during years of development. Part of it in devops field (like setting up commitizen, tslint, semantic-release and more) part in code base (improve tests, reduce duplicate code, use async for file operations etc.).   
A lot of improvements can be made to documentation, for example adding `CONTRIBUTING.MD` that explains the setup.   
Specifically regarding the things you've mentioned (`package.json` scripts) it is mostly for historical reasons (the project moved to lerna a few months ago). I assume it can be safely removed.  

Unfortunately I don't have enough time to handle all this stuff so I have to prioritize. For example implementing `indexTransform` was the top priority feature for now. Critical bugs that have no workarounds are top priority as well.  
There is always stuff to do and any help appreciated. If you feel into contributing you're most welcome. 
If you want to chat find me on [Slack](https://join.slack.com/t/angular-builders/shared_invite/enQtNTk5MDE1Nzg2ODM3LTkzMzI5ODQwYzRkOGZhZDJkNWI3OGJjNTM4YzNlY2MxZGU0ZjQ3NzVjZGEzNzYzNDFlOWM2YmQwZGQ3NzlkOWY). 

Thanks for your insight!

**Comment by michaeljota** [comment]
I see. Do you mind if I work on this? I kind of like this sort of work. :P.

**Comment by meltedspark** [comment]
Sure, go ahead. Let's talk tomorrow on Slack and see how exactly you can contribute?

**Comment by just-jeb** [comment]
This issue probably should be broken down into a few smaller issues. Closing.
