### ISSUE TITLE
custom-webpack-builder in Angular library

### ISSUE THREAD

**Issue by Humberd** [just-jeb/angular-builders#356]
The plugin works great with normal applications, however it seems there is no support for replacing `@angular-devkit/build-ng-packagr:build`, which is used by Angular library project

**Comment by just-jeb** [comment]
Indeed there is no support for ng-packagr, it requires a separate builder.  
Not sure when I'll get to implement one but you're welcome to PR.

**Comment by arturovt** [comment]
@Humberd 

`ng-packagr` doesn't use Webpack. It uses Rollup at the last step to generate UMD bundles.

**Comment by antontemchenko** [comment]
There could be a wrapper builder created over ng-packagr, with extended options and copying assets like this one https://github.com/linnenschmidt/build-ng-packagr

**Comment by just-jeb** [comment]
Closing this one in favor of #508. Please continue the discussion there.
