### ISSUE TITLE
Cannot Figure Out How to Update Snapshots from Builder

### ISSUE THREAD

**Issue by jaredmahan** [just-jeb/angular-builders#404]
I am integrating jest with my angular 8 project and can't find the command to update the snapshots from within the optiosn of @angular-builders/jest. Is there currently a way to do this?

**Comment by just-jeb** [comment]
The builder supports all the Jest CLI options. You can either specify `updateSnapshot: true` in builder's options or run the test command with this flag: `ng test --updateSnapshot`.
