### ISSUE TITLE
The configuration property of target parameter in the indexTransform callback of the example project is empty

### ISSUE THREAD

**Issue by Franziskus1988** [just-jeb/angular-builders#433]
The configuration property of the target parameter in the indexTransform callback function of the example project in this repo [full-cycle-app](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack/examples/full-cycle-app) is empty.

**To Reproduce**
1. Grab latest version of the example project.
2. Run ng build.
3. Check index.html -> "Configuration: "

The configuration shouldn't be empty. Or do I have to define the configuration to pass into this function somewhere and if so, where do I have to do it?

**Comment by just-jeb** [comment]
If you don't specify the configuration then you don't get it in `indexTransform`. If you do specify it (by running `ng build --prod` or `ng build --configuration=yourconfig`) then it works as expected.
