### ISSUE TITLE
Code instrumentation in Angular 7?

### ISSUE THREAD

**Issue by basickarl** [just-jeb/angular-builders#438]
The documentation does not state anywhere how to instrument the code.

I'm trying to run e2e tests via Cypress and it requires that the code is instrumented. I write my files in TypeScript and then manually compile the files to Javascript where I then instrument the files. I'd like to then just bundle them but I can't seem to configure angular `ng build` without using the `ts-loader`.

Either that or I'd like some sort of configuration to instrument the code via `ng build` also. This can be done wit webpack via https://webpack.js.org/loaders/istanbul-instrumenter-loader/ but then I have to write my own builder. Fine I can do this, but then I need a webpack.config.js file to begin with to do this. And `ng eject` will not work now: `The 'eject' command has been disabled and will be removed completely in 8.0.`.

So. How do I instrument code in Angular 7? Is it possible?

**Comment by just-jeb** [comment]
You can use `@angular-builders/custom-webpack` builder to modify webpack configuration that `ng build` uses. In particular it will allow you to add any loader. So no need to write your own builder.
