### ISSUE TITLE
Support for WebStorm debugging

### ISSUE THREAD

**Issue by marcalj** [just-jeb/angular-builders#461]
**Is your feature request related to a problem? Please describe.**
Can't find a way to execute tests on WebStorm since it expects the ```jest.config.js``` file and I don't need it.

**Describe the solution you'd like**
Provide a solution to execute & debug jest unit tests in WebStorm.

**Describe alternatives you've considered**
Not found.

**Additional context**
None

**Comment by just-jeb** [comment]
You should be using `@angular/cli` as your Jest package. [This](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001785599-2018-3-Seems-to-Break-Jest-Running) and [this](https://github.com/just-jeb/angular-builders/issues/150) might be useful (contains some examples).  
Please let me know if it helps you and if yes please share your final configuration.

**Comment by marcalj** [comment]
Hmm maybe in the new WebStorm fixed the issue, it seems to be working now with a default configuration. Thanks! :)
