### ISSUE TITLE
watchOptions.ignored is not working with Custom Config

### ISSUE THREAD

**Issue by sdon2** [just-jeb/angular-builders#492]
I tried to add the following config to ignore watching files when using dev-server:

custom-webpack.config.js
```
module.exports = {
  watchOptions: {
    ignored: ["src/api/**/*.*"]
  }
}
```

angular.json
```
"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./custom-webpack.config.js",
              "replaceDuplicatePlugins": true
            },
          }
        }
}

.....
"serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
            "browserTarget": "angular-sample:build"
          },
```
**Expected behavior**
Need to ignore watching files inside src/api, but it's not working! Any help??

**Comment by sdon2** [comment]
Ok, I'm satisfied with following config:

custom-webpack.config.js

```
const webpack = require('webpack');

module.exports = {
  plugins: [
  new webpack.WatchIgnorePlugin([/.*\.php/])
  ]
}
```

**Comment by simeyla** [comment]
@saravanakumar-arumugam thanks for pointing this out. I had similar issues where I had some files I wanted compiled first time but not every time.

To anyone else finding this, note that the plugin takes a regex and not a string.

    https://webpack.js.org/plugins/watch-ignore-plugin/
