### ISSUE TITLE
jest builder doesn't appear to support build options with asset globs

### ISSUE THREAD

**Issue by abierbaum** [just-jeb/angular-builders#495]
**Describe the bug**

I updated from a working 7.x project to 8.x. In the process, I started seeing this error:

```
An unhandled exception occurred: Cannot convert object to primitive value
```

I think the issue is that given a builder configuration that has an asset option that has a list of glob objects, the OptionsConverter.convertToCliArgs method fails to detect and handle/skip this cases.

I have created a branch of the project that shows the error using the `multi-apps` example.  (note: it would also have the problem on a single app example IIUC)

**To Reproduce**

See: https://github.com/abierbaum/angular-builders/tree/bug_asset_globs

The relevant change is: https://github.com/abierbaum/angular-builders/commit/23eb0bc7f5a38683eb2b2f5f5ddf1e7571466255

What this shows it that I am using standard angular options in the builder.  This includes `assets` to reference files that are needed.  

I investigated the failure, and it is throwing the exception here: https://github.com/just-jeb/angular-builders/blob/master/packages/jest/src/options-converter.ts#L14

What appears to be happening is that runJest (https://github.com/just-jeb/angular-builders/blob/master/packages/jest/src/index.ts#L54) is attempting to convert all builder options from angular.json into command line arguments to pass to jest.  This includes angular related builder options that I think are still needed to put files into place for building the test code.  (note: I could be wrong on this and that may be the source of the issue)

**Expected behavior**

I would expect that the config as shown in the branch above would work since it is using standard angular cli options.

**Builder:**
 - @angular-builders/jest
 - 8.2.0

**Libraries**
 - `angular-devkit/build-angular`: 0.802.2

**Comment by just-jeb** [comment]
You are absolutely right on what happens, however this is the expected behavior. 
Unlike Karma builder Jest builder  does not need any of these options. The only thing it need is the Jest CLI options or a path to a config file. You can find the definition of options objects [here](https://github.com/just-jeb/angular-builders/blob/master/packages/jest/README.md#builder-options).  
The thing that really surprises me is that the original example somehow passes the build phase and doesn't throw the exception you mentioned.

**Comment by abierbaum** [comment]
@just-jeb Thanks for the quick reply.  I have confirmed that if I remove the assets options things keep running as normal.  I think the example should probably be updated to reflect the fact that all the options that used to be needed for karma aren't needed anymore with jest.

Thanks for the great project. Works great.

**Comment by just-jeb** [comment]
@abierbaum I totally agree with you. Would you like to create a PR?
