### ISSUE TITLE
Extended ng-packagr builder supporting assets

### ISSUE THREAD

**Issue by klemenoslaj** [just-jeb/angular-builders#508]
**Is your feature request related to a problem? Please describe.**
Angular CLI, or more specifically ng-packagr currently does not support bundling assets with libraries.

Corresponding issue in Angular CLI: https://github.com/angular/angular-cli/issues/11071

**Describe the solution you'd like**
We could extend the official `ng-packagr` builder to copy the assets. This should be quite simple.

In addition devs would have to of course configure application assets in angular.json to copy the library assets so they are accessible during the runtime of the application.

**Additional context**
I would love to create a PR with this new builder, since I already have it and I think it makes sense not to create a new package, but rather contribute here.

https://github.com/angular/angular-cli/issues/11071#issuecomment-531467088

**Comment by just-jeb** [comment]
Sounds like a great idea, go ahead with the PR!

**Comment by klemenoslaj** [comment]
@just-jeb, great, I will hopefully submit it some time tomorrow :+1:

**Comment by just-jeb** [comment]
Cool. Keep in mind though it should have at least unit test coverage and ideally e2e with an example app (just like the other builders).

**Comment by just-jeb** [comment]
@klemenoslaj Any updates?

**Comment by klemenoslaj** [comment]
@just-jeb, I am sorry, I got distracted lately. Life happened.
I will find some time during the weekend to finalize it. Is that ok with you?

**Comment by mario-d-s** [comment]
There is already https://github.com/linnenschmidt/build-ng-packagr which works fine for us.
Maybe it's better to try to collaborate with the creator to merge his solution with the angular-builders package?

**Comment by klemenoslaj** [comment]
> There is already https://github.com/linnenschmidt/build-ng-packagr which works fine for us.
> Maybe it's better to try to collaborate with the creator to merge his solution with the angular-builders package?

That to me sounds like a splendid idea as well :+1: @just-jeb, what do you think?

**Comment by just-jeb** [comment]
I think it's a great idea. Technically it should be pretty easy. We just need @linnenschmidt consent )))

**Comment by stephen-dirtcreative** [comment]
This appears to have stalled. Is there any progress?

**Comment by klemenoslaj** [comment]
@stephen-dirtcreative this has since been implemented into ng-packagr directly.

https://github.com/ng-packagr/ng-packagr/blob/master/docs/copy-assets.md

**Comment by blemaire** [comment]
@klemenoslaj I don't believe assets copying works in libraries...

**Comment by klemenoslaj** [comment]
> @klemenoslaj I don't believe assets copying works in libraries...

Please check the link I provided again.

```
{
  "ngPackage": {
    "assets": [ <-------- HERE
      "CHANGELOG.md",
      "./styles/**/*.theme.scss"
    ],
    "lib": {
      ...
    }
  }
}
```

**Comment by imnickvaughn** [comment]
hi @klemenoslaj ,

Do I use this like this?  Mine doesn't look like yours...

```
 "my-lib": {
            "projectType": "library",
            "root": "projects/geode-lib",
            "sourceRoot": "projects/geode-lib/src",
            "prefix": "lib",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-ng-packagr:build",
                    "options": {
                        "tsConfig": "projects/geode-lib/tsconfig.lib.json",
                        "project": "projects/geode-lib/ng-package.json"
                    },
                    "assets": [
                        "projects/my-lib/src/assets",
                    ]
                },
```

I have been following all these threads and 'ng serve' never gets mentioned.  My assets (image files) do not appear after I serve the application.  This solution would fix this right? or is this literally just for "ng build"?

**Comment by klemenoslaj** [comment]
@imnickvaughn `assets` should be added to `ng-package.json` or `package.json` (`ngPackage` field), not to `angular.json`.

That will copy the assets to the dist folder, but it will not do anything in terms of serving/building the application. For that you will have to configure `assets` for your application in `angular.json`, like

```JSON
{
  "glob": "**/*",
  "input": "./dist/library/assets",
  "output": "/assets/"
},
```

**Comment by imnickvaughn** [comment]
@klemenoslaj thank you for your reply and your work on this solution!  I've tried a few things but keep getting errors.

When I add:
    "ngPackage": {
        "assets": [
            "./assets/"
        ]
    },

to 

ng-package.json like this:
{
    "$schema": "../../node_modules/ng-packagr/ng-package.schema.json",
    "dest": "../../dist/geode-lib",
    "ngPackage": {
        "assets": [
            "./assets/"
        ]
    },
    "lib": {
        "entryFile": "src/public-api.ts"
    }
}
I get this pre-build squiggly warning on ngPackage:
"Property ngPackage is not allowed."
I get this error:
$ ng build geode-lib
Building Angular Package
ERROR: Configuration doesn't match the required schema.
Data path "" should NOT have additional properties (assets).
An unhandled exception occurred: Configuration doesn't match the required schema.
Data path "" should NOT have additional properties (assets).
See "C:\Users\a638553\AppData\Local\Temp\ng-l9IJx3\angular-errors.log" for further details.

**Comment by iursevla** [comment]
@imnickvaughn  did you solve your problem?

**Comment by eng-dibo** [comment]
any updates?
