### ISSUE TITLE
Cannot find module '...webpack.config.js'

### ISSUE THREAD

**Issue by yantrab** [just-jeb/angular-builders#517]
**Describe the bug**
```
An unhandled exception occurred: Cannot find module 'C:\Users\arkadiy\Desktop\customWebpack/webpack.config.js'
Require stack:
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular-builders\custom-webpack\dist\custom-webpack-builder.js
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular-builders\custom-webpack\dist\browser\index.js
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular-devkit\architect\node\index.js
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular\cli\models\architect-command.js
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular-devkit\schematics\tools\index.js
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular\cli\utilities\json-schema.js
- C:\Users\arkadiy\Desktop\customWebpack\node_modules\@angular\cli\models\command-runner.js

```
**To Reproduce**
1. Create app with ng n app
2. run npm i -D @angular-builders/custom-webpack
3. change builder to  "@angular-builders/custom-webpack:browser"

https://github.com/yantrab/custom-webpack

**Builder:**
 - The name of the builder browser
 - The version of the builder ???

**Libraries**
 - `angular-devkit/build-angular`: 8.2.0

**Comment by just-jeb** [comment]
You should specify the path, your options are wrong. Please read the [documentation] (https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/README.md#custom-webpack-config-object). You can also see a few examples in the examples folder or read a [Medium article](https://www.google.com/url?sa=t&source=web&rct=j&url=https://blog.angularindepth.com/customizing-angular-cli-build-an-alternative-to-ng-eject-v2-c655768b48cc&ved=2ahUKEwj1raP4refkAhXOsaQKHXcGC6gQjjgwDXoECAMQAQ&usg=AOvVaw2Eeg37ys2KLh2tk9rs-Zc1).
