### ISSUE TITLE
Use a webpack config file only for ng serve

### ISSUE THREAD

**Issue by ArielGueta** [just-jeb/angular-builders#609]
Thanks for this library. I'm trying to figure out how to run an extra webpack file only on `ng server/npm start`. ( I mean dev mode )

```json
"architect": {
  ...
  "build": {
    "builder": "@angular-builders/custom-webpack:browser"
    "options": {
      "customWebpackConfig": {
         path: "./extra-webpack.config.js"
      }
      ...
    } 
  },
  "serve": {
    "builder": "@angular-builders/custom-webpack:dev-server",
    "options": {
        "browserTarget": "my-project:build"
    }
  }
```

This works but it also runs when we run `ng build --prod`. How can I run it only on dev mode?

Thanks in advance.

**Comment by arturovt** [comment]
@ArielGueta 

Hey. You can export a function except of object and check for the `mode` property:
```js
// extra-webpack.config.js

module.exports = config => {
  // Skip if it's been run via `ng build --prod`
  if (config.mode === 'production') {
    return config;
  }

  // do this stuff if it hasnt' been run with `--prod`
  config.output.libraryTarget = 'umd';
  config.output.library = 'library-in-dev-mode';
  return config;
};
```

**Comment by ArielGueta** [comment]
Cool, thanks!

**Comment by just-jeb** [comment]
Thanks @arturovt , that's indeed one of the ways. However it won't work if the author will run `ng build` without the `--prod` flag. Here are other possible solutions: 
1. Duplicate the build configuration (call it, say, `my-build` in _angular.json_. Then you can specify this target as `browserTarget` in `serve` config. 
2. Add this config under `configurations` section in `build` target like this:
```js
"architect": {
  ...
  "build": {
    "builder": "@angular-builders/custom-webpack:browser"
    ...//rest of the options
   "configurations":  {
      "dev":  {
         "options": {
         "customWebpackConfig": {
            path: "./extra-webpack.config.js"
         }
      }
   }
      ...
    } 
  },
```
and then use it in `serve` config like this:
```js
  "serve": {
    "builder": "@angular-builders/custom-webpack:dev-server",
    "options": {
        "browserTarget": "my-project:build:dev"
    }
  }
```
Didn't try this one but it should work and it probably the cleanest solution.
