### ISSUE TITLE
Q: Custom webpack not called on test: /\.html$/. Any suggestions?

### ISSUE THREAD

**Issue by pamtbaau** [just-jeb/angular-builders#616]
I have a custom svg-loader that is supposed to replace `<svg><use href="path/to/svg"/></svg>`in html template files (e.g. app.component.html) with an inline svg definition.

The custom webpack file `extra-webpack config.js`  is being loaded and the loader itself is executed on all sorts of file types except for rule: `test: /\.html$/`

I noticed in a dump of the generated source of `app.component.ts`, that the html file is not `required` using standard `require()`, but by `require("!raw-loader!./app.component.html")`
 
I guess that is the reason why the rule `test: /\.html$/` is not being fired.

Question: How can I add a custom rule for html files?

**Comment by just-jeb** [comment]
Yeah, I guess you should disable direct template loading:
https://github.com/just-jeb/angular-builders/issues/417#issuecomment-516837663
https://github.com/just-jeb/angular-builders/issues/465#issuecomment-527021004

**Comment by pamtbaau** [comment]
Thanks for you swift response. I'll give your suggestions a try and ping back with feedback.

**Comment by pamtbaau** [comment]
It's working... SVG files are now perfectly inlined... Thanks for you quick response!

I used the custom webpack config from [#465](https://github.com/just-jeb/angular-builders/issues/465#issuecomment-527021004) and replaced:
```
config.module.rules.push(
    {
      test: /.pug$/,
      use: [
        { loader: 'apply-loader' },
        { loader: 'pug-loader' }
      ]
    }
  );
```

with:
```
config.module.rules.unshift(
    {
        test: /\.html$/,
        use: [
            {loader: 'raw-loader'},
            {
                loader: 'svgelement-loader',
                options: {
                    folder: path.resolve(__dirname, './src/assets/'),
                    action: (svg, match) => { return svg.replace(/\s*xmlns="[^"]*"/, '') }
                }
            }
        ]
    },
);
```
