### ISSUE TITLE
Support Angular 9 officially

### ISSUE THREAD

**Issue by just-jeb** [just-jeb/angular-builders#624]
As far as I know there are no breaking changes in Architect API in version 9 so @angular-builders v8.x.x should work with Angular 9 out of the box, but to officially support it we need to update the dependencies and run full regression cycle.

@angular-builders v9 should have architect and core as direct dependencies rather than peer dependencies.

**Comment by elvirdolic** [comment]
As I wrote in this  #16132 issue I was forced to change to default builder to run a prod build.

**Comment by just-jeb** [comment]
@elvirdolic yeah I saw, sorry to hear about that. Can you please create a small reproduction repo so that we'd have a test case for this?

**Comment by jeetparikh** [comment]
hey @elvirdolic had a similar issue just following the migration guide on the angular website which did not upgrade my architect, core and schematics to the release candidate version. Upgrading them to the latest release candidate version fixed this issue for me and builds ok with the `custom webpack 8.x` version.

**Comment by TekSiDoT** [comment]
Confirmed with 9.0.0-rc.4: Not having @angular-devkit/architect installed/upgraded specifically alongside your other packages will cause https://github.com/angular/angular-cli/issues/16132

**Comment by juanfran** [comment]
it doesn't work for us only in the SSR the other tasks work well. Reproduction repo https://github.com/juanfran/angular-9-ssr-custom-builder-issue
