### ISSUE TITLE
Q: SVG inline-loader not being called

### ISSUE THREAD

**Issue by bookluvr416** [just-jeb/angular-builders#631]
I'm using a webpack loader that will turn SVG urls (such as a background image in a css file) into inline SVG. I've tried two different libraries, and neither of them are being called in custom webpack.

I saw this question: https://github.com/just-jeb/angular-builders/issues/616 but it was regarding html. Any suggestions as to why my webpack loader isn't being called?

custom webpack:
``
module.exports = {
      module: {
          rules: [
              {
                  test: /\.svg/,
                  use: {
                      loader: 'url-loader'
                  }
              }
          ]
      }
  };
``
and also tried: 
``
module.exports = {
      module: {
          rules: [
              {
                  test: /\.svg/,
                  use: {
                      loader: 'svg-url-loader'
                  }
              }
          ]
      }
 };
``

**Comment by just-jeb** [comment]
Could you provide a reproduction repo please?

**Comment by arturovt** [comment]
This won't and shouldn't work since CLI uses `postcss-loader` under the hood to do any CSS processing. This is what I've found when googled _postcss svg_: https://github.com/TrySound/postcss-inline-svg

**Comment by arturovt** [comment]
Closing since the issue has been stale. As I mentioned this is not an issue in the core of this package but rather in a developer's webpack configuration.
