### ISSUE TITLE
Angular-cli 8.3.x, PostCSS - Add plugin

### ISSUE THREAD

**Issue by striky1** [just-jeb/angular-builders#634]
## Describe the Bug

It's not possible to add plugin of PostCSS to the `postcssPlugin` as native function from Angular Files.

## Minimal Reproduction

I tried several ideas from basic to crazy one and only this one "works":

```
// angular.json
{
  ..,
  projects: {
    name-of-project: {
      architect: {
        build: {
          builder: "@angular-builders/custom-webpack:browser",
          options: {
            customWebpackConfig: {
              path: "./extra-webpack.config.js",
              mergeStrategies: {
                "module.rules": "append"
              }
            }
          }
        ..
}
```

```
// extra-webpack.config.js

const postcssPlace = require('postcss-place');

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: 'postcss-loader',
            options: {
              ident: 'embedded',
              plugins: [
                postcssPlace()
              ]
            }
          }
        ]
      }
    ]
  }
};
```

MergeStrategy is set to `append`, so, we are expecting to preserve result from `postcssPlugin` as options with plugins for `postcss-loader` and append `postcssPlace()`. What happens? Seems that response from `postcssPlugin` is replaced with `postcssPlace()`.

## Expected Behavior

Option to extend result from `postcssPlugin` Angular function.

## Environment

<pre><code>
Libs
- @angular/core version: 8.2.14
- @angular-devkit/build-angular version: 0.803.20
- @angular-builders/custom-webpack version: 8.4.1

For Tooling issues:
- Node version: 10.17.0
- Platform:  macOS 10.14.6
</code></pre>

## Additional Context

I tried also crazy things like:

```
// extra-webpack.config.js

const postcssPlace = require('postcss-place');

module.exports = (config) => {
  Array.from(config.module.rules).forEach(rule => {
    if (`${rule.test}`.startsWith('/\\.css') && rule.include && rule.include.length) {
      rule.use[2].options.plugins = [...[postcssPlace()], ...rule.use[2].options.plugins()];
    } else if (`${rule.test}`.startsWith('/\\.css')) {
      rule.use[1].options.plugins = [...[postcssPlace()], ...rule.use[1].options.plugins()];
    }
  });

  return config;
};
```

with opposite order of plugins too or specific order like: 

```
postcss-import
postcss-cli-resources
postcss-place
autoprefixer
```
or

```
postcss-import
postcss-place
postcss-cli-resources
autoprefixer
```

and of course with mergeStrategy `prepend`/`replace`, nothing helps. 

There is no way how to do it or at least, I don't know how to do it.

Have someone idea how to do it, pls? Ty

**Comment by just-jeb** [comment]
@striky1 please see if #638 helps.

**Comment by just-jeb** [comment]
Closing for the same reasons as mentioned [here](https://github.com/angular/angular-cli/issues/8427#issuecomment-576234801).  
This builder provides a generic way to customize the underlying Webpack configuration, therefore providing first party option for PostCSS is not in the scope. As the OP stated there is a solution, although not very elegant.
