### ISSUE TITLE
Global mock for `window.matchMedia`

### ISSUE THREAD

**Issue by MaKCbIMKo** [just-jeb/angular-builders#641]
**Is your feature request related to a problem? Please describe.**
If you're using `@angular/flex-layout` package - jest tests will fail with missing `window.matchMedia` function. As this package is provided by angular team, it makes sense to have a global mock to support it + I don't see any problems with this mock even without using this package.

**Describe the solution you'd like**
I was thinking about adding mock function for `windod.matchMedia` into `global-mocks.ts`

**Describe alternatives you've considered**
Provide custom configuration for `setupFilesAfterEnv` (with mock for `windod.matchMedia`) which will be merged with `setupFilesAfterEnv` and extend global mocks.

**Additional context**
[Official jest documentation](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom) says about mocking not implemented functions and even provides example for `window.matchMedia`

I could provide a PR for this if you agree with proposed changes.

**Comment by just-jeb** [comment]
Makes sense, PR is most welcome.
