### ISSUE TITLE
jest: dom errors using npm link

### ISSUE THREAD

**Issue by matheo** [just-jeb/angular-builders#657]
## Describe the Bug

I have a **library** with utilities of `@ngneat/spectator` to facilitate the tests, and it runs ok if I install it from the registry to my Angular project.

But when I try to develop locally using it via `npm link`, something happens and test fails.
I've debugged the failure to these queries: `platformBrowser.By.css(directiveOrSelector) : platformBrowser.By.directive(directiveOrSelector))` (`@angular/platform-browser` returns empty matches with the symlinked lib).

Knowing that it's a `dom` issue, I've tried: `"testEnvironment": "jest-environment-jsdom-fourteen"` with no joy. I've removed all the npm dependencies and node_modules of my test **library**, and just left the js scripts. I'm sure that there's no npm crazyness involved.

Is it possible to configure something to `preserve-symlinks` or anything else to mitigate this kind of issue? Thanks in advance!

## Environment

<pre><code>
Libs
- @angular/core version: 7.2.16
- @angular-devkit/build-angular version: 0.13.9
- @angular-builders/jest: 7.4.4
- jest: 24.9.0

For Tooling issues:
- Node version: v10.18.0
- Platform: Latest Ubuntu

**Comment by matheo** [comment]
I've found that `npm` is the one resolving a dependency from a parent folder of the `npm link`ed library, instead of the dependency of the Angular project, great stuff... now I'm trying to test it with `yarn`.
Thanks for the great stuff!

**Comment by just-jeb** [comment]
Just FYI, preserve-symlinks somehow [worked](https://github.com/just-jeb/angular-builders/blob/1f5f484ea0dcbeb1a900fc0bc20b135963b003e0/packages/jest/examples/simple-app/package.json#L5) for me with `ng` in certain scenarios but eventually I stopped using `link` in any form because of multiple issues. Using a local npm registry instead.

**Comment by matheo** [comment]
Indeed @just-jeb , there can be some tricky stuff with `link`!

I've found that I've needed tho use this in my `jest` config:
```
"moduleDirectories": [
    "<rootDir>/node_modules",
    "node_modules"
],
```
so the linked libraries doesn't mess with the module resolution :)
