### ISSUE TITLE
How to use tsconfig.json paths alias

### ISSUE THREAD

**Issue by ryankauk** [just-jeb/angular-builders#658]
I'm probably missing something obvious, I can't seem to get the paths to work, I'm using your custom webpack package. From looking up I thought I just needed this:

```typescript
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');
```

but this doesn't seem to work.

Do you have any suggestions or direction on this? Thanks in advanced.

**Comment by just-jeb** [comment]
Not sure what you're looking for. If you're talking about `paths` property in tsconfig it works perfectly out of the box, you don't need custom webpack config for this.

**Comment by ryankauk** [comment]
Yea i know, I needed the custom webpack for other things, it has always worked for me out of the box I just feel since I don't know webpack that well I was missing a configuration from this side of things.

**Comment by just-jeb** [comment]
I see. Well, as long as you're not changing configuration of AngularCompilerPlugin the webpack configuration shouldn't affect the `paths`. In any case I'm gonna need more info in order to be able to help you with that. Mind providing a minimal reproduction?
