### ISSUE TITLE
custom-webpack: Cannot resolve relative paths in url() compile-time

### ISSUE THREAD

**Issue by cyrilfr** [just-jeb/angular-builders#660]
## Describe the Bug

The `url()` resolution doesn't work with relative paths at `build --prod`. It should be able to resolve the paths from the app source root at compile-time as it is correct at runtime (inline bundle).

## Minimal Reproduction

I the Angular project, I have a `src/variables.scss` file defining the assets:

```
$font-family-sans-serif: "Open Sans", sans-serif !default;
$font-family-cond:       "Open Sans Condensed", sans-serif !default;
$font-family-monospace:  monospace !default;

$primary: #CD2628;
$secondary: #727272;
$color-a: #CD2628; // red
$color-b: #727272; // dark gray
$color-c: #D0D0CE; // light gray
$color-d: white;   // ...
$color-e: #FF9900; // orange
$color-f: #00A627; // green
$color-g: #FAE9E9; // light red
$color-h: #286090; // blue

$translucent-a: rgba(0, 0, 0, 0.05); // black light
$translucent-b: rgba(0, 0, 0, 0.25); // black medium
$translucent-c: rgba(0, 0, 0, 0.85); // black dark
$translucent-d: rgba(78, 78, 78, 0.1); // gray
$translucent-e: rgba(255, 255, 255, 0.95); // white

$body-background-color: white;
$body-background-image: url('assets/images/bg-hexa-red-flat.png');
$body-background-position: top left;
$body-background-repeat: repeat;
```
then in my `src/app/components/sidepanel/sidepanel.component.scss` file it is imported:

    @import 'variables.scss';

    .sidepanel {
      background-color: $body-background-color;
      background-image: $body-background-image;
      background-position: $body-background-position;
      background-repeat: $body-background-repeat;
      font-family: $font-family-sans-serif;
    }

the import works because I set the `stylePreprocessorOptions` option in my `angular.json` file:

```
"architect": {
   "build": {
     "builder": "@angular-builders/custom-webpack:browser",
       "options": {
         "outputPath": "dist",
         "index": "src/index.html",
         "main": "src/main.ts",
         "polyfills": "src/polyfills.ts",
         "tsConfig": "src/tsconfig.app.json",
         "aot": false,
         "assets": [
           "src/assets"
         ],
         "styles": [
           "src/styles.scss"
         ],
         "stylePreprocessorOptions": {
           "includePaths": [
              "src"
           ]
         },
         "customWebpackConfig": {
           "path": "./angular.webpack.js"
         }
       }
       ...
```

My `angular.webpack.js` file uses a function to set the configuration to support Electron and TypeORM:

```
const path = require('path');

module.exports = (config, options) => {
  config.target = 'electron-renderer';
  if (options.customWebpackConfig.target) {
    config.target = options.customWebpackConfig.target;
  } else if (options.fileReplacements) {
    for (let fileReplacement of options.fileReplacements) {
      if (fileReplacement.replace !== 'src/environments/environment.ts') {
        continue;
      }
      let fileReplacementParts = fileReplacement['with'].split('.');
      if (['dev', 'prod', 'test', 'electron-renderer'].indexOf(fileReplacementParts[1]) < 0) {
        config.target = fileReplacementParts[1];
      }
      break;
    }
  }
  config.externals = {
    'typeorm': "require('typeorm')",
    'sqlite3': "require('sqlite3')",
    'react-native-sqlite-storage': 'react-native-sqlite-storage'
  };
  config.resolve = {
    alias: {
      typeorm: path.resolve(__dirname, '../node_modules/typeorm/typeorm-model-shim')
    }
  };
  return config;
}
```

## Expected Behavior

Pass the compile-time check of `url('assets/images/bg-hexa-red-flat.png');` relative to the app source root.

## Screenshots

![screen](https://i.ibb.co/GphfK0q/Screenshot-from-2020-01-15-10-06-40.png)

## Environment

Libs
- @angular/core: ~8.2.14
- @angular-devkit/build-angular: ^0.803.22
- @angular-builders/custom-webpack:  ^8.4.1

For Tooling issues:
- @angular/cli: ^8.3.22
- Platform:  Linux

## Additional Context

The project is based on [angular-electron](https://github.com/maximegris/angular-electron) starter.

**Comment by just-jeb** [comment]
Doubt it is the builder thing. Does the same import work with the default builder (without custom-webpack)?

**Comment by cyrilfr** [comment]
> Doubt it is the builder thing. Does the same import work with the default builder (without custom-webpack)?

Good point. No it doesn't. But it should?

**Comment by just-jeb** [comment]
It think it shouldn't. But it seems that you can [use an absolute path](https://github.com/angular/angular-cli/issues/12797) if this image is in assets array.  
Closing this one since it's not a builder issue, but please update here once you have a solution.

**Comment by cyrilfr** [comment]
Absolute path cannot be resolved in production with Electron. Absolute means absolute in the filesystem, which is not what's expected.

**Comment by cyrilfr** [comment]
I found [this solution](https://github.com/maximegris/angular-electron/issues/432#issuecomment-574672653) using a webpack alias.
