### ISSUE TITLE
 Could not find the implementation for builder @angular-builders/jest:run 

### ISSUE THREAD

**Issue by Dasradhvarma** [just-jeb/angular-builders#667]
I'm following the instruction from this article on howto use "Jest" with Angular ng test: https://codeburst.io/angular-6-ng-test-with-jest-in-3-minutes-b1fe5ed3417c

I see the same instructions in the README for the Jest Angular8 builder here: https://github.com/just-jeb/angular-builders/tree/master/packages/jest

I'm using Angular 8 with jest

When I run ng serve I get following error: 

An unhandled exception occurred: Could not find the implementation for builder @angular-builders/jest:run See "C:\Users\dasra\AppData\Local\Temp\ng-7VXCuQ\angular-errors.log" for further details.

[error] Error: Could not find the implementation for builder @angular-builders/jest:run at WorkspaceNodeModulesArchitectHost.resolveBuilder (C:\Users\dasra\OneDrive\Documents\Angular8_project\Angular8\node_modules@angular-devkit\architect\node\node-modules-architect-host.js:49:19) at ServeCommand.initialize (C:\Users\dasra\OneDrive\Documents\Angular8_project\Angular8\node_modules@angular\cli\models\architect-command.js:71:63) at async ServeCommand.validateAndRun (C:\Users\dasra\OneDrive\Documents\Angular8_project\Angular8\node_modules@angular\cli\models\command.js:124:9) at async Object.runCommand (C:\Users\dasra\OneDrive\Documents\Angular8_project\Angular8\node_modules@angular\cli\models\command-runner.js:186:24) at async default_1 (C:\Users\dasra\OneDrive\Documents\Angular8_project\Angular8\node_modules@angular\cli\lib\cli\index.js:54:31)

Versions are: + @angular-builders/jest@7.4.4 + jest@24.9.0 + @types/jest@24.9.0

Any suggestions how to fix this ...!!! Please Help me out trying this from week can't fix the error Thanks

My project : https://github.com/Dasradhvarma/Angular-8

**Comment by just-jeb** [comment]
You're using builder version 7 with Angular 8. You should be using the corresponding version of the builder (8).

**Comment by Dasradhvarma** [comment]
I updated the angular builders version compatible to Angular 8. When i run the application I'm getting another error : 
   File not found: <rootDir>/tsconfig.custom.json - I configured my my jest in package.json 

my Package.json : {
  "name": "Angular8",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build ",
    "test": "jest",
    "test:ci": "jest -i",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "test:coverage": "jest --coverage"
  },
  "private": true,
  "jest": {
    "verbose": true,
    "preset": "jest-preset-angular",
    "globals": {
      "ts-jest": {
        "diagnostics": false,
        "allowSyntheticDefaultsImports": true,
        "tsConfig": "<rootDir>/tsconfig.custom.json",
        "stringifyContentPathRegex": "\\.html$",
        "astTransformers": [
          "jest-preset-angular/build/InlineFilesTransformer.js",
          "jest-preset-angular/build/StripStylesTransformer"
        ],
        "testPathIgnorePatterns": [
          "<rootDir>/node_modules/",
          "<rootDir>/src/test.ts/",
          "<rootDir>/dist/"
        ]
      }
    },
    "setupFilesAfterEnv": [
      "<rootDir>/setupJest.ts"
    ]
  },
  "dependencies": {
    "@angular/animations": "~8.2.14",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.14",
    "@angular/compiler": "~8.2.14",
    "@angular/forms": "~8.2.14",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "~8.2.14",
    "@angular/platform-browser-dynamic": "~8.2.14",
    "@angular/router": "~8.2.14",
    "bootstrap": "^3.4.1",
    "jest-environment-jsdom-fourteen": "^1.0.1",
    "rxjs": "~6.4.0",
    "ts-jest": "^24.3.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-builders/jest": "^8.0.2",
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular/cli": "^8.3.23",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/jest": "^24.9.0",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.1",
    "core-js": "^3.6.4",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jest": "^24.9.0",
    "jest-preset-angular": "^8.0.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "^3.5.3"
  }
}

My- ts-config .json :+1: 
{
  "compileOnSave": true,
  "compilerOptions": {
    "baseUrl": "src",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es5",
    "lib": ["esnext", "dom"],
    "types": ["jest"],
    "typeRoots": ["./node_modules/@types"]
  },
  "include": ["src/**/*.ts/"],
  "exclude": ["node_modules", "wwwroot/lib", "dist"],
"angularCompilerOptions": {
"fullTemplateTypeCheck": true,
"strictInjectionParameters": true
}
}

My project : https://github.com/Dasradhvarma/Angular-8 

Please let me know where i'm doing mistake

**Comment by just-jeb** [comment]
You shouldn't be defining `ts-jest` options in your `package.json`, the builder does that for you. If you want to use custom tsconfig you should pass `tsConfig` [option](https://github.com/just-jeb/angular-builders/tree/master/packages/jest#builder-options) to the builder.  
You can use [this](https://github.com/just-jeb/angular-builders/blob/master/packages/jest/examples/multiple-apps/angular.json) example app as a reference.
