### ISSUE TITLE
Getting environment info in customWebpackConfig.

### ISSUE THREAD

**Issue by at-vinguyen** [just-jeb/angular-builders#681]
**Environment info**
Is it possible to get the specific environment info in the `customWebpackConfig`, for example:
- We run `ng build -c staging`, the data we got is which we defined in `environment.staging.ts`
- We run `ng build -c production`, the data we got is which we defined in `environment.production.ts`

**Comment by just-jeb** [comment]
I think you're trying to use the wrong tools. What exactly you're trying to achieve?  
If you want different configuration for webpack according to the config flag then you should be using Angular CLI configurations (and different webpack configs).  
If you just want to know what is the configuration you're building with then yes, you get all the build options (configuration is among them) in [webpack config function](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-function) as a second parameter.  
Could you please elaborate on your use case?

**Comment by MJomaa** [comment]
Same thing here but for a different cause.

I have a web app that can be also bundled as an electron app. For this I've added an additional environment configuration called "electron" that does some file replacements, adds custom loaders for native node-modules and sets the target to "electron-renderer". 

It would be a blessing if I could use
```
if (opts.environment !== 'electron') {
    return cfg;
}
```
in the custom webpack config to avoid those in the regular web app.

**Comment by just-jeb** [comment]
OK, I was under impression that the target configuration is available within the custom webpack config function but in fact it is not. I have an explicit [TODO](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/common.ts#L17) for this.  
I'm going to create a feature request to add this, but I still think that what you're trying to achieve is doable with just Angular CLI configs. Still need more details on your use case.

**Comment by at-vinguyen** [comment]
Thank you for your response. Now I try another way and my problem is solved. But I would like to share with you my use case.
I have to build the app in 3 environments and what I need to do is passing the configurations (`environment*.ts`) into `index.html`, for example:
 - Google Tag Manager (without using service)
 - Change the title to identify each env
  For local: **[Local] Nice App**
  For dev: **[Dev] Nice App**
  For stg: **[Stg] Nice App**
  For Prod: **Nice App**
 - And some more metadata ...

I will happy to hear your solution to this.

**Comment by just-jeb** [comment]
That's exactly what [`indexTransform`](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/README.md#index-transform) is for. 
You can have a map from config to  metadata in `index-transform.js` and based on target configuration modify your `index.html`.

**Comment by at-vinguyen** [comment]
Yeap, `indexTransform` is my solution. I understand your recommendation but I tried to put all configs in `environment*.ts` files that help to manage the application easily.
This is my index-transform.ts file
```ts
module.exports = (targetOptions, indexHtml) => {
  if (targetOptions.configuration === 'production') {
    targetOptions.configuration = 'prod';
  }
  const envSubPath = targetOptions.configuration ? `.${targetOptions.configuration}` : '';
  const environment = require(`./src/environments/environment${envSubPath}.ts`).environment;
  indexHtml = indexHtml.replace(/<%= gtagCode %>/g, environment.gtagCode);
  indexHtml = indexHtml.replace(/<%= appName %>/g, environment.appName);
  return indexHtml;
};
```
In this case, the error will happen if using `indexTransform` without `customWebpackConfig`.
To fix it, use a trick by adding `extra-webpack-config.ts` with no content.
```json
"customWebpackConfig": {
  "path": "extra-webpack.config.ts"
},
"indexTransform": "index-transform.ts",
```

**Comment by just-jeb** [comment]
You shouldn't experience any error if not provided `customWebpackConfig`. It should just [use the basic Angular CLI config](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/custom-webpack-builder.ts#L22).  
What is the error you get?

**Comment by at-vinguyen** [comment]
This error caused by loading `environment.ts` file in `index-transform.ts`
![image](https://user-images.githubusercontent.com/15604319/74846001-62efbb00-5362-11ea-8caf-eed3a1a5fb71.png)

**Comment by just-jeb** [comment]
Ok ok, I know what the problem is. You use `index-transform.ts` instead of `index-transform.js` and it is not supported. The trick you did causes webpack builder to [register TS compiler](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/custom-webpack-builder.ts#L57) for `customWebpackConfig` (in which TS is supported) and the side-effect is that you can also load your `index-transform.ts`.  
Would you mind opening a feature request to support TS for `indexTransform`?  
PR is also welcome btw, it should be very small.

**Comment by at-vinguyen** [comment]
You know exactly what happened to me and what I did to solve the problem.
Support TS for `indexTransform` is another case and of course, that is needed too.
When I create this issue my expectation is to able to get the environment info of the target configuration.

**Comment by just-jeb** [comment]
I understand that, this is exactly why I asked you to create another issue (since you're the one that discovered the problem). But if you're not up to it, it's OK I'll do that.  
As far as I can see this specific issue is resolved, correct? You do get the target configuration in `indexTransform`.

**Comment by at-vinguyen** [comment]
In short, we need to improve two things:
1. Get the target configuration in the `custom webpack config` (issue already raised by you)
2. Support TS for `index Transform` (I will create a new issue for that)
BTW, thank you for your time.

**Comment by just-jeb** [comment]
Unfortunately execution order is hardcoded within Angular CLI.
