### ISSUE TITLE
Documentation: README says Angular 8, package depends on 9

### ISSUE THREAD

**Issue by tommck** [just-jeb/angular-builders#682]
[couldn't decide if this was a bug or feature request]

**Is your feature request related to a problem? Please describe.**
The current READMEs say that this supports Angular 8, but the package code depends on 9.x RCs.

**Describe the solution you'd like**
I think the README we see and the code we see should be in sync.

**Describe alternatives you've considered**
If you're trying to keep the README locked at a specific version, consider doing 9.0 RC work in a branch instead and mentioning that ongoing development is happening there in the README

**Comment by just-jeb** [comment]
Yes, you're 100% right, it should be up to date, just didn't get to update it. 
Just FYI all the previous major versions have branches of their own and master is the development branch, so this version of README should be updated to reflect the reality ))). 
The READMEs in versions branches should be updated with correct URLs as well.

**Comment by marcalj** [comment]
Just checking, is this package ready for Angular v9?

**Comment by just-jeb** [comment]
Yes, for now you should use the `next` tag, official release will be later this week.  
You can safely use the beta release though since there are no planned changes for the official release, it's just semantics.
