### ISSUE TITLE
Support app-shell with custom-webpack

### ISSUE THREAD

**Issue by tommck** [just-jeb/angular-builders#690]
**Is your feature request related to a problem? Please describe.**
I am using an app shell (`ng g app-shell`) and there is no support for custom-webpack stuff

**Describe the solution you'd like**
I'd like it supported :)

**Describe alternatives you've considered**
Crying over a beer

**Comment by just-jeb** [comment]
App Shell builder just [invokes](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/app-shell/index.ts#L148) `browser` and `server` targets, which do support `customWebpackConfig`. So it's enough to specify custom  webpack configs in these targets and you should be fine.  
LMK if you're still in trouble.

**Comment by tommck** [comment]
Yep, that was it.. I added the app shell after I added custom-webpack stuff, so I had to add the custom webpack stuff to the ":server" entry as well.

Thanks for the quick response @just-jeb
