### ISSUE TITLE
done is not a function in jest-preset-angular 8.0.0

### ISSUE THREAD

**Issue by jankeesvanandel** [just-jeb/angular-builders#697]
## Describe the Bug

I get "done is not a function" errors when I pass in a done callback. This is caused by the following bug in jest-preset-angular: https://github.com/thymikee/jest-preset-angular/pull/357

I upgraded my local version of jest-preset-angular, but @angular-builders/jest is still using the 8.0.0 version, which has the issue.

I replaced the node_modules/@angular-builders/jest/node_modules/jest-preset-angular with the new 8.1.2 version and with that version everything works, but I have no "proper" way to override the dependency version.

Could you please upgrade to 8.1.2?

## Environment

<pre><code>
Libs
- @angular/core version: 9.0.4
- @angular-devkit/build-angular version: ~0.900.4
- @angular-builders/jest version: 9.0.0

For Tooling issues:
- Node version: v13.8.0
- Platform:  Mac

**Comment by just-jeb** [comment]
Sure. Would you like to make a PR?

**Comment by jankeesvanandel** [comment]
done! https://github.com/just-jeb/angular-builders/pull/698

**Comment by just-jeb** [comment]
The fix should be available in the next beta build within a few minutes (I think it should be `@angular-builders/jest@9.0.2-beta`.

**Comment by just-jeb** [comment]
Update: it's fixed in `@angular-builders/jest@9.0.1-beta.1`

**Comment by jankeesvanandel** [comment]
Awesome! Thanks for the quick action!
