### ISSUE TITLE
Can't use custom-webpack:dev-server with angular 9.1.0

### ISSUE THREAD

**Issue by kamilchlebek** [just-jeb/angular-builders#708]
## Describe the Bug

- builder is set to `@angular-builders/custom-webpack:dev-server`

Running `ng serve` ends up with message:
> ERROR in Cannot read property 'flags' of undefined

After debugging `ng serve` I can see it comes from method `checkUnreachable` inside typescript internals. It throws an exception while parsing `node_modules/@angular-builders/custom-webpack/node_modules/typescript/lib/typescript.js`

My guess it's because of `@angular-devkit` version mismatch after upgrading to 9.1.0.

- Deleting directory `node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit` fixes the issue - forces node to use `@angular-devkit` from `node_modules`

- Switching to default builder fixes the issue

## Minimal Reproduction

https://github.com/kamilchlebek/angular-builders-issue-demo

Steps: 
1. `ng serve` :arrow_right:  error

## Expected Behavior

`ng serve` finishes successfully. 

## Environment

<pre><code>Angular CLI: 9.1.0
Node: 10.16.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
@angular-builders                 9.0.0

**Comment by just-jeb** [comment]
Yep, version mismatch is the root cause. Trying to find the best solution for this, thank you for such a well documented issue.

**Comment by just-jeb** [comment]
Should be fixed in `v9.1.0-beta.1`. Please update me if helped.

**Comment by faizplus** [comment]
Thanks @just-jeb for this quick fix. It is working with `v9.1.0-beta.1`

**Comment by kamilchlebek** [comment]
Thank you @just-jeb. It's good with `v9.1.0-beta.1`
