### ISSUE TITLE
Angular v9 localize option causes error

### ISSUE THREAD

**Issue by julmot** [just-jeb/angular-builders#713]
## Describe the Bug

Currently I have a separate build per language. In Angular v9 it should be possible to have one build generating multiple language outputs.

Therefore I have added an `i18n` configuration as child of my project configuration in `angular.json`, like described in the documentation:

```json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "my-project": {
      "i18n": {
        "sourceLocale": "en-US",
        "locales": {
          "de": "src/locale/messages.de.xlf",
          "fr": "src/locale/messages.fr.xlf",
          "it": "src/locale/messages.it.xlf"
        }
      }
      // ....
    }
  }
}
```

Then I've specified `"localize": true` within "architect" => "build" => "options". 

When running `ng build --configuration=production` this causes an error:

```text
Schema validation failed with the following errors:
  Data path "" should NOT have additional properties(localize).
```

Removing that `localize` property and instead running the build using the `localize` flag causes also an error:

```text
Unknown option: '--localize'
```

However, according to the [Angular docs](https://angular.io/guide/i18n#merge-the-completed-translation-file-into-the-app) this should be valid.

After switching back from `@angular-builders/custom-webpack` to `@angular-devkit/build-angular` the error disappeared and the build ran through (of course custom config doesn't work then). So I expect it to be a problem of this project.

## Minimal Reproduction

I'm working on that...

## Expected Behavior

Using `--localize` on the command line or `"localize": true` in angular.json should not trigger errors.

## Environment

<pre><code>
Libs
- @angular/core version: ~9.1.0
- @angular-devkit/build-angular version: ~0.901.0
- @angular-builders/custom-webpack version: ^8.4.1

**Comment by just-jeb** [comment]
You're with outdated version of `@angular-builders/custom-webpack`, please use version 9.  
The best for you is to use `9.1.0-beta.2` since it contains some crucial fixes for `devkit` versions mismatch.

**Comment by julmot** [comment]
@just-jeb Gotcha, thanks!

I'm just curious why running `$ ng update` says:

```
We analyzed your package.json and everything seems to be in order. Good work!
```

... if the custom-webpack package has actually a new version released.

**Comment by just-jeb** [comment]
`custom-webpack` is not an official Angular package, therefore `ng update` doesn't check its version.
