### ISSUE TITLE
Fails compilation in scss files

### ISSUE THREAD

**Issue by gquinteros93** [just-jeb/angular-builders#716]
## Describe the Bug

I am using [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/blob/8.x.x/packages/custom-webpack/README.md) to extend the compilation of the ```scss``` files in order to use [postcss]( https://postcss.org/) and the plugin [postcss-modules](https://github.com/css-modules/postcss-modules)

Currently, when I try to serve the project these errors are displayed in the terminal:

![image](https://user-images.githubusercontent.com/53574912/78562861-6b0b9900-77f0-11ea-8a54-d0dde4bbdb42.png)

I think the issue is the ```component.scss``` files are being compiled twice, one for the default compiler and the other one by my custom webpack config: ```extra-webpack.config.js```.

## Minimal Reproduction
Here is my project: https://github.com/gquinteros93/angular-css-modules

## Expected Behavior

I expect my ```scss``` files will be compiled with my custom webpack rule.

## Environment

<pre><code>
Libs
- @angular/core version: 8.2.0
- @angular-devkit/build-angular version: 0.803.24
- @angular-builders/custom-webpack": "8.2.0"
- @angular-builders/dev-server": "7.3.1"

For Tooling issues:
- Node version: v10.9.0
- Platform:  Mac

**Comment by just-jeb** [comment]
I don't think there is a problem with the builder. More likely it's a problem with your configuration.
Modifying `postcss` rules is tricky but possible. Please refer to [this](https://github.com/angular/angular-cli/issues/8427) thread and the two threads mentioned in [this](https://github.com/angular/angular-cli/issues/8427#issuecomment-576234801) comment.  
It should cover pretty much everything you're gonna need for modifying your `postcss` rules.  

Please update me once you have a solution.

**Comment by just-jeb** [comment]
Also, you don't need `@angular-builders/dev-server` anymore, you should be using `@angular-builders/custom-webpack:serve` builder instead.

**Comment by gquinteros93** [comment]
Hi @just-jeb , thanks for your response.

I will see the links you provide me to understand how to extend postcss plugins. 

About using ```@angular-builders/custom-webpack:serve```  instead of  ```@angular-builders/dev-server```, if I change ```@angular-builders/dev-server```:

![image](https://user-images.githubusercontent.com/53574912/78568379-677c1000-77f8-11ea-9842-cfb31e48f0ac.png)

By ```@angular-builders/custom-webpack:serve```:

![image](https://user-images.githubusercontent.com/53574912/78568895-2801f380-77f9-11ea-84ef-a2e1edeb13da.png)

I got the following error:

![image](https://user-images.githubusercontent.com/53574912/78568924-35b77900-77f9-11ea-9dab-2ac8fbe86e92.png)

**Comment by gquinteros93** [comment]
Hi @just-jeb , thanks for you help, I follow the same approach as: https://github.com/angular/angular-cli/issues/8427#issuecomment-576263052

And I was able to extend postcss 🎉  :  ```extra-webpack.config.js``` : 

```
const postcssModules = require('postcss-modules');

module.exports = (config, options) => {

    const scssRule = config.module.rules.find(x => x.test.toString().includes('scss'));
    const postcssLoader = scssRule.use.find(x => x.loader === 'postcss-loader');
    const pluginFunc = postcssLoader.options.plugins;
    const newPluginFunc = function () {
        var plugs = pluginFunc.apply(this, arguments);
        plugs.splice(plugs.length - 1, 0, postcssModules({ generateScopedName: "[hash:base64:5]" }));
        return plugs;
    }
    postcssLoader.options.plugins = newPluginFunc;

    return config;
};
``` 

Now I need to extend [posthtml](https://github.com/posthtml/posthtml) in order to use [posthtml-css-modules](https://github.com/posthtml/posthtml-css-modules) to replace the classes names by their corresponding hashed names.

I will research if it possible but If you already know or have an idea about how to do it, it's more than welcome.

Thanks!!!

**Comment by gquinteros93** [comment]
Hi @just-jeb , I was able to use [posthtml-css-modules](https://github.com/posthtml/posthtml-css-modules) with this comment on a previous issue: 

https://github.com/just-jeb/angular-builders/issues/465#issuecomment-527021004

Later I will add here my custom-wepback.config with the HTML rules.

Thanks for your support and congratulations for the library, it's really useful 👏 .

P/d: you can close this issue 😄

**Comment by just-jeb** [comment]
@gquinteros93 
> I got the following error:
Yeah sorry I mislead you. You need to use `@angular-builders/custom-webpack:dev-server`. In any case `@angular-builders/dev-server` is deprecated.
