### ISSUE TITLE
After updating to Angular and Angular CLI 9.1.1 and using custom-webpack 9.1.0, significant pieces of webpack aren't properly loaded

### ISSUE THREAD

**Issue by hamfastgamgee** [just-jeb/angular-builders#719]
I tried to update our project to Angular CLI 9.1.1 while using custom-webpack version 9.1.0.  Unfortunately, this appears to break automatic dependency resolution in npm for webpack and many of the dependencies/plugins.  For example, I then had to manually add devDependencies for webpack itself, webpack-dev-server, autoprefixer, file-loader, raw-loader, sass-loader, and style-loader.

Angular CLI 9.1.1 had to do a rollback to use Typescript 3.6.5 in the build optimizer due to bugs in Typescript.  Guessing this may be somehow related.  (It also broke my code which was already using the safe navigation [Elvis] operator because the tests were accidentally using Typescript 3.6.5 instead of 3.8.3, but that's Angular's issue and not related to this project. :) )

Suffice it to say, instead of proceeding forward, I rolled back to Angular 9.0.7 and custom-webpack 9.0.0 for the moment.

**Comment by hamfastgamgee** [comment]
Curiously, I just tried with 9.2.0-beta.0, and now I'm completely fine.  So one of the dependencies upgraded in the beta release must have cleared some sort of npm confusion?

**Comment by just-jeb** [comment]
I guess so. FYI `9.2.0` is a release now.
