### ISSUE TITLE
Differential loading with es5 support enabled doesn't inject es5 bundles in the extra html files generated through @angular-builders/custom-webpack

### ISSUE THREAD

**Issue by Balaji-Arulvanan** [just-jeb/angular-builders#723]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

 A clear and concise description of the problem...
Recently we updated our project to Angular9.1.0 from Angularv7.3.8. 
We use @angular-builders/custom-webpack to generate index files for higher environments. After migration, i enabled Differential loading with es5 support enabled(With browserslist for IE11).
After build, i can see that the generated htmls through custom webpack builder doesn't have es5 builds injected in it. It has all the es2015 bundles and polyfills-es5. Since it doesn't have other es bundles in it, it will fail in IE. 

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-kzvnyl

## 🌍 Your Environment
Angular cli 9.1.1
Nod 10.15.3
Os: Win32

"@angular/animations": "^9.1.0",
"@angular/common": "^9.1.0",
"@angular/compiler": "^9.1.0",
"@angular/core": "^9.1.0",
"@angular/forms": "^9.1.0",
"@angular/platform-browser": "^9.1.0",
"@angular/platform-browser-dynamic": "^9.1.0",
"@angular/platform-server": "^9.1.0",
"@angular/router": "^9.1.0",
"@angular/cli": "^9.1.0",
"@angular/compiler-cli": "^9.1.0",
"@angular/language-service": "^9.1.0",
"@angular-builders/custom-webpack": "^9.0.0",
"@angular-builders/dev-server": "^7.3.1",
"@angular-devkit/build-angular": "~0.901.0",

**Comment by just-jeb** [comment]
Have you been following the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD)? In particular [index.html](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) part?

**Comment by Balaji-Arulvanan** [comment]
hey @just-jeb 
We use custom webpack builder to generate other index files for higher environments using HtmlWebpackPlugin in extra-webpack.config.js from CustomWebpackConfig. Something like index-stage.html,index-dev.html using sample code

var htmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
    plugins: [
       new htmlWebpackPlugin({
           filename: 'index-dev.html',
           chunks: ['a,'b','c']
       }),
    new htmlWebpackPlugin({
           filename: 'index-prod.html',
           chunks:['a,'b'],
           excludechunks:['c']
       })
    ]
}

Till angular 7 we had all the chunk injected through this way. Since angular 8+ after enabling diff loading, index-dev.html has es2015 bundles and polyfills-es5. It doesn't have other es5 bundles. I think it will help if we can adopt differential loading when html files are created in this way. What do you think?

**Comment by just-jeb** [comment]
With differential loading there are two processes running one after another - first is a [webpack build](https://github.com/angular/angular-cli/blob/9.1.x/packages/angular_devkit/build_angular/src/browser/index.ts#L260) for `es2015` bundles and another is a post-process that [generates](https://github.com/angular/angular-cli/blob/9.1.x/packages/angular_devkit/build_angular/src/browser/index.ts#L463) `es5` bundles out  of the `es2015` bundles.  
Obviously, `HtmlWebpackPlugin` is applied only to the Webpack build, this is why you don't get the `es5` bundles in your `index-dev.html`.  
`index.html` is [generated](https://github.com/angular/angular-cli/blob/9.1.x/packages/angular_devkit/build_angular/src/browser/index.ts#L712) later on after both build steps are completed.
The solution to your problem would be using [`indexTransform`](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/README.md#index-transform) as I mentioned earlier. It receives `index.html` content and returns the modified one, but no one prevents you from generating additional `.html` files during the transformation.

**Comment by Balaji-Arulvanan** [comment]
I can use `IndexTransform` to add new html files. But it receives the content from `index.html`. What if i wanted to generate the files using a custom template through `HtmlWebpackPlugin` and inject only required bundles removing few extra ones in the `index.html`

It looks like going forward we will have to use custom index transform instead of using the angular builders. 

Since we don't have a option to create multiple index files, we made use of this builder. After angular 9+, we need to look into diffeent solution then. 

Thanks @just-jeb for the info.

**Comment by Balaji-Arulvanan** [comment]
#632 Looks like this issue seems to be there when we use other plugins as well.

**Comment by just-jeb** [comment]
I'm not sure what is the problem with using `indexTransform`:
1. You won't have Webpack build for `es5` bundles - not anymore, so you won't be able to use Webpack plugins to alter `es5` bundles nor to generate custom `.html` that contains them - from the Webpack perspective these files simply do not exist.
2. `index.html` contains *all* the files in `script` tags, including `es5` bundles. What prevents you from parsing the `index.html`, leaving just the tags you want and saving it as another `custom-index.html`?

**Comment by Balaji-Arulvanan** [comment]
@just-jeb I get it. This makes the custom-webpack builder as not useful anymore when we use differential loading. Anyway, moving on to IndecTransform then.

**Comment by just-jeb** [comment]
Just to clarify - `indexTransform` is an option in `custom-webpack` builder.

**Comment by arbali12** [comment]
My bad...didn't notice it :p
