### ISSUE TITLE
Replace experimental.workspace with context.getProjectMetadata

### ISSUE THREAD

**Issue by just-jeb** [just-jeb/angular-builders#731]
Usages of `experimental.workspace` from  ` '@angular-devkit/core'` can be replaced by [`context.getProjectMetadata`](https://github.com/angular/angular-cli/blob/e70a2b04bd6bcc545e8f994601acecd75d0c6084/packages/angular_devkit/architect/node/node-modules-architect-host.ts#L127)

**Comment by arturovt** [comment]
Not using `experimental` object.
