### ISSUE TITLE
Production config ignored when running ng serve --prod

### ISSUE THREAD

**Issue by EvtK** [just-jeb/angular-builders#736]
## Describe the Bug

I'm using the angular-builders to set some extra webpack config. Great plugin. Now I stubbled upon a nasty issue. When having **@angular-builders/custom-webpack:browser** configured as builder for build target and **@angular-builders/custom-webpack:dev-server** as builder for serve target, I notice that the production configuration provided in the build target is ignored when running serve with the production flag. As an example I'm looking at the namedChunk = false config, which can be easily be tracked for working or not working.

## Minimal Reproduction

Here is (partially) my config:

```
"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
              <..removed..>
            },
          "configurations": {
            "production": {
                 "namedChunks": false,
            },

"serve": {
          "builder": "@angular-builders/custom-webpack:dev-server",
          "options": {
               <... removed >
          },
          "configurations": {
            "production": {
              "browserTarget": "my-app:build:production"
            }
          }
```

now, when running ng serve --prod, I would expect it to take the production configuration from the build target and therefore make sure my chunks are not named. Though this option is ignored and I do get named chunks.

When I switch the '@angular-builders/custom-webpack' back to the angular default: '@angular-devkit/build-angular', i do not get named chunks which should be expected. 

## Expected Behavior

I expect the custom-webpack builder to respect and take the provided configurations.

## Environment

<pre><code>
Libs
- @angular/core version: 9.1.0
- @angular-devkit/build-angular version: 0.901.0
- @angular-builders/custom-webpack version: 9.1.0 (tried with beta version already)

For Tooling issues:
- Node version: 10.16.3
- Platform: Mac

**Comment by just-jeb** [comment]
Interesting. Could you please create a simple reproduction repo in order to speed up the investigation?

**Comment by EvtK** [comment]
yes well do ASAP.

**Comment by EvtK** [comment]
I I have started a clean repo on angular 9.1 and could not reproduce it right away. So I went back to my current repo where I have the issue (sorry cannot share it, corporate code), and investigated some more. I came across this file that is used in the custom webpack builder:

https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/dev-server/index.ts

 I discovered that putting a console.log on line 146, printing the number of plugins
`    console.log('PLUGINS COUNT', webpackConfig.plugins.length)
`

with running the custom webpack builder this will give me 13, running the default angular builder this will give me 11. And yes, with the custom webpack builder one of these extra plugins is the 'NamedLazyChunksPlugin'.

I'm bazzled, will definitly investigate further, but any directions on this are greatly appreciated!

**Comment by just-jeb** [comment]
Any chance #422 is related?

**Comment by EvtK** [comment]
yeah definitly, I loose three options on the second run of getTargetOptions. I read into the other issues as well, but I can confirm that angular 9 hasn't solved it!

**Comment by just-jeb** [comment]
Maybe it's worth to comment on the Angular CLI issue to check up on it.

**Comment by EvtK** [comment]
w00haa...

After I updated to these versions:

    "@angular-devkit/build-angular": "0.901.6",
    "@angular/cli": "9.1.6",

issue is gone!

**Comment by just-jeb** [comment]
Does this mean I can close the #422 as well?

**Comment by EvtK** [comment]
I guess so, but I haven't tested their scenario's.
