### ISSUE TITLE
splitChunks scripts not added in html

### ISSUE THREAD

**Issue by ranaictiu** [just-jeb/angular-builders#738]
## Describe the Bug

When optimisation/splitChunks settings applied the scripts files get split properly but the scripts tags don't get added in index.html file. 
<pre>
<code>
optimization: {
    minimize: true,
    removeEmptyChunks: false,
    mergeDuplicateChunks: false,
    splitChunks: {
      minSize: 0,
      maxSize: 4500000,
      minChunks: 1,
      automaticNameDelimiter: '-',
      hidePathInfo: true
    }
  }
</code>
</pre>

## Minimal Reproduction

- Cone this repo [https://github.com/ranaictiu/angular-builders/tree/master/packages/custom-webpack/examples/full-cycle-app](https://github.com/ranaictiu/angular-builders/tree/master/packages/custom-webpack/examples/full-cycle-app)
- run ng build

You will find the script fiels are generated in output folder but the index.html missing the required <script> tags.

## Expected Behavior
As the script files get split into multiple, the files should be referenced in html file

## Environment

<pre><code>
Libs
- @angular/core version: 9.0.0
- @angular-devkit/build-angular version: >=0.900.0 < 0.1000.0
- @angular-builders/{the name of the builder} version: 9.1.0

For Tooling issues:
- Node version: 12.16.2
- Platform:  Windows

**Comment by just-jeb** [comment]
That's interesting. When I run `ng serve` they are added. With `ng build` they are not.  
![image](https://user-images.githubusercontent.com/9823087/82534586-0d3bd200-9b4e-11ea-88a1-df924a22cfc9.png)

Need to dig into Angular CLI code see why it happens.

**Comment by just-jeb** [comment]
I'm going to need a clear reproduction. Would you mind creating a brand new app with minimal `splitChunks` config?

**Comment by ranaictiu** [comment]
I've used full-cycle-app and cloned into [https://github.com/ranaictiu/splitchunk-mininal-config](https://github.com/ranaictiu/splitchunk-mininal-config). Looks like the minimal option you need to reproduce is the maxSize as below:

<pre>
<code>
  optimization: {
    splitChunks: {
      maxSize: 4500000,
    }
  }
</code>
</pre>

**Comment by just-jeb** [comment]
Full cycle app has a lot of noice. A clean reproduction with `ng new` would be really helpful.

**Comment by ranaictiu** [comment]
My bad, used an angular boilerplate template - [https://github.com/ranaictiu/angular-boilerplate-splitchunks](https://github.com/ranaictiu/angular-boilerplate-splitchunks)

**Comment by sm0808** [comment]
Does anyone got a solution for this? I am facing the same problem

**Comment by just-jeb** [comment]
Can you provide minimal reproduction?

**Comment by songzhj** [comment]
> Can you provide minimal reproduction?

@just-jeb
https://github.com/songzhj/split-chunk-demo
Same problem, here is a reproduction.
You can run `npm run start`(correct inject in html) and `npm run build:prod`(wrong in html) reproduce it.
Looking forward to some solution. :)

**Comment by subodhkumarWM** [comment]
Just wanted to check if there is any update on this. I am facing the same problem on using '@angular-builders/custom-webpack' with angular 9.

I am trying to chunk 'vendor.[hash].js' using the below config
```
splitChunks: {
            cacheGroups: {
                vendor: {
                    name: true,
                    minSize: 1000000,
                    maxSize: 1000000,
                    test: /[\\/]node_modules(?![\\/]wm)[\\/]/
                }
            }
        }
```
Even though the chunks do get generated, the script tag entries for these are not updated in 'index.html'.

**Comment by subodhkumar** [comment]
Following approach working for me:
I am chunking vendor.js for my build & including back in index.html

Custom-webpack-config
```
. . .
        splitChunks: {
            automaticNameDelimiter:'-',
            cacheGroups: {
                vendor: {
                    minSize: 1000000,
                    maxSize: 1000000,
                    test: /[\\/]node_modules(?![\\/]wm)[\\/]/
                }
            }
        }
. . .
```


Custom Builder has an additional proerty called `indexTransform`.
Ref: https://github.com/just-jeb/angular-builders/blob/9.x.x/packages/custom-webpack/README.md#index-transform

Updated `angular.json`

```
architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "./wm-custom-webpack.config.js"
            },
            "indexTransform":"./index-html-transform.js",
       . . .
```

# index-html-transform.js

```

const fs = require('fs');
const node_path = require('path');

const addScript = (path)=>{
    return `<script src="ng-bundle/${path}"></script>`
}
module.exports = (targetOptions, indexHtml) =>{
    const vendor_path = node_path.resolve(__dirname+`/../dist/ng-bundle`);
    let vendorScripts = ``;
    fs.readdirSync(vendor_path).forEach((file)=>{
        if(file.indexOf('vendor-')===0){
                vendorScripts+=addScript(file);
        }
    });

    const mainScriptStr = `<script src="ng-bundle/main`;
    const mainIndex = indexHtml.indexOf(mainScriptStr);
    
    return `${indexHtml.slice(0,mainIndex)}
            ${vendorScripts}
            ${indexHtml.slice(mainIndex)}`;
}
```

Hopefully this shud help.

Regards,
Subodh Kumar

**Comment by stevefarwell** [comment]
Thanks Subodh,
Slight modification of the vendor_path worked for me with Angular 10.x as the build adds a dir with the project name in the dist folder
const vendor_path = node_path.resolve(__dirname+`/dist/${targetOptions.project}`);

Steve Farwell
