### ISSUE TITLE
Custom library - @angular-builders/custom-webpack:browser throw compile time warning ( angular8)

### ISSUE THREAD

**Issue by HemTech** [just-jeb/angular-builders#742]
I’m getting warning to compile angular 8 project with custom library

WARNING in C:/Project/.../fesm2015/customlibary.js.map 1:10
Module parse failed: Unexpected token (1:10)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

**Comment by arturovt** [comment]
Closing since been stale.
