### ISSUE TITLE
ERROR in No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by eng-dibo** [just-jeb/angular-builders#752]
I just modified my build builder to '@angular-builders/custom-webpack:browser', but wen I try to run `ng build` with or without `aot` and `optimization` I got an error:
`ERROR in No NgModule metadata found for 'AppModule'.`

**Comment by just-jeb** [comment]
I'm gonna need more info on this. Do you have a repository with reproduction? If not, can you please create one?

**Comment by bradhugh** [comment]
Same here. I will try to set up a repro repository next week.
