### ISSUE TITLE
Errors thrown in indexTransform not being reported by the webpack process

### ISSUE THREAD

**Issue by handijk** [just-jeb/angular-builders#768]
## Describe the Bug

Errors thrown in the indexTransform function are not being reported by the webpack process.
Instead the webpack process keeps hanging on "95% emitting index-html-webpack-plugin".

## Minimal Reproduction

Insert a `throw new Error('i am an error')` in the indexTransform function.

## Expected Behavior

I expect the webpack process to fail with the error.

## Environment

<pre><code>
Libs
- @angular/core version: 9.1.11
- @alngular-devkit/build-angular version: 0.901.9
- @angular-builders/custom-webpack: 9.1.0
</code></pre>

For Tooling issues:
- Node version: 12.16.3
- Platform: All

**Comment by just-jeb** [comment]
Actually `indexTransform` is not part of the Webpack build. Index generation is done after the Webpack build has finished.  
I agree that it should throw an error, but it's handled by Angular CLI, I don't have any control of it.  
Probably best to open an issue in Angular CLI repo.
