### ISSUE TITLE
Cannot read property 'flags' of undefined

### ISSUE THREAD

**Issue by mbulfair** [just-jeb/angular-builders#796]
## Describe the Bug

While using version 9.1x of angular this was working as expected. Using this with 10.0.1 I see the below error. I've simplified what I could but I can't seem to figure out where the error is. 

## Minimal Reproduction

Change `build:builder` from `@angular-devkit/build-angular:browser` to `@angular-builders/custom-webpack:browser`

root has a webpack.config.js
```js
const path = require('path');

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/,
        loader: 'postcss-loader',
        options: {
          ident: 'postcss',
        },
      },
    ],
  },
};

```

## Screenshots

![image](https://user-images.githubusercontent.com/5325543/86954694-71c5e700-c124-11ea-92ed-c146c72af99f.png)

## Environment

<pre><code>
Angular CLI: 10.0.1
Node: 12.18.1
OS: darwin x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0
</code></pre>

**Comment by nkgentile** [comment]
See https://github.com/just-jeb/angular-builders/issues/726#issuecomment-654409401

**Comment by mbulfair** [comment]
Thank you @nkgentile

**Comment by mbulfair** [comment]
closing 10 beta fixes the error, Hopefully 10x get's officially released soon
