### ISSUE TITLE
Make Custom Webpack dev-server have its own customWebpackConfig

### ISSUE THREAD

**Issue by rslemos** [just-jeb/angular-builders#803]
Custom Webpack browser, server and karma have its own `customWebpackConfig` property.

Only dev-server uses the respective browser's `customWebpackConfig` property (actually `browserTarget`'s).

I have a scenario where I want to customize only the `serve` target (I need to manipulate some urls that are not part of the build), but I had to add `"build": { "builder": "@angular-builders/custom-webpack:browser" }` only to customize my webpack-dev-server.

**Comment by just-jeb** [comment]
You don't really need a separate entry in config for this.  
What you want can be achieved by adding `customWebpackConfig` entry in your `build` target but under `configurations`.  
Then you can specify the `browserTarget` in your `serve` target with the appropriate configuration (see example [here](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/examples/full-cycle-app/angular.json#L84)).
