### ISSUE TITLE
Question: twice angular enableProdMode warning log in console ?

### ISSUE THREAD

**Issue by qdelettre** [just-jeb/angular-builders#807]
Hi,

Sorry to ask if it's dumb.
I have used these builders in angular 8 project (with MomentLocalesPlugin), and in dev mode i can see this log twice "Angular is running in the development mode. Call enableProdMode() to enable the production mode.".

Is it normal to have it **twice** ? 

Thanks

**Comment by just-jeb** [comment]
When you switch to a regular Angular builder you have the same behavior? Angular runs two builds for differential loading, I guess this is the reason.
