### ISSUE TITLE
@angular-builders/custom-webpack upgrade webpack-merge

### ISSUE THREAD

**Issue by andygup** [just-jeb/angular-builders#819]
**Is your feature request related to a problem? Please describe.**
This is a request to upgrade custom-webpack to the latest version of `webpack-merge`. I did notice this dependabot PR => https://github.com/just-jeb/angular-builders/pull/814 but couldn't find any related issues.

**Describe the solution you'd like**
Use regular merge.

**Describe alternatives you've considered**
With Angular 10, we can run: `ng build && webpack --config ./extra-webpack.config.js` but that's bypassing the Builder approach and not ideal.

**Additional context**
We are having merge issues that I suspect might be related to the use of `webpack-merge` and `smartStrategy`, reference: https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/webpack-config-merger.ts#L2. This is based on 1 year old implementation that's been dropped from the latest version: https://github.com/survivejs/webpack-merge/commit/1c1c2f1e4748da74854a7eec3ab5b676f56b9835

**Comment by just-jeb** [comment]
Dropping `smartStrategy` is a breaking change, so I don't think it can be added as a minor version. It potentially can break a lot of builds, so it should be part of `11` release.

**Comment by just-jeb** [comment]
Closed with #907, you can try it in `11.0.0-beta.2`. Refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#custom-webpack-builder) for the docs.
