### ISSUE TITLE
tsConfig deprecated warning. Bump jest-preset-angular from 8.2.1 to 8.3.2

### ISSUE THREAD

**Issue by field123** [just-jeb/angular-builders#854]
## Describe the Bug
Deprication warning coming from jest-preset-angular due to depricated option property. 

`ts-jest[config] (WARN) The option 'tsConfig' is deprecated and will be removed in ts-jest 27, use 'tsconfig' instead`

Has been updated in the recent version of jest-preset-angular. See https://github.com/thymikee/jest-preset-angular/pull/524

## Minimal Reproduction

Will add tomorrow afternoon if required.

## Expected Behavior

No warnings

## Screenshots

https://i.gyazo.com/e4fbd2338365f189f0d47ac2a9179d1d.png

## Environment

<pre><code>
Libs
- @angular/core version: 10.2.2
- @angular-devkit/build-angular version: 0.1002.0
- @angular-builders/jest version: 10.0.1

For Tooling issues:
- Node version: 12.16.2
- Platform:  Windows

**Comment by just-jeb** [comment]
Pending #819

**Comment by just-jeb** [comment]
Released a beta version, #819 will be handled separately before the release of the stable version.
