### ISSUE TITLE
How does one detect if configuration is production?

### ISSUE THREAD

**Issue by maximedupre** [just-jeb/angular-builders#911]
```
// webpack.config.js
module.exports = (config) => {
    console.log(config.mode); // 'production'
    ...
}
```

`config.mode` is always `production`, whether `ng serve` is executed with `--prod` or not.

Most likely this is just a question, but perhaps the documentation could include this or maybe a new feature :-).

**Comment by just-jeb** [comment]
```js
module.exports = (cfg, opts, targetOptions) => {
   console.log(targetOptions.configuration);
);
```

AFAIK `ng build --prod` is just a nice way to say `ng build --configuration=production`.
