### ISSUE TITLE
"transform is not a function" error on base setup

### ISSUE THREAD

**Issue by BenRacicot** [just-jeb/angular-builders#914]
## Describe the Bug
Hello,
I've setup a basic `"builder": "@angular-builders/custom-webpack:browser"` on my Angular 11.0.5 app and am getting a `transform is not a function` error when building. Even with a blank transform file.

Here is the angular.json config

```
"architect": {
    "build": {
        "builder": "@angular-builders/custom-webpack:browser",
        "options": {
            "customWebpackConfig": {
                "path": "./custom-webpack-build.config.ts",
                "mergeStrategies": {
                    "module.rules": "prepend"
                },
                "replaceDuplicatePlugins": true
            },
            "indexTransform": "./custom-webpack-html.ts"
            ...
```
## Screenshots

<img width="992" alt="Screen Shot 2020-12-28 at 8 45 30 AM" src="https://user-images.githubusercontent.com/1815385/103218483-1ad9e700-48e9-11eb-91a7-72999bc0f23c.png">

## Environment
- "@angular-builders/custom-webpack": "^10.0.1"
- "@angular-devkit/build-angular": "~0.1100.2"
- "@angular/cli": "~11.0.5"
- "@angular/compiler-cli": "^11.0.5"
- Platform:  MacOS 10.15.7 

I cannot find reference to this error via Google or GH issues.
Thank you for input.

**Comment by just-jeb** [comment]
Hey. You're using Angular Builders v10 with Angular 11. The versions should be aligned as the documentation states.  
Please refer to the [migration guide](https://github.com/just-jeb/angular-builders/blob/master/MIGRATION.MD#migration-from-version-10-to-version-11) in order to upgrade to Angular Builders v11.

**Comment by BenRacicot** [comment]
Ah, my apologies. I just missed that detail but also see now that V11 was launched yesterday!

**Thank you** for your hard work on this plugin. Bringing sanity to a lot of engineers.

**Comment by just-jeb** [comment]
It is my pleasure.
