### ISSUE TITLE
Bundle additional "scripts" files with ng serve, as it works with ng build

### ISSUE THREAD

**Issue by qortex** [just-jeb/angular-builders#915]
## Describe the Bug

I'd like to add a permanent js script file (in `assets` directory) to the build when served through `ng serve`.

It works fine when using `ng build`, I just have a `scripts` array with the file.

Now when I create a specific config in the builder for adding this file and referring to it from `ng serve`, it fails with the error below. Am I missing something?

## Minimal Reproduction

My `serve` config:
```json
"serve": {
  "builder": "@angular-builders/custom-webpack:dev-server",
  "options": {
    "browserTarget": "frontend:build"
  },
  "configurations": {
    "withjs": {
      "browserTarget": "frontend:build:withjs"
    }
  }
},
```

And then in my `build`, I have:
```json
"build": {
  "builder": "@angular-builders/custom-webpack:browser",
  "options": {
    // ...options
    "scripts": [],
  },
  "configurations": {
    "production": {
      // ...options
      "scripts": ["src/assets/js/myfile.js"],
    },
    "staging": {
      // ...options
      "scripts": ["src/assets/js/myfile_staging.js"],
    },
    "withjs": {
      "scripts": ["src/assets/js/myfile_staging.js"]
    }
  }
},
```

When I run `ng serve`, the app is served without the js file.

When I run `ng serve -c withjs`, it fails with:
```
✔ Compiled successfully.
✔ Browser application bundle generation complete.
⠙ Generating browser application bundles (phase: building).../home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/plugins/scripts-webpack-plugin.js:39
            const scriptTime = compilation.fileTimestamps.get(scripts[i]);
                                                          ^

TypeError: Cannot read property 'get' of undefined
    at ScriptsWebpackPlugin.shouldSkip (/home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/plugins/scripts-webpack-plugin.js:39:59)
    at /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/plugins/scripts-webpack-plugin.js:73:22
    at /home/mic/dev/qontrol/product/frontend/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/plugins/scripts-webpack-plugin.js:26:93
    at /home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:478:47
    at fn (/home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:398:9)
    at Hook.eval [as callAsync] (eval at create (/home/mic/dev/qontrol/product/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:53:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/mic/dev/qontrol/product/frontend/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:2147:33)
    at /home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:2193:9
    at /home/mic/dev/qontrol/product/frontend/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/mic/dev/qontrol/product/frontend/node_modules/neo-async/async.js:2850:39)
    at Compilation.createChunkAssets (/home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:3258:12)
    at /home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:2188:13
    at /home/mic/dev/qontrol/product/frontend/node_modules/webpack/lib/Compilation.js:2342:5
    at /home/mic/dev/qontrol/product/frontend/node_modules/neo-async/async.js:2818:7
    at done (/home/mic/dev/qontrol/product/frontend/node_modules/neo-async/async.js:3522:9)
```

**Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducable issues.
Please delete this note once you have read it.

## Expected Behavior

I would expect that `ng serve -c withjs` does the same as `ng serve`, just adding the `js` file to the bundle.

## Environment

<pre><code>
Libs
- @angular/core version: 11.0.6
- @angular-devkit/build-angular version: 0.1100.6
- @angular-builders/custom-webpack version: 11.0.0

**Comment by just-jeb** [comment]
Not a builder issue but I'll try to help you. If I understand your issue then you should add this configuration to the `build` target and in `serve` target use the same configuration name in order to point to the right `browserTarget` configuration like in [this](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/examples/full-cycle-app/angular.json#L87) example.  
Let me know if it helped.

**Comment by qortex** [comment]
Thanks for the help!
I must be looking at the wrong thing, I believe that's what I already do and it's coherent with the link you sent. I must be missing something.

**Comment by just-jeb** [comment]
Try to isolate it (remove the usage in Angular Builders and leave the part with scripts and configurations), see if it reproduces with default Angular setup and if yes then it must be an issue on their end.

**Comment by qortex** [comment]
Thanks! I'll dig into it.
I really don't see clearly who does what in all this custom-webpack / builder / dev-kit / webpack party. I need to spend some time learning those things one day!

**Comment by qortex** [comment]
Alright, actually it works as expected when I switch back to webpack 4.

I had enabled webpack 5 in my project, and enabling it makes this error appear. When reverting to webpack 4, it works as expected, and my workflow works as is.

So I'll close this issue, and leave that error sadly lingering in the abyss for now.
