### ISSUE TITLE
Support Karma 6 by using latest rc from angular cli

### ISSUE THREAD

**Issue by muuvmuuv** [just-jeb/angular-builders#919]
**Is your feature request related to a problem? Please describe.**

I would like to use the latest Karma 6 version but unfortunately this is only possible with the latest rc from angular cli.

**Describe the solution you'd like**

Also provide a beta/rc that includes the latest rc 11.1 from angular cli.

**Describe alternatives you've considered**

None

**Additional context**

https://github.com/angular/angular-cli/issues/19815#event-4221673994

**Comment by just-jeb** [comment]
You should be able to use it now that `11.1` is no longer in RC, correct?

**Comment by muuvmuuv** [comment]
Yes this fixes it
