### ISSUE TITLE
Remove Console.log in Angular 9

### ISSUE THREAD

**Issue by sonnyk22** [just-jeb/angular-builders#927]
Is there a feature in this library to remove all the `Console.Logs` in Angular 9 or higher?  If yes, then is there a sample code for it.

Thank you

**Comment by just-jeb** [comment]
Not sure I understand what you're talking about. Please elaborate.

**Comment by Dassderdie** [comment]
You can use [environment variables](https://angular.io/guide/build#using-environment-specific-variables-in-your-app) to do stuff like that:
```ts
if(environment.production) {
    console.log = () => {};
}
```

**Comment by just-jeb** [comment]
There is [a way](https://www.coditty.com/code/angular-how-to-remove-console-log-from-production-build) to completely remove `console.log` from production code. Is this what you're looking for?

**Comment by arturovt** [comment]
@sonnyk22 

This works perfect, just checked it out:
```js
// webpack.config.js
module.exports = config => {
  config.optimization.minimizer.forEach((minimizer) => {
    if (minimizer.constructor.name === 'TerserPlugin') {
      minimizer.options.terserOptions.compress.drop_console = true;
    }
  });

  return config;
};
```

I think the issue can be closed.

**Comment by pasevin** [comment]
@arturovt thanks for this, I don't know where did you find this, but that's the only way it works for me on Angular 11 too. Share the link where you found it please.

**Comment by arturovt** [comment]
I didn’t find it anywhere, I just checked terser plugin options.

**Comment by just-jeb** [comment]
@pasevin I provided a link two comments above 😄

**Comment by pasevin** [comment]
Thanks, guys, I'm "console.log-free" now ;)
