### ISSUE TITLE
Remove "@angular-devkit" from custom-webpack published package.json dependencies.

### ISSUE THREAD

**Issue by abadakhshan** [just-jeb/angular-builders#930]
"@angular-devkit/architect": ">=0.1100.0 < 0.1200.0",
"@angular-devkit/build-angular": ">=0.1100.0 < 0.1200.0",
"@angular-devkit/core": "^11.0.0"

in "@angular-builders/custom-webpack" in some scenario with **yarn** causes that we have two different versions of these packages, one in `node_modules ` root and another in  `node_modules/@angular-builders/custom-webpack/node_modules`.

Moving these dependencies to peer dependencies in the published package.json can solve this problem.

**Comment by just-jeb** [comment]
Hey @abadakhshan , thanks for your suggestion. It has already been discussed, you can find my response [here](https://github.com/just-jeb/angular-builders/issues/873#issuecomment-731649466). You're also welcome to read the whole discussion in #873.

**Comment by abadakhshan** [comment]
Thank you @just-jeb.

Please use `Yarn` to install dependencies with this` package.json`

```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1101.0",
    "@angular-builders/custom-webpack": "~11.0.0"
  }
}
```

After installing we have `@angular-devkit\build-angular@0.1101.4` in `node_modules` and  `@angular-devkit/build-angular@0.1102.0` in  `node_modules\@angular-builders\custom-webpack\node_modules` and this can cause many issues.


Am I doing something wrong?

**Comment by just-jeb** [comment]
Interesting... Seems like Yarn installs the latest version of Devkit for Angular Builders, although it is compatible with previous versions as well. I suppose this is how it works, not much that I can do. 
Why are you restricting the Devkit version to `0.1101.*`?

**Comment by abadakhshan** [comment]
It was just an Example.
This issue also happen when you have a yarn.lock with devkit 0.1101.*, then upgrade it to 0.1102.*.

**Comment by just-jeb** [comment]
I guess it's a problem with `yarn`, not with the builders. Am I missing something?

**Comment by abadakhshan** [comment]
> I guess it's a problem with `yarn`, not with the builders. Am I missing something?

I created an issue for Yarn 
https://github.com/yarnpkg/berry/issues/2482

**Comment by larixer** [comment]
@abadakhshan @just-jeb You might be interested to declare these dependencies as both peerDependencies and regular dependencies. In this case `npm` and `yarn 1` will treat them as regular dependencies. Yarn 2+ will treat them as peerDependencies if they are provided by the parent package and regular dependencies if they were not provided by a parent package.
