### ISSUE TITLE
custom-webpack: Invalid or unexpected token @ 11.0.0 -> 11.1.0 (and 11.1.1)

### ISSUE THREAD

**Issue by tony** [just-jeb/angular-builders#944]
Hi, thank you for the project @just-jeb!

Updated for 11.1.1

- https://github.com/tony/cv/runs/2066271570
- https://github.com/tony/cv/pull/1256

## Describe the Bug

When updating to 11.0.0 -> 11.1.0, I started getting an issue when performing production builds (e.g. `yarn build --prod`):

```
- Generating browser application bundles...
An unhandled exception occurred: styles.c14a328672c59a2d3bd2.css Invalid or unexpected token
See "/tmp/ng-hPuLP5/angular-errors.log" for further details.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 127.
```

Link: https://github.com/tony/cv/runs/2008951146 (master failure), https://github.com/tony/cv/runs/2009209231

Possibly related to

- https://github.com/just-jeb/angular-builders/pull/879
- https://github.com/just-jeb/angular-builders/blob/%40angular-builders/custom-webpack%4011.1.0/packages/custom-webpack/CHANGELOG.md
- changes: https://github.com/just-jeb/angular-builders/commits/%40angular-builders/custom-webpack%4011.1.1
- commits: https://github.com/just-jeb/angular-builders/compare/@angular-builders/custom-webpack@11.0.0...@angular-builders/custom-webpack@11.1.0
- diff: https://github.com/just-jeb/angular-builders/compare/@angular-builders/custom-webpack@11.0.0...@angular-builders/custom-webpack@11.1.0

## Minimal Reproduction

Sorry if this doesn't meet your requirement - I will do the best I can!

Before (@ 11.0.0): [ref](https://github.com/tony/cv/commit/e64b77c1f33a41c412b28d3b92ab608dc3a46072), [CI passing](https://github.com/tony/cv/runs/2009193917)
After (@ 11.1.0) PR with package upgraded and CI failing: [ref](https://github.com/tony/cv/commit/5e92fb70683307082debf0785e30576f679089ed), [PR](https://github.com/tony/cv/pull/1256), [diff](https://github.com/tony/cv/pull/1256/files), [branch](https://github.com/tony/cv/tree/angular-custom-webpack), [CI Failing](https://github.com/tony/cv/runs/2009209231)

`yarn build --prod`

## Expected Behavior

Build to finish (to be fair I'm not quite sure what's happening when it works correctly 😆)

## Environment

Libs
- @angular/core version: 11.2.3
- @angular-devkit/build-angular version: 0.1102.2
- @angular-builders/custom-builder version: 11.1.0

For Tooling issues:
- Node version: 12.20.1
- Platform:  Ubuntu

**Comment by just-jeb** [comment]
Should be fixed in `11.1.1`. Can we close the issue?

**Comment by tony** [comment]
@just-jeb Yes we can! Thank you!

**Comment by tony** [comment]
@just-jeb I am getting the same issue with 11.1.1

https://github.com/tony/cv/pull/1256 / https://github.com/tony/cv/runs/2066271570

**Comment by tony** [comment]
Happening with 12.x as well

**Comment by tony** [comment]
I guess it has something to do with how I use SCSS.  I still haven't solved this

Is there a way to disable the #879 change in 11.1.0 / 12.0?  Is that something that could be added?

https://github.com/tony/cv/pull/1256 is still available to checkout and test.  I'm still pinned at 11.0.0. At this point my only choice is to stay at angular 11 or find a way to customize webpack

**Comment by tony** [comment]
Mostly I'm limited by a lack of angular build process knowledge.  I only dabble in angular in a limited way at the moment.

**Comment by tony** [comment]
@just-jeb If I turn off CSS compression, it works:

```diff
diff --git a/packages/angular/angular.json b/packages/angular/angular.json
index 30fbb8a..7fe7dd1 100644
--- a/packages/angular/angular.json
+++ b/packages/angular/angular.json
@@ -48,7 +48,12 @@
               ],
               "deployUrl": "./",
               "baseHref": "./",
-              "optimization": true,
+              "optimization": {
+                "scripts": true,
+                "styles": {
+                  "minify": false
+                }
+              },
               "outputHashing": "all",
               "sourceMap": false,
               "namedChunks": false,
```

We know it's related to `optimize-css-webpack-plugin.js`

```
[error] Error: styles.b643bc06221d292b1c7e.css Invalid or unexpected token
    at /home/t/work/cv/packages/angular/node_modules/@angular-builders/custom-webpack/node_modules/@angular-devkit/build-angular/src/webpack/plugins/optimize-css-webpack-plugin.js:98:48
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Can I get a better idea what happened in 11.1.1?  Maybe it has to do with my scss coming from another package in the monorepo?

**Comment by just-jeb** [comment]
As you can see from the [CHANGELOG](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/CHANGELOG.md) there is nothing that could have affected css since `11.0.0`.  
And from what I can see you don't have anything CSS related in your webpack config... 
If you switch to `@angular-devkit` builder, does it make the build pass?

**Comment by tony** [comment]
Sorry for the delay

> If you switch to `@angular-devkit` builder, does it make the build pass?

Yes, it does build:

```diff
diff --git a/packages/angular/angular.json b/packages/angular/angular.json
index 30fbb8ac..a75c985c 100644
--- a/packages/angular/angular.json
+++ b/packages/angular/angular.json
@@ -18,11 +18,8 @@
       "prefix": "app",
       "architect": {
         "build": {
-          "builder": "@angular-builders/custom-webpack:browser",
+          "builder": "@angular-devkit/build-angular:browser",
           "options": {
-            "customWebpackConfig": {
-              "path": "./webpack/webpack.custom.ts"
-            },
             "preserveSymlinks": true,
             "outputPath": "dist/angular",
             "index": "src/index.html",
```

> And from what I can see you don't have anything CSS related in your webpack config...

Not in the webpack config, but in my options. This passes w/ `custom-webpack`:

```diff
diff --git a/packages/angular/angular.json b/packages/angular/angular.json
index 30fbb8ac..7a5b4246 100644
--- a/packages/angular/angular.json
+++ b/packages/angular/angular.json
@@ -35,7 +35,7 @@
               { "glob": "favicon.ico", "input": "../data/img/", "output": "/" },
               { "glob": "**/*", "input": "../data/img/", "output": "/assets/img/" }
             ],
-            "styles": ["../ui/styles/style.scss"],
+            "styles": [],
             "scripts": []
           },
           "configurations": {
```

The scss file is outside the angular monorepo: https://github.com/tony/cv/blob/angular-custom-webpack/packages/ui/styles/style.scss

**Comment by just-jeb** [comment]
Mind trying to remove the `package-lock` (or `yarn.lock`) and running a clean install? Might be some versions issue.

**Comment by tony** [comment]
- Removed yarn.lock: https://github.com/tony/cv/actions/runs/976273984
- Renewed yarn.lock after `rm -rf node_modules/ **/node_modules`: https://github.com/tony/cv/actions/runs/976278033

**Comment by tony** [comment]
@just-jeb I fixed with by removing `browserslist`. Some how, this changed ended up trying to build `browserslist` to me. Thank you for sticking with me on this!

11.1.1:
- With `browserslist` (failure): https://github.com/tony/cv/runs/2925295705, https://github.com/tony/cv/commit/4b4b13edeeda5c442912c92173ea45969e83ba89
- Without `browserslist` (success): https://github.com/tony/cv/runs/2925398375, https://github.com/tony/cv/commit/670a9ad816c7f15790210b2de2ad326c40dd0e5c
