### ISSUE TITLE
Need help using Webpack HMR with Angular Universal.

### ISSUE THREAD

**Issue by luongngocminh** [just-jeb/angular-builders#946]
I'm currently developing a large Angular Universal app, and it cost a lot of time rebuilding the code when there are any changes using either

-  `dev-ssr` - which is only watch both backend and frontend and reload when there're changes, this will consume a huge amount of ram and cpu because it will watch everything and only live reload (not hmr)
-  `build:ssr` - which is very slow in development environment when I have to manually rebuild the entire project everytime I change something.

Is there a way for me to integrate webpack to have hot reload and hmr for this project? Atleast on the server side.

**Comment by just-jeb** [comment]
If I understand your question correctly, then you can use [`custom-webpack:server`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#Custom-webpack-server) in conjunction with [`HotModuleReplacementPlugin`](https://webpack.js.org/plugins/hot-module-replacement-plugin/)
