### ISSUE TITLE
Module output source isn't being updated when using a Webpack loader

### ISSUE THREAD

**Issue by silverAndroid** [just-jeb/angular-builders#952]
## Describe the Bug

I'm trying to use a Webpack loader to automatically import a directive module to a component module when a certain condition has been met. However, it seems to be that even though I update the source to include the HelloModule inside the imports array of the AppModule's NgModule decorator, it doesn't seem to be included in the build output. I'm not sure if it's an issue where I need to add an option to the AngularCompilerPlugin or something else entirely.

## Minimal Reproduction

https://github.com/silverAndroid/angular-custom-webpack-inject-module

## Expected Behavior

* When the app (from the minimal reproduction repository) loads, there should be a log in the browser console saying 'hello from the appHello directive'.
* After running a production build, inside `dist/custom-webpack-inject-module/main.js`, there is one instance of './hello/hello.module' as a comment (meaning that the module was included in the build in the AppModule).

## Environment

<pre><code>Libs
- @angular/core version: "~11.2.4"
- @angular-devkit/build-angular version: "~0.1102.3"
- @angular-builders/custom-webpack: "^11.1.1"

For Tooling issues:
- Node version: 12.17.0
- Platform: macOS
</code></pre>

**Comment by just-jeb** [comment]
Hi @silverAndroid. Do you get console logs? If yes then it means that your loader is called you should be looking for the problem inside.  
Otherwise, the problem might be in the [`mergeRules`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-object) (currently you're using default). In this case I'd suggest you go with [custom Webpack config function](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack#custom-webpack-config-function). This way you have full control over the configuration and leave no room for merge issues.

**Comment by silverAndroid** [comment]
Hi @just-jeb. In the minimal reproduction, I log what's being returned after modifying the source and it is the expected behaviour.
![image](https://user-images.githubusercontent.com/5651666/110835169-753ddf00-826c-11eb-9b73-308dac8c6fc3.png)
However, when I look inside the `main.js` being served, I don't see any mention of the `HelloModule` anywhere

**Comment by silverAndroid** [comment]
Another thing to note is if I pass invalid source code (I removed the ending apostrophe from the HelloModule import), I don't see any compiler errors being emitted.

**Comment by silverAndroid** [comment]
I think I may end up needing to use TypeScript transformers through the Angular compiler plugin 😰

**Comment by just-jeb** [comment]
So if I understand it right there is no issue with the builder itself, is that correct?

**Comment by silverAndroid** [comment]
@just-jeb I believe so, seems to be a design decision with the Angular Compiler

**Comment by just-jeb** [comment]
In case you missed it, check out [this](https://github.com/just-jeb/angular-builders/issues/484#issuecomment-529101071) and [this](https://github.com/just-jeb/angular-builders/issues/484#issuecomment-529105020).
