### ISSUE TITLE
Upgrade to the last version of @angular-devkit/build-angular to have tailwind

### ISSUE THREAD

**Issue by jogelin** [just-jeb/angular-builders#954]
Since angular v11.2, it is possible to use tailwind directly in angular cli. ([please check PR](https://github.com/angular/angular-cli/pull/19935))

But because it is using internal dependencies for `@angular-devkit/build-angular`, it is not compatible with this and tailwind is not injected !

**Comment by just-jeb** [comment]
The internal dependencies [do not](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/package.json#L41) restrict minor Angular versions. The builder should work with 11.2. 
In fact there are people using it with the builder, I had to update the schemas to match 11.2.
