### ISSUE TITLE
loader output seems to be ignored/lost

### ISSUE THREAD

**Issue by yevit** [just-jeb/angular-builders#963]
Hi,

I'm trying to get `@angular-builders/custom-webpack` to use the `string-replace-loader` to change the contents of a file before it is outputted. I've tried quite a few different configurations but the replacement always seems to be ignored, even though the replacement function is running.

[I've setup a repo here](https://github.com/yevit/angular-cli-webpack-testing) using the Angular getting started project. The loader is setup in `webpack.config.js` to replace the string in `src/app/app.component.ts`. When I run `ng serve` I can see the console.log message appearing from the loader function but the angular app still has the original text.

I've tried a few different loaders/plugins & `mergeRules` but I've never been able to get it to work.

I'm also trying a similar thing with `image-webpack-loader` to remove comments from svg files but getting the same result so I'm hoping that getting to the bottom of this will help with that too.

This is in preparation for moving a large Angular project from a pure webpack build to using the Angular CLI so I'm trying to find a middle ground. All of the loaders are currently setup in the larger project so I'm know they should work fine.

Thanks for your help

## Minimal Reproduction

Pull my repo here https://github.com/yevit/angular-cli-webpack-testing.
Or
- Create a new angular project
- Install `@angular-builders/custom-webpack` & `string-replace-loader`
- Setup the custom webpack config
- Add a string replacement rule
- Run ng serve or ng build

## Expected Behavior

The replacement string to appear.

## Screenshots
![image](https://user-images.githubusercontent.com/2155908/112872786-b2053500-90b8-11eb-980a-07b031789cae.png)

![image](https://user-images.githubusercontent.com/2155908/112872833-be898d80-90b8-11eb-886e-72d7d3255dc7.png)

## Environment

<pre><code>
Libs
- @angular/core version: 11 (I've also tried 9)
- @angular-builders/custom-webpack

**Comment by just-jeb** [comment]
Looks like the same issue as in #952 . Don't think I can do anything about it.
