### ISSUE TITLE
Multiple webpack entry points support

### ISSUE THREAD

**Issue by skosito** [just-jeb/angular-builders#966]
**Is your feature request related to a problem? Please describe.**
I am currently migrating from webpack build to ng cli, and I have 2 entry points:

entry: {
  "entry-point-1": "path1",
  "entry-point-2": "path2"
}

However, angular.json scheme only contains one field for this (main), and fields scripts, but it seems like it is not suitable for this.

**Describe the solution you'd like**
Would like possibility to have multiple entry points, if that is not already possible somehow?

**Describe alternatives you've considered**
Any alternative would work.

**Comment by just-jeb** [comment]
Have you tried to override the `entry` with custom Webpack config?

**Comment by skosito** [comment]
@just-jeb yes, but then when I ng serve it, I get ```
X is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.
```
for all files.

**Comment by skosito** [comment]
@just-jeb when i add entry to custom webpack config, and in angular.json

`"mergeRules": {
                "entry": "replace"
              }`
              
and if I run ng build it is showing correct bundles (and only spec files unused), but ng serve just lists all ts files as unused...
I am using ng cli 10.2.3, and custom webpack 10.0.1. Do you have some suggestions?

**Comment by skosito** [comment]
after checking the docs and code, i noticed i was doing 2 things wrong:
- using mergeRules instead of mergeStrategies (since I am using v10, and mergeRules is available in v11)
- mergeStrategies not needed when using custom webpack config function

managed to solve it using config function by modifying config.entry object, something like this:
config.entry['new-entry'] = ['path-to-entry']
