### ISSUE TITLE
".maxWorkers should be number" is incorrect

### ISSUE THREAD

**Issue by greelgorke** [just-jeb/angular-builders#969]
## Describe the Bug

By trying to configure the `maxWorkers` option for the jest builder with a string value the validation error is thrown. [Jest CLI Documentation](https://jestjs.io/docs/cli#--maxworkersnumstring) disagrees.

## Minimal Reproduction

1. create an angular app and configure it for usage with the jest builder
2. put the `maxWorkers` option as string value i.e. `"maxWorkers" :"50%"`
3. run ng test

## Expected Behavior
Tests are run with the configured maxWorkers.

## Environment

<pre><code>
Libs

    "@angular/core": "~11.0.8",
    "@angular-builders/jest": "^11.0.0",
    "@angular-devkit/build-angular": "^0.1100.6",

For Tooling issues:
- Node version: 12.10
- Platform:  MacOS 11.2.3

**Comment by just-jeb** [comment]
Should be fixed in `v11.2.0-beta.1`, would you mind confirming?

**Comment by greelgorke** [comment]
I've tested your change locally. it works, thanks!

in the meantime I could work around that issue by putting the configuration in the jest.config file

**Comment by just-jeb** [comment]
No need, I'm releasing it now from the beta.
