### ISSUE TITLE
Angular 12 webpack 5

### ISSUE THREAD

**Issue by ganySA** [just-jeb/angular-builders#972]
Hi

Any idea if this works with Angular 12 webpack 5?

Getting multiple errors since upgrading and tailwindcss seems to break further.

"CustomWebpackDevServerSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

Compliation just seems to hang on
Generating browser application bundles (phase: building)...

**Comment by just-jeb** [comment]
Angular 12 is not yet officially released hence not yet supported by the builders. Once it is released I'll release a new version of builders supporting Angular 12.

**Comment by piotrroda** [comment]
Angular Team officially released v12 yesterday.

**Comment by ArielGueta** [comment]
I have just upgraded my application to Angular 12 and getting the same:

```
"BuilderInputSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"BuilderOutputSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"CustomWebpackDevServerSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
"BuildCustomWebpackBrowserSchema" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.

⠋ Generating browser application bundles...Cannot read property 'get' of undefined
```

We can't upgrade without the compatibility of this library.

**Comment by just-jeb** [comment]
Guys, please see if `12.0.0-beta.0` works for you. If yes I'll release it officially.

**Comment by elliotleelewis** [comment]
> Guys, please see if `12.0.0-beta.0` works for you. If yes I'll release it officially.

Yep, works for me!

**Comment by GeorgeKnap** [comment]
first I got an error that webpack is not found. After installing it into dev dependencies I'm geting this error during the ng build:
```
- Generating browser application bundles...
An error occurred during the build:
TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (c:\development\SDS\core-ui-v3\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:125:10)
    at c:\development\SDS\core-ui-v3\node_modules\terser-webpack-plugin\dist\index.js:566:67
    at _next47 (eval at create (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:77:1)
    at _next25 (eval at create (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:189:1)
    at _next3 (eval at create (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:280:1)
    at Hook.eval [as call] (eval at create (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:298:1)
    at Hook.CALL_DELEGATE [as _call] (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:14:14)
    at Compiler.newCompilation (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1031:26)
    at c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.compile (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:1068:28)
    at c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:496:12
    at Compiler.readRecords (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:908:11)
    at c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:493:11
    at Hook.eval [as callAsync] (eval at create (c:\development\SDS\core-ui-v3\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
An unhandled exception occurred: The 'compilation' argument must be an instance of Compilation
```

**Comment by just-jeb** [comment]
@GeorgeKnap please try removing `package-lock.json` and `node_modules` and doing a clean install. If that doesn't help I'm gonna need a repro for investigation.

**Comment by GeorgeKnap** [comment]
> @GeorgeKnap please try removing `package-lock.json` and `node_modules` and doing a clean install. If that doesn't help I'm gonna need a repro for investigation.

👍 that seems to do the trick

**Comment by gabynevada** [comment]
> @GeorgeKnap please try removing `package-lock.json` and `node_modules` and doing a clean install. If that doesn't help I'm gonna need a repro for investigation.

Had the same issue, this solved it for me.

**Comment by mshima** [comment]
The error happens when there are 2 versions of webpack in the dependency tree. eg `webpack@5.37.0` and `webpack@5.36.2`.
`@angular-devkit/build-angular@12.0.0` has a transient dependency on `webpack@5.36.2` and will fail when `webpack@!=5.36.2` is in `@angular-devkit/build-webpack` tree.

There are no safeguards for this problem.
To implement safeguard:
- `@angular-builders/custom-webpack` should add a peer dependency on `@angular-devkit/build-angular`
- `@angular-devkit/build-angular` should add a peer dependency on `webpack@5.36.2`.

This will force `webpack@5.36.2` to be deduped at the root of the project.

To workaround the problem:
 - Add dependency on `webpack@5.36.2` or remove `webpack` from dependency and recreate node_modules/package-lock
 - Don't use `npm install --force` (not deduping right), use `npm install --legacy-peer-deps` instead.

**Comment by just-jeb** [comment]
Thanks for the detailed breakdown, @mshima. Just FYI `@angular-builders/custom-webpack` has a direct dependency in `@angular-devkit/build-angular` so I don't think that adding it as a peer dependency would change anything.

**Comment by mshima** [comment]
@just-jeb this kind of problem is exactly what peer dependencies is designed to solve:
https://classic.yarnpkg.com/en/docs/dependency-types/#toc-peerdependencies.
https://nodejs.org/es/blog/npm/peer-dependencies/#the-solution-peer-dependencies.
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies.

The application won't work without `webpack@5.36.2` so the fix is to enforce it.

**Comment by ArielGueta** [comment]
Thanks! I have the following issues after upgrading:
- The `sealing` phase is slow from some reason
- I started to get the following errors:
```
BREAKING CHANGE: The request './lexer' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```
- Lazy Chunk Files are shown as numbers. For example: `995.js`

**Comment by just-jeb** [comment]
@ArielGueta seems like Webpack [issues](https://github.com/webpack/webpack/issues/11636), unfortunately there is nothing I can do about it.

**Comment by just-jeb** [comment]
That's really weird, the tests including ones that use index transform are passing with Angular 12.  
Could you please provide a repo with a reproduction if this issue?

**Comment by ArielGueta** [comment]
We are using index transform, and it works fine.

**Comment by calarconpieriz** [comment]
> The error happens when there are 2 versions of webpack in the dependency tree. eg `webpack@5.37.0` and `webpack@5.36.2`.
> `@angular-devkit/build-angular@12.0.0` has a transient dependency on `webpack@5.36.2` and will fail when `webpack@!=5.36.2` is in `@angular-devkit/build-webpack` tree.
> 
> There are no safeguards for this problem.
> To implement safeguard:
> 
> * `@angular-builders/custom-webpack` should add a peer dependency on `@angular-devkit/build-angular`
> * `@angular-devkit/build-angular` should add a peer dependency on `webpack@5.36.2`.
> 
> This will force `webpack@5.36.2` to be deduped at the root of the project.
> 
> To workaround the problem:
> 
> * Add dependency on `webpack@5.36.2` or remove `webpack` from dependency and recreate node_modules/package-lock
> * Don't use `npm install --force` (not deduping right), use `npm install --legacy-peer-deps` instead.

This was the main problem. I had a version for `@angular-builders/custom-webpack` and other for `@angular-devkit/build-angular` as I updated the Angular version with ng update <deps>. I solved it by updating `@angular-builders/custom-webpack` manually.
