### ISSUE TITLE
Try loading webpack config as ESM

### ISSUE THREAD

**Issue by muuvmuuv** [just-jeb/angular-builders#978]
**Is your feature request related to a problem? Please describe.**

We are currently switching a few things to fully ESM with Node 16 (or trying it out at least) but got an error trying to use webpack config as full ESM.

```
[error] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /webpack.config.mjs
    at new NodeError (node:internal/errors:329:5)
    at Module.load (node:internal/modules/cjs/loader:970:11)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at resolveCustomWebpackConfig (..@angular-builders/custom-webpack/dist/custom-webpack-builder.js:47:33)
    at Function.<anonymous> (..@angular-builders/custom-webpack/dist/custom-webpack-builder.js:26:46)
    at Generator.next (<anonymous>)
    at ..@angular-builders/custom-webpack/dist/custom-webpack-builder.js:8:71
    at new Promise (<anonymous>)
```

**Describe the solution you'd like**

Maybe check if its a ES module before loading it.

**Describe alternatives you've considered**

Let's discuss

**Additional context**

https://github.com/webpack/webpack-cli/releases/tag/webpack-cli%404.5.0

**Comment by just-jeb** [comment]
The issue is most probably [here](https://github.com/just-jeb/angular-builders/blob/master/packages/custom-webpack/src/custom-webpack-builder.ts#L70), `.mjs` modules cannot be loaded with `require` function, but rather require a dynamic `import()`.

**Comment by just-jeb** [comment]
From what I hear the effort is not worth it, any reason why you would want to use `mjs` specifically for the config?

**Comment by muuvmuuv** [comment]
We have helper scripts which are shared through some tools which are written as modules. We just wanted to benefit from the latest syntax, but it really seems no lib configs are supporting modules. Kinda sad, but I guess it's because modules are so new. So, I will just mark them as cjs in our linters for now.

**Comment by just-jeb** [comment]
Ok, I'll leave this issue open with a low priority in case someone has time to play around with it.

**Comment by muuvmuuv** [comment]
So I came into trouble with ESM again since most packages are not migrating to ESM only syntax (like every package from sindre: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).

Looking into it again and trying some different "module" configurations I couldn't get it working. Here is a repl: https://github.com/muuvmuuv/issue-angular-es-module

So it is not only .mjs files but every package that is ESM-only with type:module. At least it seems so (see repl).
