### ISSUE TITLE
Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by ZOUJIELynn** [just-jeb/angular-builders#982]
## Describe the Bug

I met the error : 'An unhandled exception occurred: Right-hand side of 'instanceof' is not an object' when update to 12.0.0-beta.0

## Minimal Reproduction

**Note:** Our policy is that issues reported without a reproduction will be closed immediately and then reopened once a reproduction has been provided. Please respect the developers of this project by doing this. We give of our personal time to work on this project and would rather be spending our time fixing or enhancing the library than chasing down badly described or unreproducible issues.
Please delete this note once you have read it.

## Environment

<pre><code>
Libs
- @angular/core version: 12.0.0
- @angular-devkit/build-angular version: 12.0.0
- @angular-builders/{the name of the builder} version: 12.0.0

For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by just-jeb** [comment]
Gonna need a little bit more info. Just like the Issue Template suggests.

**Comment by ZOUJIELynn** [comment]
> Gonna need a little bit more info. Just like the Issue Template suggests.

I find that when update to 12.0.0, ‘AngularCompilerPlugin’ becomes ‘undefined’  
caused the error when build

**Comment by ZOUJIELynn** [comment]
> > Gonna need a little bit more info. Just like the Issue Template suggests.
> 
> I find that when update to 12.0.0, ‘AngularCompilerPlugin’ becomes ‘undefined’
> caused the error when build

The error caused by @ngtools/webpack  changed the export content
