### ISSUE TITLE
Angular 12 ERROR [karma-server]: Server start failed on port 9876: TypeError: Cannot read property 'hooks' of null

### ISSUE THREAD

**Issue by KirillMetrik** [just-jeb/angular-builders#988]
## Describe the Bug

Using `@angular-builders/custom-webpack:karma` for running tests causes the following exception with Angular 12: "ERROR [karma-server]: Server start failed on port 9876: TypeError: Cannot read property 'hooks' of null"

## Minimal Reproduction
Minimal reproduction repo: https://github.com/KirillMetrik/error-test

Steps:
* clone repo
* run `npm install`
* run `ng test`
The test run will fail with error: 
> ERROR [karma-server]: Server start failed on port 9876: TypeError: Cannot read property 'hooks' of null

## Expected Behavior

Tests should compile and run.
After replacing `@angular-builders/custom-webpack:karma` test builder with the standard one (`@angular-devkit/build-angular:karma`) and removing `customWebpackConfig` section from angular.json everything works without errors.

## Environment

<pre><code>
Libs
- @angular/core version: 12.0.1
- @angular-devkit/build-angular version: 12.0.1
- @angular-builders/custom-webpack version: 11.1.1

- Node version: 14.17.0
- Platform:  Windows

</code></pre>

## Additional Context

With Angular version 11 everything works.

**Comment by rudivanbiljon** [comment]
Confirmed that updating resolved it for me.
