### ISSUE TITLE
Update jest-preset-angular to v9

### ISSUE THREAD

**Issue by PascalHonegger** [just-jeb/angular-builders#999]
**Is your feature request related to a problem? Please describe.**
I'm trying to use the new [jest-preset-angular Ivy Support](https://thymikee.github.io/jest-preset-angular/docs/guides/angular-ivy), but get installation warnings because of incompatible version ranges and runtime errors which are likely caused by said version conflicts.

**Describe the solution you'd like**
Update dependency from 8.4.0 to 9.0.0

**Describe alternatives you've considered**
Not updating, which is not that much fun 😉 

**Additional context**

**Comment by jbpzen** [comment]
It is a work in progress here #913

**Comment by just-jeb** [comment]
Please try out `12.1.0-beta.0` (Jest 27 + preset 9). If everything is OK I'll release it officially.

**Comment by PascalHonegger** [comment]
@just-jeb I got my tests running with ivy and the latest jest / angular versions, thanks for the update! I had some problems with ESM, but those might be unrelated to this package and is not a priority for me.

**Comment by just-jeb** [comment]
@PascalHonegger you might find [this](https://thymikee.github.io/jest-preset-angular/docs/guides/esm-support/) helpful.
